window.GE.outfit_database = window.GE.outfit_database || new Map();

window.GE.outfit_database.set("alina", toMap({
  "purchasable": toMap({
    "beach": 3,
    "casual": 3,
    "intimates": 5,
    "gym": 3,
    "lounge": 3,
    "office": 3,
    "stylin": 3
  }),
  "beach": toMap({
    "alina beach louis vuitton bikini": toMap({
      "id": "alina beach louis vuitton bikini",
      "category": "beach",
      "name": "louis vuitton bikini",
      "flavors": [
        "You're not sure of the brand, but it looks sleek and sexy.",
        "Is it really worth this hefty price tag?",
        "When you really need to flex.",
        "Ah, the price we pay for fashion."
      ],
      "description": "louis vuitton branded bikini",
      "price": 495,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 5,
      "style": "sexy",
      "colors": ["black", "peach"],
      "tags": ["swim", "strings"],
      "emphasizes": ["butt"],
      "reveals": ["boobs", "butt", "tummy", "legs"],
      "top": "string bikini top",
      "breasts": "string bikini top",
      "bottom": "string bikini bottom",
      "pussy": "string pattern bikini bottom",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "alina beach fun in the sun": toMap({
      "id": "alina beach fun in the sun",
      "category": "beach",
      "name": "fun in the sun",
      "flavor": "A light and breezy outfit.",
      "description": "pink crop top and jean shorts",
      "price": 125,
      "type": "casual beachwear",
      "sluttiness": 2,
      "comfort": 8,
      "durability": 5,
      "style": "relaxed",
      "colors": ["pink", "blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "pink crop top",
      "breasts": "pink crop top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "beach", "lounge"]
    }),
    "alina beach golden bikini": toMap({
      "id": "alina beach golden bikini",
      "category": "beach",
      "name": "golden bikini",
      "flavor": "Probably shouldn't wear this in the water.",
      "description": "fancy black and gold chain bikini",
      "price": 750,
      "type": "fancy bikini",
      "sluttiness": 7,
      "comfort": 2,
      "durability": 9,
      "style": "bombshell",
      "colors": ["black", "gold"],
      "tags": ["jingle", "straps", "intimidating"],
      "emphasizes": [],
      "reveals": ["tummy", "boobs", "legs", "butt"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "high-waisted bikini bottom",
      "pussy": "high-waisted bikini bottom",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heel boots",
      "locations": ["beach", "fetish", "stylin"]
    }),
    "alina beach green bikini": toMap({
      "id": "alina beach green bikini",
      "category": "beach",
      "name": "green bikini",
      "flavor": "Slightly more coverage than skinny dipping.",
      "description": "green triangle bikini",
      "price": 65,
      "type": "revealing bikini",
      "sluttiness": 7,
      "comfort": 7,
      "durability": 4,
      "style": "slutty",
      "colors": ["green"],
      "tags": ["tiny", "swim"],
      "emphasizes": ["breasts"],
      "reveals": ["tummy", "boobs", "legs", "butt"],
      "top": "triangle bikini top",
      "breasts": "triangle bikini top",
      "bottom": "three-string bikini bottom",
      "pussy": "three-string bikini bottom",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach", "fetish"]
    }),
    "alina beach jeankini": toMap({
      "id": "alina beach jeankini",
      "category": "beach",
      "name": "jeankini",
      "flavor": "Cool girl vibes.",
      "description": "'Vixen' bikini and a pair of ripped jeans",
      "price": 165,
      "type": "casual beachwear",
      "sluttiness": 5,
      "comfort": 8,
      "durability": 5,
      "style": "relaxed",
      "colors": ["black", "red", "white", "blue"],
      "tags": ["two bottom layers"],
      "emphasizes": ["breasts"],
      "reveals": ["tummy", "boobs"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "torn jeans",
      "pussy": "bikini bottom",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["beach", "lounge"]
    }),
    "alina beach one piece": toMap({
      "id": "alina beach one piece",
      "category": "beach",
      "name": "one piece",
      "flavor": "Swim with confidence!",
      "description": "black one-piece swimsuit",
      "price": 110,
      "type": "one-piece swimsuit",
      "sluttiness": 2,
      "comfort": 7,
      "durability": 8,
      "style": "modest",
      "colors": ["black"],
      "tags": ["one piece", "swim"],
      "emphasizes": ["cleavage", "butt"],
      "reveals": ["cleavage", "legs", "butt"],
      "top": "black one-piece",
      "breasts": "black one-piece",
      "bottom": "black one-piece",
      "pussy": "black one-piece",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach"]
    }),
    "alina beach purple swimsuit": toMap({
      "id": "alina beach purple swimsuit",
      "category": "beach",
      "name": "purple swimsuit",
      "flavor": "A bit tricky to put on.",
      "description": "purple swimsuit with a lot of straps",
      "price": 170,
      "type": "one-piece swimsuit",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["purple"],
      "tags": ["one piece", "swim"],
      "emphasizes": ["cleavage", "butt"],
      "reveals": ["cleavage", "legs", "butt", "tummy"],
      "top": "purple swimsuit",
      "breasts": "purple swimsuit",
      "bottom": "purple swimsuit",
      "pussy": "purple swimsuit",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach"]
    }),
    "alina beach vixen bikini": toMap({
      "id": "alina beach vixen bikini",
      "category": "beach",
      "name": "vixen bikini",
      "flavor": "Not sure what 'Vixen' is, but I look like a model in this!",
      "description": "bikini that says 'Vixen'",
      "price": 250,
      "type": "bikini",
      "sluttiness": 7,
      "comfort": 6,
      "durability": 5,
      "style": "sexy",
      "colors": ["black", "white", "red"],
      "tags": ["swim"],
      "emphasizes": ["boobs", "butt"],
      "reveals": ["boobs", "legs", "tummy", "butt"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach"]
    })
  }),
  "casual": toMap({
    "alina casual bad girls club": toMap({
      "id": "alina casual bad girls club",
      "category": "casual",
      "name": "bad girls club",
      "flavor": "Certified proof that you're a 'bad girl'!",
      "description": "black crop top and skirt",
      "price": 85,
      "type": "casual sexy",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 3,
      "style": "sexy",
      "colors": ["black"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "black crop top",
      "breasts": "black crop top",
      "bottom": "black cutaway skirt",
      "pussy": "black cutaway skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "beach", "lounge"]
    }),
    "alina casual collegiate": toMap({
      "id": "alina casual collegiate",
      "category": "casual",
      "name": "collegiate",
      "flavor": "Does this outfit make me look smarter?",
      "description": "white tank top, brown shirt and plaid pants",
      "price": 125,
      "type": "casual smart",
      "sluttiness": 1,
      "comfort": 4,
      "durability": 6,
      "style": "smart",
      "colors": ["white", "brown", "grey"],
      "tags": ["intelligent"],
      "emphasizes": [],
      "reveals": [],
      "top": "brown shirt",
      "breasts": "white tank top",
      "bottom": "plaid pants",
      "pussy": "plaid pants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["beach", "lounge", "casual"]
    }),
    "alina casual cropped hoodie": toMap({
      "id": "alina casual cropped hoodie",
      "category": "casual",
      "name": "cropped hoodie",
      "flavor": "Comfy yet super sexy.",
      "description": "cropped hoodie and booty shorts",
      "price": 85,
      "type": "casual sexy",
      "sluttiness": 7,
      "comfort": 9,
      "durability": 6,
      "style": "sexy",
      "colors": ["grey", "blue"],
      "tags": ["asscheeks"],
      "emphasizes": ["butt"],
      "reveals": ["asscheeks", "tummy", "legs"],
      "top": "cropped grey hoodie",
      "breasts": "cropped grey hoodie",
      "bottom": "booty shorts",
      "pussy": "booty shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["lounge", "casual"]
    }),
    "alina casual flowery dress": toMap({
      "id": "alina casual flowery dress",
      "category": "casual",
      "name": "flowery dress",
      "flavor": "A dress almost as pretty as you!",
      "description": "white off-shoulder dress with blue flowers",
      "price": 200,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 5,
      "style": "cute",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "white flower dress",
      "breasts": "white flower dress",
      "bottom": "white flower dress",
      "pussy": "white flower dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["lounge", "casual", "office"]
    }),
    "alina casual golf vibes": toMap({
      "id": "alina casual golf vibes",
      "category": "casual",
      "name": "golf vibes",
      "flavor": "Don't bend over too far in this.",
      "description": "pink top and short grey skirt",
      "price": 225,
      "type": "skirt and blouse",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 6,
      "style": "cute",
      "colors": ["pink", "grey"],
      "tags": ["easy access skirt"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "pink top",
      "breasts": "pink top",
      "bottom": "short grey skirt",
      "pussy": "short grey skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "golf shoes",
      "locations": ["lounge", "casual", "office"]
    }),
    "alina casual grey tank top": toMap({
      "id": "alina casual grey tank top",
      "category": "casual",
      "name": "grey tank top",
      "flavor": "Sometimes, less is more!",
      "description": "grey tank top and jean shorts",
      "price": 70,
      "type": "casual sexy",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 5,
      "style": "sexy",
      "colors": ["grey", "blue"],
      "tags": ["asscheeks"],
      "emphasizes": ["butt"],
      "reveals": ["asscheeks", "tummy", "legs"],
      "top": "grey tank top",
      "breasts": "grey tank top",
      "bottom": "booty shorts",
      "pussy": "booty shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["lounge", "casual"]
    }),
    "alina casual hipster cafe outfit": toMap({
      "id": "alina casual hipster cafe outfit",
      "category": "casual",
      "name": "hipster cafe outfit",
      "flavor": "This getup screams 'pumpkin spice latte'.",
      "description": "wispy green blouse and yoga pants",
      "price": 85,
      "type": "casual smart",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 4,
      "style": "smart",
      "colors": ["green", "black"],
      "tags": ["see through top", "intelligent"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "wispy green top",
      "breasts": "wispy green top",
      "bottom": "booty shorts",
      "pussy": "booty shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "uggs",
      "locations": ["lounge", "casual", "office"]
    }),
    "alina casual hot girl summer": toMap({
      "id": "alina casual hot girl summer",
      "category": "casual",
      "name": "hot girl summer",
      "flavor": "This will probably bring the boys to the yard.",
      "description": "bikini top and booty shorts",
      "price": 115,
      "type": "casual slutty",
      "sluttiness": 8,
      "comfort": 6,
      "durability": 3,
      "style": "slutty",
      "colors": ["pink", "blue"],
      "tags": ["asscheeks"],
      "emphasizes": ["asscheeks"],
      "reveals": ["asscheeks", "tummy", "legs", "boobs"],
      "top": "pink bikini top",
      "breasts": "pink bikini top",
      "bottom": "booty shorts",
      "pussy": "booty shorts",
      "breast support": 5,
      "panties under": "can",
      "bra under": "no",
      "shoes": "slides",
      "locations": ["lounge", "casual", "beach"]
    }),
    "alina casual overall dress": toMap({
      "id": "alina casual overall dress",
      "category": "casual",
      "name": "overall dress",
      "flavor": "It's pretty cute, overall. ",
      "description": "blue denim dress",
      "price": 65,
      "type": "dress",
      "sluttiness": 3,
      "comfort": 4,
      "durability": 9,
      "style": "cute",
      "colors": ["blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": [],
      "top": "blue denim dress",
      "breasts": "blue denim dress",
      "bottom": "blue denim dress",
      "pussy": "blue denim dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["lounge", "casual", "office"]
    }),
    "alina casual picnic top": toMap({
      "id": "alina casual picnic top",
      "category": "casual",
      "name": "picnic top",
      "flavor": "A cute outfits for cute moments. Like a picnic!",
      "description": "loose seersucker top and jean shorts",
      "price": 110,
      "type": "shorts and blouse",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 6,
      "style": "cute",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "loose seersucker top",
      "breasts": "loose seersucker top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["lounge", "casual", "office", "beach"]
    }),
    "alina casual python tube top": toMap({
      "id": "alina casual python tube top",
      "category": "casual",
      "name": "python tube top",
      "flavor": "You'll have to really slither into this.",
      "description": "snakeskin tube top and booty shorts",
      "price": 80,
      "type": "casual slutty",
      "sluttiness": 7,
      "comfort": 7,
      "durability": 4,
      "style": "slutty",
      "colors": ["brown", "blue"],
      "tags": ["asscheeks"],
      "emphasizes": ["asscheeks"],
      "reveals": ["asscheeks", "tummy", "legs"],
      "top": "snakeskin tube top",
      "breasts": "snakeskin tube top",
      "bottom": "booty shorts",
      "pussy": "booty shorts",
      "breast support": 2,
      "panties under": "can",
      "bra under": "no",
      "shoes": "slides",
      "locations": ["lounge", "casual"]
    })
  }),
  "fetish": toMap({
    "alina fetish collared bitch": toMap({
      "id": "alina fetish collared bitch",
      "category": "fetish",
      "name": "collared bitch",
      "flavor": "The collar tells everyone you know your place.",
      "description": "fancy studded bikini with a thick collar",
      "price": 600,
      "type": "fancy bikini",
      "sluttiness": 9,
      "comfort": 2,
      "durability": 4,
      "style": "slutty",
      "colors": ["black", "silver"],
      "tags": ["jingle", "straps", "collar"],
      "emphasizes": [],
      "reveals": ["tummy", "boobs", "legs", "butt"],
      "top": "studded bikini top",
      "breasts": "studded bikini top",
      "bottom": "three-string bikini bottom",
      "pussy": "three-string bikini bottom",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach", "fetish"]
    }),
    "alina fetish insufficient skirt": toMap({
      "id": "alina fetish insufficient skirt",
      "category": "fetish",
      "name": "insufficient skirt",
      "flavor": "Who knows what'll happen if you walk around with this on…",
      "description": "black bralette and a super short skirt",
      "price": 45,
      "type": "fetish",
      "sluttiness": 10,
      "comfort": 4,
      "durability": 2,
      "style": "slutty",
      "colors": ["black", "red"],
      "tags": ["easy access skirt"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "entire butt"],
      "top": "black bralette",
      "breasts": "black bralette",
      "bottom": "short red skirt",
      "pussy": "short red skirt",
      "breast support": 4,
      "panties under": "can",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish", "lounge"]
    }),
    "alina fetish velvet": toMap({
      "id": "alina fetish velvet",
      "category": "fetish",
      "name": "velvet",
      "flavor": "Really sexy, yet really classy too. ",
      "description": "classy set of black lingerie",
      "price": 400,
      "type": "classy lingerie",
      "sluttiness": 8,
      "comfort": 5,
      "durability": 4,
      "style": "slutty",
      "colors": ["black", "silver"],
      "tags": ["jingle", "straps", "collar"],
      "emphasizes": [],
      "reveals": ["tummy", "boobs", "legs", "butt"],
      "top": "black bra",
      "breasts": "black bra",
      "bottom": "black girdle",
      "pussy": "black girdle",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish", "lingerie"]
    }),
    "alina fetish vinyl": toMap({
      "id": "alina fetish vinyl",
      "category": "fetish",
      "name": "vinyl",
      "flavor": "Don't wear this to family Thanksgiving.",
      "description": "vinyl bodysuit, fishnets, and high-heels",
      "price": 275,
      "type": "fetish",
      "sluttiness": 9,
      "comfort": 2,
      "durability": 5,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["fishnet stockings"],
      "emphasizes": ["butt"],
      "reveals": ["boobs", "butt", "legs", "tummy"],
      "top": "black vinyl bra",
      "breasts": "black vinyl bra",
      "bottom": "high-waisted vinyl panties",
      "pussy": "high-waisted vinyl panties",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["fetish", "lingerie"]
    })
  }),
  "gym": toMap({
    "alina gym acrobatic": toMap({
      "id": "alina gym acrobatic",
      "category": "gym",
      "name": "acrobatic",
      "flavors": [
        "This workout outfit exposes more skin than typical activewear.",
        "Reenacting Call on Me might get you a lot of looks at the gym..."
      ],
      "description": "tan tank top and orange sports thong",
      "price": 65,
      "type": "workout",
      "sluttiness": 8,
      "comfort": 5,
      "durability": 2,
      "style": "sexy fitness",
      "colors": ["tan", "orange"],
      "tags": ["standalone lingerie"],
      "emphasizes": ["boobs", "butt"],
      "reveals": ["boobs", "butt", "tummy", "legs"],
      "top": "tan sports tanktop",
      "breasts": "tan sports tanktop",
      "bottom": "orange sports thong",
      "pussy": "orange sports thong",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    }),
    "alina gym 80s fitness": toMap({
      "id": "alina gym 80s fitness",
      "category": "gym",
      "name": "80s fitness",
      "flavor": "An easy way to stick out at the gym.",
      "description": "blue bodysuit and pink accompaniments",
      "price": 175,
      "type": "sexy fitness",
      "sluttiness": 5,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["blue", "pink"],
      "tags": ["one piece"],
      "emphasizes": ["butt", "legs"],
      "reveals": ["butt", "legs"],
      "top": "blue bodysuit",
      "breasts": "blue bodysuit",
      "bottom": "blue bodysuit",
      "pussy": "blue bodysuit",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym"]
    }),
    "alina gym modest fitness outfit": toMap({
      "id": "alina gym modest fitness outfit",
      "category": "gym",
      "name": "modest fitness outfit",
      "flavor": "You just want to work out!",
      "description": "black tank top and black spandex pants",
      "price": 125,
      "type": "casual fitness",
      "sluttiness": 1,
      "comfort": 6,
      "durability": 6,
      "style": "casual",
      "colors": ["black"],
      "tags": [],
      "emphasizes": ["butt"],
      "reveals": [],
      "top": "black tank top",
      "breasts": "black tank top",
      "bottom": "black yoga pants",
      "pussy": "black yoga pants",
      "breast support": 2,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["gym"]
    }),
    "alina gym orange sports bra": toMap({
      "id": "alina gym orange sports bra",
      "category": "gym",
      "name": "orange sports bra",
      "flavor": "Shows a little underboob.",
      "description": "orange sports bra and black panties",
      "price": 75,
      "type": "sexy fitness",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["orange", "black"],
      "tags": ["standalone lingerie"],
      "emphasizes": ["boobs", "butt"],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "orange sports bra",
      "breasts": "orange sports bra",
      "bottom": "black sports panties",
      "pussy": "black sports panties",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lingerie", "lounge"]
    }),
    "alina gym white sports bra": toMap({
      "id": "alina gym white sports bra",
      "category": "gym",
      "name": "white sports bra",
      "flavor": "Showing a lot of skin, but this is for working out.",
      "description": "white sports bra and grey sport shorts",
      "price": 55,
      "type": "sexy fitness",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 3,
      "style": "sexy",
      "colors": ["white", "black"],
      "tags": [],
      "emphasizes": ["cleavage", "butt"],
      "reveals": ["tummy", "cleavage", "butt"],
      "top": "white sports bra",
      "breasts": "white sports bra",
      "bottom": "grey sport shorts",
      "pussy": "grey sport shorts",
      "breast support": 9,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    }),
    "alina gym yoga outfit": toMap({
      "id": "alina gym yoga outfit",
      "category": "gym",
      "name": "yoga outfit",
      "flavor": "Featuring a front-zip sports bra for 'easy access'.",
      "description": "front-zip sports bra and white yoga pants",
      "price": 155,
      "type": "sexy fitness",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 6,
      "style": "sexy",
      "colors": ["blue", "white"],
      "tags": ["front-zip"],
      "emphasizes": ["cleavage", "butt"],
      "reveals": ["tummy", "cleavage"],
      "top": "blue sports bra",
      "breasts": "blue sports bra",
      "bottom": "white yoga pants",
      "pussy": "white yoga pants",
      "breast support": 9,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    }),
    "alina gym gym slut": toMap({
      "id": "alina gym gym slut",
      "category": "gym",
      "name": "gym slut",
      "flavor": "You'll get a lot of looks at the gym, that's for sure.",
      "description": "black and pink sports bra and sock thingys",
      "price": 120,
      "type": "slutty fitness",
      "sluttiness": 10,
      "comfort": 6,
      "durability": 3,
      "style": "slutty",
      "colors": ["black", "pink"],
      "tags": ["standalone lingerie"],
      "emphasizes": ["boobs", "butt"],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "string triangle bra",
      "breasts": "string triangle bra",
      "bottom": "black sports panties",
      "pussy": "black sports panties",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lingerie", "lounge"]
    }),
    "alina gym light and fit": toMap({
      "id": "alina gym light and fit",
      "category": "gym",
      "name": "light and fit",
      "flavor": "A casual yet sexy way to work out. ",
      "description": "black sports bra and pink running shorts",
      "price": 40,
      "type": "casual fitness",
      "sluttiness": 5,
      "comfort": 7,
      "durability": 3,
      "style": "casual",
      "colors": ["black", "pink"],
      "tags": [],
      "emphasizes": ["cleavage", "butt"],
      "reveals": ["tummy", "cleavage", "butt"],
      "top": "black sports bra",
      "breasts": "black sports bra",
      "bottom": "pink sports shorts",
      "pussy": "pink sports shorts",
      "breast support": 9,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    })
  }),
  "lingerie": toMap({
    "alina lingerie black fishnet lingerie": toMap({
      "id": "alina lingerie black fishnet lingerie",
      "category": "lingerie",
      "name": "black fishnet lingerie",
      "flavor": "A favorite gift of sugar daddies everywhere.",
      "description": "balconette bra, panties, and stockings",
      "price": 450,
      "type": "fancy lingerie",
      "sluttiness": 8,
      "comfort": 2,
      "durability": 2,
      "style": "classy",
      "colors": ["black"],
      "tags": ["stockings", "straps", "gift"],
      "emphasizes": ["boobs", "butt", "legs"],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "balconette bra",
      "breasts": "balconette bra",
      "bottom": "fishnet panties",
      "pussy": "fishnet panties",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie", "fetish"]
    }),
    "alina lingerie floral lingerie": toMap({
      "id": "alina lingerie floral lingerie",
      "category": "lingerie",
      "name": "floral lingerie",
      "flavor": "See-through, but still elegant.",
      "description": "balconette bra, panties, and stockings",
      "price": 150,
      "type": "lingerie",
      "sluttiness": 8,
      "comfort": 4,
      "durability": 3,
      "style": "classy",
      "colors": ["black"],
      "tags": [],
      "emphasizes": ["boobs", "butt", "legs"],
      "reveals": ["boobs", "tummy", "butt", "nipples", "pussy"],
      "top": "see-through bra",
      "breasts": "see-through bra",
      "bottom": "see-through panties",
      "pussy": "see-through panties",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "alina lingerie lacy white lingerie": toMap({
      "id": "alina lingerie lacy white lingerie",
      "category": "lingerie",
      "name": "lacy white lingerie",
      "flavor": "A sexy wardrobe staple.",
      "description": "white bra and high-waisted string panties",
      "price": 65,
      "type": "lingerie",
      "sluttiness": 9,
      "comfort": 6,
      "durability": 3,
      "style": "casual",
      "colors": ["white"],
      "tags": [],
      "emphasizes": ["boobs", "butt", "legs"],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "white bra",
      "breasts": "white bra",
      "bottom": "high-waisted white string panties",
      "pussy": "high-waisted white string panties",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "alina lingerie black lingerie": toMap({
      "id": "alina lingerie black lingerie",
      "category": "lingerie",
      "name": "black lingerie",
      "flavor": "Comfy and casual lingerie.",
      "description": "bra and panties",
      "price": 30,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 10,
      "durability": 4,
      "style": "casual",
      "colors": ["black"],
      "tags": [],
      "emphasizes": ["boobs", "butt", "legs"],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "black bra",
      "breasts": "black bra",
      "bottom": "black panties",
      "pussy": "black panties",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "alina lingerie lacy bustier": toMap({
      "id": "alina lingerie lacy bustier",
      "category": "lingerie",
      "name": "lacy bustier",
      "flavor": "Classy and supportive.",
      "description": "lacy bustier and matching panties",
      "price": 75,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 5,
      "durability": 8,
      "style": "classy",
      "colors": ["black"],
      "tags": [],
      "emphasizes": ["boobs", "butt", "legs"],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "bustier",
      "breasts": "bustier",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 10,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "alina lingerie loungerie": toMap({
      "id": "alina lingerie loungerie",
      "category": "lingerie",
      "name": "loungerie",
      "flavor": "Comfy and soft lingerie.",
      "description": "bra and panties",
      "price": 35,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 10,
      "durability": 4,
      "style": "casual",
      "colors": ["grey", "black"],
      "tags": [],
      "emphasizes": ["boobs", "butt", "legs"],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "grey bra",
      "breasts": "grey bra",
      "bottom": "grey panties",
      "pussy": "grey panties",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "alina lingerie scarlit moment": toMap({
      "id": "alina lingerie scarlit moment",
      "category": "lingerie",
      "name": "scarlit moment",
      "flavor": "Red little devil.",
      "description": "bra and panties",
      "price": 75,
      "type": "lingerie",
      "sluttiness": 7,
      "comfort": 7,
      "durability": 4,
      "style": "sexy",
      "colors": ["red"],
      "tags": [],
      "emphasizes": ["boobs", "butt", "legs"],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "red bra",
      "breasts": "red bra",
      "bottom": "red panties",
      "pussy": "red panties",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "alina lingerie valentine": toMap({
      "id": "alina lingerie valentine",
      "category": "lingerie",
      "name": "valentine",
      "flavor": "Cute and sweet!",
      "description": "bra and panties",
      "price": 65,
      "type": "lingerie",
      "sluttiness": 5,
      "comfort": 8,
      "durability": 3,
      "style": "cute",
      "colors": ["red"],
      "tags": [],
      "emphasizes": ["boobs", "butt", "legs"],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "red bra",
      "breasts": "red bra",
      "bottom": "red panties",
      "pussy": "red panties",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "alina lingerie straps for days": toMap({
      "id": "alina lingerie straps for days",
      "category": "lingerie",
      "name": "straps for days",
      "flavor": "Like a present waiting to be unwrapped.",
      "description": "one-piece lingerie",
      "price": 145,
      "type": "lingerie",
      "sluttiness": 8,
      "comfort": 5,
      "durability": 6,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["straps"],
      "emphasizes": ["boobs", "butt", "legs"],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "black lingerie",
      "breasts": "black lingerie",
      "bottom": "black lingerie",
      "pussy": "black lingerie",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    })
  }),
  "lounge": toMap({
    "alina lounge cami": toMap({
      "id": "alina lounge cami",
      "category": "lounge",
      "name": "cami",
      "flavor": "This pattern cami is super comfy.",
      "description": "white flower cami and pink shorts",
      "price": 45,
      "type": "loungewear",
      "sluttiness": 3,
      "comfort": 8,
      "durability": 3,
      "style": "lazy",
      "colors": ["white", "pink"],
      "tags": [],
      "emphasizes": ["butt", "legs"],
      "reveals": ["legs", "butt"],
      "top": "white flower cami",
      "breasts": "white flower cami",
      "bottom": "pink shorts",
      "pussy": "pink shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge", "casual"]
    }),
    "alina lounge pink onesie": toMap({
      "id": "alina lounge pink onesie",
      "category": "lounge",
      "name": "pink onesie",
      "flavor": "Yeah, it's cute.",
      "description": "pink onesie",
      "price": 65,
      "type": "loungewear",
      "sluttiness": 4,
      "comfort": 9,
      "durability": 5,
      "style": "lazy",
      "colors": ["pink"],
      "tags": ["one piece"],
      "emphasizes": ["butt", "legs"],
      "reveals": ["legs", "butt"],
      "top": "pink onesie",
      "breasts": "pink onesie",
      "bottom": "pink onesie",
      "pussy": "pink onesie",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "alina lounge red tshirt": toMap({
      "id": "alina lounge red tshirt",
      "category": "lounge",
      "name": "red tshirt",
      "flavor": "Netflix and chill!",
      "description": "red tshirt and white panties",
      "price": 40,
      "type": "loungewear",
      "sluttiness": 6,
      "comfort": 8,
      "durability": 4,
      "style": "lazy",
      "colors": ["red", "white"],
      "tags": [],
      "emphasizes": ["butt", "legs"],
      "reveals": ["legs", "butt"],
      "top": "red t-shirt",
      "breasts": "red t-shirt",
      "bottom": "white panties",
      "pussy": "white panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "alina lounge tube top": toMap({
      "id": "alina lounge tube top",
      "category": "lounge",
      "name": "tube top",
      "flavor": "It's probably distracting to wear this around the house…",
      "description": "white tube top and red panties",
      "price": 45,
      "type": "loungewear",
      "sluttiness": 8,
      "comfort": 8,
      "durability": 3,
      "style": "lazy",
      "colors": ["white", "red"],
      "tags": [],
      "emphasizes": ["butt", "legs"],
      "reveals": ["legs", "butt", "belly"],
      "top": "white tube top",
      "breasts": "white tube top",
      "bottom": "red panties",
      "pussy": "red panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "alina lounge white nightgown": toMap({
      "id": "alina lounge white nightgown",
      "category": "lounge",
      "name": "white nightgown",
      "flavor": "A cute and elegant way to lounge.",
      "description": "lacy white nightgown",
      "price": 65,
      "type": "loungewear",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 3,
      "style": "elegant",
      "colors": ["white"],
      "tags": ["one piece", "easy access dress"],
      "emphasizes": ["cleavage", "legs"],
      "reveals": ["cleavage", "legs"],
      "top": "nightgown",
      "breasts": "nightgown",
      "bottom": "nightgown",
      "pussy": "nightgown",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    })
  }),
  "office": toMap({
    "alina office blazer and boobs": toMap({
      "id": "alina office blazer and boobs",
      "category": "office",
      "name": "blazer and boobs",
      "flavor": "For the ruthless businesswoman in you!",
      "description": "navy blazer and low-cut blouse",
      "price": 275,
      "type": "sexy office",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 6,
      "style": "sexy",
      "colors": ["blue", "purple"],
      "tags": ["two layer top", "very professional"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "navy blazer",
      "breasts": "low-cut underwire blouse",
      "bottom": "pencil skirt",
      "pussy": "pencil skirt",
      "breast support": 4,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "alina office burgundy sweater": toMap({
      "id": "alina office burgundy sweater",
      "category": "office",
      "name": "burgundy sweater",
      "flavor": "A conservative choice for the office.",
      "description": "burgundy cable sweater and green plaid blouse",
      "price": 95,
      "type": "modest office",
      "sluttiness": 1,
      "comfort": 7,
      "durability": 7,
      "style": "sexy",
      "colors": ["red", "green"],
      "tags": ["professional"],
      "emphasizes": [],
      "reveals": [],
      "top": "burgundy sweater",
      "breasts": "burgundy sweater",
      "bottom": "plaid skirt",
      "pussy": "plaid skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["office"]
    }),
    "alina office conservative elegance": toMap({
      "id": "alina office conservative elegance",
      "category": "office",
      "name": "conservative elegance",
      "flavor": "An elegant work blouse and skirt.",
      "description": "navy blazer and low-cut blouse",
      "price": 145,
      "type": "elegant office",
      "sluttiness": 1,
      "comfort": 5,
      "durability": 5,
      "style": "elegant",
      "colors": ["white", "blue"],
      "tags": ["professional"],
      "emphasizes": ["legs"],
      "reveals": ["legs"],
      "top": "white blouse",
      "breasts": "white blouse",
      "bottom": "navy skirt",
      "pussy": "navy skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "alina office hogwarts": toMap({
      "id": "alina office hogwarts",
      "category": "office",
      "name": "hogwarts",
      "flavor": "Looks a bit more like a schoolgirl than office lady… but who cares? ",
      "description": "navy sweater and grey skirt",
      "price": 175,
      "type": "casual office",
      "sluttiness": 5,
      "comfort": 5,
      "durability": 6,
      "style": "casual",
      "colors": ["navy", "grey"],
      "tags": ["schoolgirl", "professional", "easy access skirt"],
      "emphasizes": ["butt", "legs"],
      "reveals": ["legs"],
      "top": "navy sweater",
      "breasts": "navy sweater",
      "bottom": "grey skirt",
      "pussy": "grey skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "alina office sunflower": toMap({
      "id": "alina office sunflower",
      "category": "office",
      "name": "sunflower",
      "flavor": "Need to close a deal? Unbutton the blouse!",
      "description": "yellow blouse and short skirt",
      "price": 195,
      "type": "slutty office",
      "sluttiness": 9,
      "comfort": 5,
      "durability": 5,
      "style": "slutty",
      "colors": ["yellow", "black"],
      "tags": ["easy access skirt", "professional"],
      "emphasizes": ["cleavage", "legs"],
      "reveals": ["cleavage", "legs"],
      "top": "yellow blouse",
      "breasts": "yellow blouse",
      "bottom": "short black skirt",
      "pussy": "short black skirt",
      "breast support": 4,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "alina office houndstooth": toMap({
      "id": "alina office houndstooth",
      "category": "office",
      "name": "houndstooth",
      "flavor": "Total girlboss outfit!",
      "description": "white button-down and houndstooth pants",
      "price": 130,
      "type": "casual office",
      "sluttiness": 3,
      "comfort": 6,
      "durability": 7,
      "style": "casual",
      "colors": ["white", "brown"],
      "tags": [],
      "emphasizes": ["legs", "hips", "butt", "professional"],
      "reveals": [],
      "top": "white button-down top",
      "breasts": "white button-down top",
      "bottom": "houndstooth pants",
      "pussy": "houndstooth pants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["office"]
    }),
    "alina office turtleneck and stockings": toMap({
      "id": "alina office turtleneck and stockings",
      "category": "office",
      "name": "turtleneck and stockings",
      "flavor": "The skirt really shows off your butt.",
      "description": "grey sweater and burgundy skirt",
      "price": 140,
      "type": "sexy office",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 5,
      "style": "sexy",
      "colors": ["grey", "red"],
      "tags": ["stockings", "professional"],
      "emphasizes": ["butt", "legs"],
      "reveals": [],
      "top": "burgundy sweater",
      "breasts": "burgundy sweater",
      "bottom": "plaid skirt",
      "pussy": "plaid skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    })
  }),
  "stylin": toMap({
    "alina stylin blue velour": toMap({
      "id": "alina stylin blue velour",
      "category": "stylin",
      "name": "blue velour",
      "flavor": "This dress is super elegant, and makes you feel confident.",
      "description": "blue dress",
      "price": 1125,
      "type": "dress",
      "sluttiness": 3,
      "comfort": 4,
      "durability": 8,
      "style": "elegant",
      "colors": ["blue"],
      "tags": ["gift"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "blue dress",
      "breasts": "blue dress",
      "bottom": "blue dress",
      "pussy": "blue dress",
      "breast support": 4,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "alina stylin caged": toMap({
      "id": "alina stylin caged",
      "category": "stylin",
      "name": "caged",
      "flavor": "A classy way to get that 'barely contained' look.",
      "description": "white off-shoulder top and matching skirt",
      "price": 180,
      "type": "blouse and skirt",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 3,
      "style": "sexy",
      "colors": ["white"],
      "tags": ["easy access skirt"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy"],
      "top": "off-shoulder top",
      "breasts": "off-shoulder top",
      "bottom": "white skirt",
      "pussy": "white skirt",
      "breast support": 4,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "alina stylin cute and frilly": toMap({
      "id": "alina stylin cute and frilly",
      "category": "stylin",
      "name": "cute and frilly",
      "flavor": "Girly and adorable!",
      "description": "pink princess dress",
      "price": 250,
      "type": "dress",
      "sluttiness": 2,
      "comfort": 5,
      "durability": 4,
      "style": "cute",
      "colors": ["pink"],
      "tags": ["princess", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "pink dress",
      "breasts": "pink dress",
      "bottom": "pink dress",
      "pussy": "pink dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "glass slippers",
      "locations": ["stylin"]
    }),
    "alina stylin fresh pink": toMap({
      "id": "alina stylin fresh pink",
      "category": "stylin",
      "name": "fresh pink",
      "flavor": "Cute and naughty!",
      "description": "pink sleeve dress",
      "price": 175,
      "type": "dress",
      "sluttiness": 6,
      "comfort": 8,
      "durability": 3,
      "style": "cute",
      "colors": ["pink"],
      "tags": ["one piece", "easy access skirt", "asscheeks"],
      "emphasizes": ["cleavage", "butt", "legs"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "pink dress",
      "breasts": "pink dress",
      "bottom": "pink dress",
      "pussy": "pink dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["stylin", "office"]
    }),
    "alina stylin glitzy": toMap({
      "id": "alina stylin glitzy",
      "category": "stylin",
      "name": "glitzy",
      "flavor": "It sparkles!",
      "description": "sparkly bralette and pink skirt",
      "price": 300,
      "type": "blouse and skirt",
      "sluttiness": 6,
      "comfort": 8,
      "durability": 3,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["easy access skirt"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "bralette",
      "breasts": "bralette",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 8,
      "panties under": "can",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["stylin", "office"]
    }),
    "alina stylin violet top": toMap({
      "id": "alina stylin violet top",
      "category": "stylin",
      "name": "violet top",
      "flavor": "This is really eye catching.",
      "description": "bodysuit and skirt",
      "price": 300,
      "type": "bodysuit and skirt",
      "sluttiness": 4,
      "comfort": 5,
      "durability": 5,
      "style": "sexy",
      "colors": ["purple", "black"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "office", "casual"]
    }),
    "alina stylin white off shoulder": toMap({
      "id": "alina stylin white off shoulder",
      "category": "stylin",
      "name": "white off shoulder",
      "flavor": "Long sleeved, yet really sexy. ",
      "description": "off-shoulder top and matching skirt",
      "price": 160,
      "type": "blouse and skirt",
      "sluttiness": 4,
      "comfort": 5,
      "durability": 5,
      "style": "sexy",
      "colors": ["white"],
      "tags": [],
      "emphasizes": ["butt"],
      "reveals": ["tummy", "cleavage", "legs"],
      "top": "off-shoulder top",
      "breasts": "off-shoulder top",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "office", "casual"]
    })
  })
}));