window.GE.outfit_database = window.GE.outfit_database || new Map();

window.GE.outfit_database.set("cassidy", toMap({
  "purchasable": toMap({
    "beach": 6,
    "casual": 3,
    "fetish": 2,
    "lingerie": 3,
    "gym": 3,
    "lounge": 3,
    "office": 3,
    "stylin": 4
  }),
  "beach": toMap({
    "cassidy beach cheetah print bikini": toMap({
      "id": "cassidy beach cheetah print bikini",
      "category": "beach",
      "name": "cheetah print bikini",
      "flavors": [
        "This bikini may or may not make you feel like a wild animal. Predator, or prey?",
        "This will probably attract a lot of attention.",
        "You never considered yourself a cheetah print person... but now as a girl you can kinda rock it."
      ],
      "description": "black & cheetah print bikini",
      "price": 85,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 3,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["swim", "strings"],
      "emphasizes": ["boobs", "butt"],
      "reveals": ["boobs", "butt", "tummy", "legs"],
      "top": "black bikini top",
      "breasts": "black bikini top",
      "bottom": "cheetah pattern bikini bottom",
      "pussy": "cheetah pattern bikini bottom",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "cassidy beach pink and yellow bikini": toMap({
      "id": "cassidy beach pink and yellow bikini",
      "category": "beach",
      "name": "mismatched pink & yellow bikini",
      "flavors": [
        "This bikini top barely holds in your huge breasts, hopefully it doesn't come off in the water...",
        "This skimpy string bikini is more for showing off than for swimming.",
        "These really go together?"
      ],
      "description": "pink and yellow bikini",
      "price": 39,
      "type": "bikini",
      "sluttiness": 9,
      "comfort": 5,
      "durability": 2,
      "style": "slutty",
      "colors": ["yellow", "pink"],
      "tags": ["swim", "strings", "waterproof"],
      "emphasizes": ["boobs", "butt"],
      "reveals": ["boobs", "butt", "tummy", "legs"],
      "top": "neon yellow string bikini top",
      "breasts": "neon yellow string bikini top",
      "bottom": "neon pink string bikini bottom",
      "pussy": "neon pink string bikini bottom",
      "breast support": 2,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "cassidy beach crochet bikini": toMap({
      "id": "cassidy beach crochet bikini",
      "category": "beach",
      "name": "crochet bikini",
      "flavors": [
        "There's barely enough fabric here to be considered a bikini.",
        "Surprisingly waterproof, but it likely won't stay on in the water.",
        "If you so much as breathe too hard this will slip off!"
      ],
      "description": "white crochet bikini",
      "price": 35,
      "type": "dress",
      "sluttiness": 8,
      "comfort": 6,
      "durability": 1,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["swim", "strings"],
      "emphasizes": ["boobs", "butt"],
      "reveals": ["boobs", "butt", "tummy", "legs"],
      "top": "crochet bikini top",
      "breasts": "crochet bikini top",
      "bottom": "crochet bikini bottom",
      "pussy": "crochet bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "cassidy beach beach bum": toMap({
      "id": "cassidy beach beach bum",
      "category": "beach",
      "name": "beach bum",
      "flavor": "They'll be lining up to help you apply sunscreen.",
      "description": "rainbow knit bikini top and jean shorts",
      "price": 150,
      "type": "casual beachwear",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 4,
      "style": "relaxed",
      "colors": ["pink", "blue"],
      "tags": ["two bottom layers", "swim"],
      "emphasizes": ["cleavage", "asscheeks"],
      "reveals": ["tummy", "breasts", "legs", "butt"],
      "top": "rainbow knit bikini top",
      "breasts": "rainbow knit bikini top",
      "bottom": "jean shorts",
      "pussy": "rainbow knit bikini bottom",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["casual", "beach", "lounge"]
    }),
    "cassidy beach blue bikini": toMap({
      "id": "cassidy beach blue bikini",
      "category": "beach",
      "name": "blue bikini",
      "flavor": "You look like the next Bond girl in this. ",
      "description": "blue triangle bikini top and high-waisted bottoms",
      "price": 95,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["blue"],
      "tags": ["swim"],
      "emphasizes": ["boobs", "butt"],
      "reveals": ["boobs", "butt", "tummy"],
      "top": "blue triangle bikini top",
      "breasts": "blue triangle bikini top",
      "bottom": "high-waisted bikini bottom",
      "pussy": "high-waisted bikini bottom",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["casual", "beach"]
    }),
    "cassidy beach cherries": toMap({
      "id": "cassidy beach cherries",
      "category": "beach",
      "name": "cherries",
      "flavor": "Ironically, a girl could easily *lose* her cherry wearing this.",
      "description": "cherry-patterned bikini",
      "price": 120,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 6,
      "style": "sexy",
      "colors": ["white", "red"],
      "tags": ["swim"],
      "emphasizes": ["boobs", "butt"],
      "reveals": ["boobs", "butt", "tummy"],
      "top": "cherry-patterned bikini top",
      "breasts": "cherry-patterned bikini top",
      "bottom": "red bikini bottom",
      "pussy": "red bikini bottom",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "cassidy beach comfy black bikini": toMap({
      "id": "cassidy beach comfy black bikini",
      "category": "beach",
      "name": "comfy black bikini",
      "flavor": "These are really supportive, and fit your tits like a glove. ",
      "description": "stretchy black bikini",
      "price": 210,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 9,
      "durability": 7,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["swim"],
      "emphasizes": ["boobs", "butt"],
      "reveals": ["boobs", "butt", "tummy"],
      "top": "black bikini top",
      "breasts": "black bikini top",
      "bottom": "black bikini bottom",
      "pussy": "black bikini bottom",
      "breast support": 9,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "cassidy beach lifeguard": toMap({
      "id": "cassidy beach lifeguard",
      "category": "beach",
      "name": "lifeguard",
      "flavor": "Flotation devices not included, but you brought your own.",
      "description": "red and black matching bikini, with a tummy buckle",
      "price": 175,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 8,
      "style": "sexy",
      "colors": ["black", "red"],
      "tags": ["swim", "buckle", "zipper"],
      "emphasizes": ["boobs", "butt"],
      "reveals": ["boobs", "butt", "tummy"],
      "top": "front-zip bikini top",
      "breasts": "front-zip bikini top",
      "bottom": "black bikini bottom",
      "pussy": "black bikini bottom",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "cassidy beach neon yellow bikini": toMap({
      "id": "cassidy beach neon yellow bikini",
      "category": "beach",
      "name": "neon yellow bikini",
      "flavor": "You'll be the highlight of someone's day. ",
      "description": "neon yellow bikini with a string tanga",
      "price": 175,
      "type": "bikini",
      "sluttiness": 8,
      "comfort": 5,
      "durability": 3,
      "style": "slutty",
      "colors": ["yellow"],
      "tags": ["swim", "strings"],
      "emphasizes": ["boobs", "butt"],
      "reveals": ["boobs", "butt", "tummy"],
      "top": "string bikini top",
      "breasts": "string bikini top",
      "bottom": "neon yellow bikini bottom",
      "pussy": "neon yellow bikini bottom",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "cassidy beach one piece": toMap({
      "id": "cassidy beach one piece",
      "category": "beach",
      "name": "one piece",
      "flavor": "A fairly tasteful piece of swimwear. Not too revealing.",
      "description": "one-piece swimsuit that says 'Vixen' on the back",
      "price": 95,
      "type": "one-piece swimsuit",
      "sluttiness": 1,
      "comfort": 8,
      "durability": 8,
      "style": "modest",
      "colors": ["black"],
      "tags": ["swim", "one piece"],
      "emphasizes": ["butt"],
      "reveals": ["butt"],
      "top": "one-piece swimsuit",
      "breasts": "one-piece swimsuit",
      "bottom": "one-piece swimsuit",
      "pussy": "one-piece swimsuit",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "cassidy beach pink one piece": toMap({
      "id": "cassidy beach pink one piece",
      "category": "beach",
      "name": "pink one piece",
      "flavor": "Makes you look a little ditzy. But in a cute way!",
      "description": "neon pink one-piece swimsuit",
      "price": 155,
      "type": "one-piece swimsuit",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["swim", "one piece", "straps"],
      "emphasizes": ["butt", "boobs"],
      "reveals": ["butt", "boobs", "legs"],
      "top": "one-piece swimsuit",
      "breasts": "one-piece swimsuit",
      "bottom": "one-piece swimsuit",
      "pussy": "one-piece swimsuit",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "cassidy beach red strap bikini": toMap({
      "id": "cassidy beach red strap bikini",
      "category": "beach",
      "name": "red strap bikini",
      "flavor": "Red and ready.",
      "description": "comfy red bikini top and bottom",
      "price": 130,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 4,
      "style": "sexy",
      "colors": ["red"],
      "tags": ["swim", "straps"],
      "emphasizes": ["butt", "boobs"],
      "reveals": ["butt", "boobs", "legs", "tummy"],
      "top": "red bikini top",
      "breasts": "red bikini top",
      "bottom": "red bikini bottom",
      "pussy": "red bikini bottom",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "cassidy beach red triangle top bikini": toMap({
      "id": "cassidy beach red triangle top bikini",
      "category": "beach",
      "name": "red triangle top bikini",
      "flavor": "You can hardly blame the boys for staring at you in this.",
      "description": "triangle top string bikini",
      "price": 270,
      "type": "bikini",
      "sluttiness": 8,
      "comfort": 4,
      "durability": 2,
      "style": "slutty",
      "colors": ["red"],
      "tags": ["swim", "strings"],
      "emphasizes": ["butt", "boobs"],
      "reveals": ["butt", "boobs", "legs", "tummy"],
      "top": "red bikini top",
      "breasts": "red bikini top",
      "bottom": "red bikini bottom",
      "pussy": "red bikini bottom",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "cassidy beach tiny blue bikini": toMap({
      "id": "cassidy beach tiny blue bikini",
      "category": "beach",
      "name": "tiny blue bikini",
      "flavor": "Honestly, you might as well just show them your nipples at this point.",
      "description": "tiny blue bikini",
      "price": 170,
      "type": "bikini",
      "sluttiness": 9,
      "comfort": 2,
      "durability": 1,
      "style": "slutty",
      "colors": ["blue"],
      "tags": ["swim", "strings"],
      "emphasizes": ["butt", "boobs"],
      "reveals": ["butt", "boobs", "legs", "tummy"],
      "top": "blue bikini top",
      "breasts": "blue bikini top",
      "bottom": "blue bikini bottom",
      "pussy": "blue bikini bottom",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "cassidy beach tiny one piece": toMap({
      "id": "cassidy beach tiny one piece",
      "category": "beach",
      "name": "tiny one piece",
      "flavor": "You'll be practically naked if you get this wet.",
      "description": "microscopic white one-piece",
      "price": 250,
      "type": "one-piece swimsuit",
      "sluttiness": 10,
      "comfort": 3,
      "durability": 1,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["swim", "one piece", "straps", "transparent"],
      "emphasizes": ["butt", "boobs"],
      "reveals": ["butt", "boobs", "legs", "nipples", "pussy"],
      "top": "one-piece swimsuit",
      "breasts": "one-piece swimsuit",
      "bottom": "one-piece swimsuit",
      "pussy": "one-piece swimsuit",
      "breast support": 2,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach", "fetish"]
    }),
    "cassidy beach white string bikini": toMap({
      "id": "cassidy beach white string bikini",
      "category": "beach",
      "name": "white string bikini",
      "flavor": "Your boobs spill out underneath the top. Not a whole lot of support. ",
      "description": "white string bikini",
      "price": 80,
      "type": "bikini",
      "sluttiness": 8,
      "comfort": 3,
      "durability": 1,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["swim", "strings"],
      "emphasizes": ["butt", "boobs"],
      "reveals": ["butt", "boobs", "legs", "tummy", "underboob"],
      "top": "white bikini top",
      "breasts": "white bikini top",
      "bottom": "white bikini bottom",
      "pussy": "white bikini bottom",
      "breast support": 2,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    })
  }),
  "casual": toMap({
    "cassidy casual bookworm": toMap({
      "id": "cassidy casual bookworm",
      "category": "casual",
      "name": "bookworm",
      "flavor": "You don't need the glasses but OMG they complete the outfit!",
      "description": "white blouse under a blue denim dress",
      "price": 95,
      "type": "casual",
      "sluttiness": 3,
      "comfort": 6,
      "durability": 8,
      "style": "cute",
      "colors": ["white", "blue"],
      "tags": ["intelligent", "one piece", "easy access dress"],
      "emphasizes": ["legs"],
      "reveals": ["legs"],
      "top": "blue denim dress",
      "breasts": "blue denim dress",
      "bottom": "blue denim dress",
      "pussy": "blue denim dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "cassidy casual bursting": toMap({
      "id": "cassidy casual bursting",
      "category": "casual",
      "name": "bursting",
      "flavor": "The top is a disaster waiting to happen.",
      "description": "black bralette and high-waisted jeans",
      "price": 60,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 4,
      "durability": 1,
      "style": "sexy",
      "colors": ["black", "blue"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy"],
      "top": "black bralette",
      "breasts": "black bralette",
      "bottom": "blue jeans",
      "pussy": "blue jeans",
      "breast support": 3,
      "panties under": "can",
      "bra under": "no",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "cassidy casual comfy cozy": toMap({
      "id": "cassidy casual comfy cozy",
      "category": "casual",
      "name": "comfy cozy",
      "flavor": "Perfect for those Netflix & chill evenings.",
      "description": "white off-shoulder sweater and ripped jeans",
      "price": 130,
      "type": "casual",
      "sluttiness": 2,
      "comfort": 10,
      "durability": 4,
      "style": "cute",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "white off-shoulder sweater",
      "breasts": "white off-shoulder sweater",
      "bottom": "ripped blue jeans",
      "pussy": "ripped blue jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "cassidy casual floral": toMap({
      "id": "cassidy casual floral",
      "category": "casual",
      "name": "floral",
      "flavor": "A sexy and fun outfit.",
      "description": "floral bralette and checkered maxi skirt",
      "price": 210,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 7,
      "style": "sexy",
      "colors": ["yellow", "black"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy"],
      "top": "floral bralette",
      "breasts": "floral bralette",
      "bottom": "checkered maxi skirt",
      "pussy": "checkered maxi skirt",
      "breast support": 8,
      "panties under": "can",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["casual", "lounge", "stylin"]
    }),
    "cassidy casual frilly tank top": toMap({
      "id": "cassidy casual frilly tank top",
      "category": "casual",
      "name": "frilly tank top",
      "flavor": "Best worn with pigtails.",
      "description": "cropped white tanktop and jean shorts",
      "price": 75,
      "type": "casual",
      "sluttiness": 8,
      "comfort": 8,
      "durability": 4,
      "style": "sexy",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": ["cleavage", "asscheeks"],
      "reveals": ["cleavage", "tummy", "legs", "asscheeks"],
      "top": "cropped white tanktop",
      "breasts": "cropped white tanktop",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "cassidy casual fuscia skirt": toMap({
      "id": "cassidy casual fuscia skirt",
      "category": "casual",
      "name": "fuscia skirt",
      "flavor": "The skirt goes swish around your legs!",
      "description": "white tanktop and fuscia skirt",
      "price": 80,
      "type": "skirt and blouse",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 4,
      "style": "cute",
      "colors": ["white", "pink"],
      "tags": ["easy access skirt"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "white tanktop",
      "breasts": "white tanktop",
      "bottom": "swishy skirt",
      "pussy": "swishy skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "cassidy casual jean jacket": toMap({
      "id": "cassidy casual jean jacket",
      "category": "casual",
      "name": "jean jacket",
      "flavor": "You can't button the jacket due to your huge knockers, but you still think the outfit comes together nicely!",
      "description": "jean jacket, white tanktop, and jean shorts",
      "price": 145,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 5,
      "style": "sexy",
      "colors": ["white", "blue"],
      "tags": ["two layer top"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs", "belly", "asscheeks"],
      "top": "jean jacket",
      "breasts": "white tanktop",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge", "stylin"]
    }),
    "cassidy casual mint tank top": toMap({
      "id": "cassidy casual mint tank top",
      "category": "casual",
      "name": "mint tank top",
      "flavor": "It wouldn't look all that slutty if you didn't have to push your boobs up into it and the inseam of the shorts was longer than 1/2 inch.",
      "description": "cropped mint tank top and super short shorts",
      "price": 95,
      "type": "casual",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["green", "blue"],
      "tags": [],
      "emphasizes": ["cleavage", "asscheeks"],
      "reveals": ["cleavage", "tummy", "asscheeks"],
      "top": "mint tank top",
      "breasts": "mint tank top",
      "bottom": "short shorts",
      "pussy": "short shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "cassidy casual peach tanktop": toMap({
      "id": "cassidy casual peach tanktop",
      "category": "casual",
      "name": "peach tanktop",
      "flavor": "Comfortable, yet revealing.",
      "description": "cropped beach tanktop and jean shorts",
      "price": 105,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 5,
      "style": "sexy",
      "colors": ["orange", "blue"],
      "tags": [],
      "emphasizes": ["cleavage", "asscheeks"],
      "reveals": ["cleavage", "tummy", "asscheeks"],
      "top": "peach tanktop",
      "breasts": "peach tanktop",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "cassidy casual pink picnic": toMap({
      "id": "cassidy casual pink picnic",
      "category": "casual",
      "name": "pink picnic",
      "flavor": "Old-fashioned but not plain! The top is a bit too small to fit a bra under. ",
      "description": "matching checkered top and skirt",
      "price": 150,
      "type": "casual",
      "sluttiness": 2,
      "comfort": 5,
      "durability": 6,
      "style": "cute",
      "colors": ["pink"],
      "tags": ["easy access skirt"],
      "emphasizes": ["cleavage", "legs"],
      "reveals": ["cleavage", "tummy", "legs"],
      "top": "checkered top",
      "breasts": "checkered top",
      "bottom": "checkered skirt",
      "pussy": "checkered skirt",
      "breast support": 4,
      "panties under": "can",
      "bra under": "no",
      "shoes": "flats",
      "locations": ["casual", "lounge", "stylin"]
    }),
    "cassidy casual sorority girl": toMap({
      "id": "cassidy casual sorority girl",
      "category": "casual",
      "name": "sorority girl",
      "flavor": "Do these glasses make you look smarter?",
      "description": "white crop top and black skirt",
      "price": 150,
      "type": "casual",
      "sluttiness": 8,
      "comfort": 5,
      "durability": 6,
      "style": "slutty",
      "colors": ["pink"],
      "tags": ["easy access skirt", "intelligent"],
      "emphasizes": ["underboob"],
      "reveals": ["underboob", "legs", "tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "black skirt",
      "pussy": "black skirt",
      "breast support": 4,
      "panties under": "can",
      "bra under": "no",
      "shoes": "flats",
      "locations": ["casual", "lounge", "stylin"]
    }),
    "cassidy casual white frilly top": toMap({
      "id": "cassidy casual white frilly top",
      "category": "casual",
      "name": "white frilly top",
      "flavor": "Better tie this tight enough!",
      "description": "white knit crop top and jean shorts",
      "price": 150,
      "type": "casual",
      "sluttiness": 7,
      "comfort": 4,
      "durability": 3,
      "style": "sexy",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": ["sideboob"],
      "reveals": ["sideboob", "cleavage", "tummy"],
      "top": "white knit crop top",
      "breasts": "white knit crop top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 4,
      "panties under": "can",
      "bra under": "no",
      "shoes": "flats",
      "locations": ["casual", "lounge", "stylin"]
    }),
    "cassidy casual zip up": toMap({
      "id": "cassidy casual zip up",
      "category": "casual",
      "name": "zip up",
      "flavors": [
        "The hardest working zipper on earth.",
        "The zipper is pretty strained, but it looks too cute to go another size up."
      ],
      "description": "cropped pink hoodie and jeans",
      "price": 80,
      "type": "casual",
      "sluttiness": 8,
      "comfort": 3,
      "durability": 4,
      "style": "sexy",
      "colors": ["pink", "blue"],
      "tags": ["zipper"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy"],
      "top": "cropped pink hoodie",
      "breasts": "cropped pink hoodie",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 4,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    })
  }),
  "fetish": toMap({
    "cassidy fetish dumb bitch": toMap({
      "id": "cassidy fetish dumb bitch",
      "category": "fetish",
      "name": "dumb bitch",
      "flavor": "You look someone's trophy slut in this.",
      "description": "golden bikini with a lot of decoration",
      "price": 350,
      "type": "fancy bikini",
      "sluttiness": 10,
      "comfort": 2,
      "durability": 2,
      "style": "slutty",
      "colors": ["gold"],
      "tags": ["jingle", "collar"],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "boobs", "legs", "butt"],
      "top": "golden bikini top",
      "breasts": "golden bikini top",
      "bottom": "golden bikini bottom",
      "pussy": "golden bikini bottom",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach", "fetish"]
    }),
    "cassidy fetish french maid lingerie": toMap({
      "id": "cassidy fetish french maid lingerie",
      "category": "fetish",
      "name": "french maid lingerie",
      "flavor": "When a normal french maid outfit isn't sexy enough.",
      "description": "lacy lingerie with a matching collar",
      "price": 200,
      "type": "lingerie",
      "sluttiness": 10,
      "comfort": 3,
      "durability": 1,
      "style": "slutty",
      "colors": ["white", "black"],
      "tags": ["collar", "chores"],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "boobs", "legs", "butt"],
      "top": "lacy bra",
      "breasts": "lacy bra",
      "bottom": "lacy panties",
      "pussy": "lacy panties",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish", "lounge"]
    }),
    "cassidy fetish jungle cat": toMap({
      "id": "cassidy fetish jungle cat",
      "category": "fetish",
      "name": "jungle cat",
      "flavor": "You're ready to pounce! (Or be pounced on?) Rawr.",
      "description": "leopard-pattern one piece",
      "price": 250,
      "type": "one piece",
      "sluttiness": 9,
      "comfort": 4,
      "durability": 2,
      "style": "slutty",
      "colors": ["brown", "black"],
      "tags": ["swim", "one piece"],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "boobs", "legs", "butt"],
      "top": "one piece",
      "breasts": "one piece",
      "bottom": "one piece",
      "pussy": "one piece",
      "breast support": 2,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish", "beach"]
    }),
    "cassidy fetish kitty": toMap({
      "id": "cassidy fetish kitty",
      "category": "fetish",
      "name": "kitty",
      "flavor": "Meow.",
      "description": "see-through bodysuit, with cat ears included",
      "price": 175,
      "type": "one piece",
      "sluttiness": 9,
      "comfort": 4,
      "durability": 2,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["one piece", "stockings", "transparent"],
      "emphasizes": ["boobs", "nipples"],
      "reveals": ["pussy", "nipples", "boobs", "belly", "legs", "butt"],
      "top": "see-through bodysuit",
      "breasts": "see-through bodysuit",
      "bottom": "see-through bodysuit",
      "pussy": "see-through bodysuit",
      "breast support": 1,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    }),
    "cassidy fetish stripper": toMap({
      "id": "cassidy fetish stripper",
      "category": "fetish",
      "name": "stripper",
      "flavor": "Why does the collar have a loop for a padlock?",
      "description": "black and gold stripping bikini, with matching gloves",
      "price": 400,
      "type": "fancy bikini",
      "sluttiness": 9,
      "comfort": 1,
      "durability": 4,
      "style": "slutty",
      "colors": ["gold"],
      "tags": ["jingle", "collar", "dance"],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "boobs", "legs", "butt"],
      "top": "black and gold bikini top",
      "breasts": "black and gold bikini top",
      "bottom": "black and gold garter",
      "pussy": "black and gold garter",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    }),
    "cassidy fetish maid": toMap({
      "id": "cassidy fetish maid",
      "category": "fetish",
      "name": "maid",
      "flavor": "Makes you want to do chores!",
      "description": "french maid outfit",
      "price": 300,
      "type": "dress",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 4,
      "style": "slutty",
      "colors": ["white", "black"],
      "tags": ["chores", "stockings", "easy access dress"],
      "emphasizes": ["boobs"],
      "reveals": ["cleavage"],
      "top": "french maid outfit",
      "breasts": "french maid outfit",
      "bottom": "french maid outfit",
      "pussy": "french maid outfit",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["fetish", "lounge"]
    })
  }),
  "gym": toMap({
    "cassidy gym bouncy": toMap({
      "id": "cassidy gym bouncy",
      "category": "gym",
      "name": "bouncy",
      "flavor": "'Alright, lets start with jumping jacks.'",
      "description": "white see-through top and blue string tanga",
      "price": 60,
      "type": "slutty fitness",
      "sluttiness": 10,
      "comfort": 3,
      "durability": 2,
      "style": "slutty",
      "colors": ["white", "blue"],
      "tags": ["transparent top", "workout"],
      "emphasizes": ["underboob"],
      "reveals": ["nipples", "boobs", "tummy", "legs", "butt"],
      "top": "white top",
      "breasts": "white top",
      "bottom": "blue tanga",
      "pussy": "blue tanga",
      "breast support": 1,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "fetish", "lounge"]
    }),
    "cassidy gym pink tanktop": toMap({
      "id": "cassidy gym pink tanktop",
      "category": "gym",
      "name": "pink tanktop",
      "flavor": "Ready to get sweaty?",
      "description": "pink cropped tanktop and grey sport shorts",
      "price": 80,
      "type": "fitness",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 5,
      "style": "relaxed",
      "colors": ["pink", "grey"],
      "tags": ["workout"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "legs"],
      "top": "pink tanktop",
      "breasts": "pink tanktop",
      "bottom": "grey shorts",
      "pussy": "grey shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["gym", "lounge", "casual"]
    }),
    "cassidy gym yoga": toMap({
      "id": "cassidy gym yoga",
      "category": "gym",
      "name": "yoga",
      "flavor": "The material is extremely thin - no wonder it's cheap.",
      "description": "pink and yellow yoga outfit",
      "price": 20,
      "type": "fitness",
      "sluttiness": 3,
      "comfort": 8,
      "durability": 4,
      "style": "relaxed",
      "colors": ["pink", "yellow"],
      "tags": ["good workout", "yoga", "gym scene"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "legs"],
      "top": "pink tanktop",
      "breasts": "pink tanktop",
      "bottom": "yellow yoga pants",
      "pussy": "yellow yoga pants",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge", "casual"]
    })
  }),
  "lingerie": toMap({
    "cassidy lingerie blue push-up bra": toMap({
      "id": "cassidy lingerie blue push-up bra",
      "category": "lingerie",
      "name": "blue push-up bra",
      "flavor": "As if these puppies needed any enhancement.",
      "description": "blue push-up bra and panties",
      "price": 100,
      "type": "lingerie",
      "sluttiness": 6,
      "comfort": 4,
      "durability": 4,
      "style": "sexy",
      "colors": ["blue"],
      "tags": ["push-up"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "blue push-up bra",
      "breasts": "blue push-up bra",
      "bottom": "blue lace panties",
      "pussy": "blue lace panties",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "cassidy lingerie blue satin lingerie": toMap({
      "id": "cassidy lingerie blue satin lingerie",
      "category": "lingerie",
      "name": "blue satin lingerie",
      "flavor": "Really comfy and soft to the touch.",
      "description": "blue satin bra and panties",
      "price": 75,
      "type": "lingerie",
      "sluttiness": 7,
      "comfort": 10,
      "durability": 3,
      "style": "sexy",
      "colors": ["blue"],
      "tags": ["sleep"],
      "emphasizes": [],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "satin bra",
      "breasts": "satin bra",
      "bottom": "satin panties",
      "pussy": "satin panties",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "cassidy lingerie lacy red lingerie": toMap({
      "id": "cassidy lingerie lacy red lingerie",
      "category": "lingerie",
      "name": "lacy red lingerie",
      "flavor": "You look like a Christmas present in this.",
      "description": "red bra and panties with garter",
      "price": 120,
      "type": "lingerie",
      "sluttiness": 8,
      "comfort": 4,
      "durability": 4,
      "style": "slutty",
      "colors": ["red"],
      "tags": [],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "lace bra",
      "breasts": "lace bra",
      "bottom": "lace panties",
      "pussy": "lace panties",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "cassidy lingerie stretchy red lingerie": toMap({
      "id": "cassidy lingerie stretchy red lingerie",
      "category": "lingerie",
      "name": "stretchy red lingerie",
      "flavor": "Shower thought: Is 'red bra'd woman' the distaff counterpart of 'red-blooded man'?",
      "description": "stretchy red bra and panties",
      "price": 90,
      "type": "lingerie",
      "sluttiness": 6,
      "comfort": 9,
      "durability": 3,
      "style": "sexy",
      "colors": ["red"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "stretchy bra",
      "breasts": "stretchy bra",
      "bottom": "stretchy panties",
      "pussy": "stretchy panties",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "cassidy lingerie underwire white lingerie": toMap({
      "id": "cassidy lingerie underwire white lingerie",
      "category": "lingerie",
      "name": "underwire white lingerie",
      "flavor": "Quite supportive, but digs into your boobs a bit.",
      "description": "white bra and panties",
      "price": 75,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 2,
      "durability": 8,
      "style": "sexy",
      "colors": ["white"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "underwire bra",
      "breasts": "underwire bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 10,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "cassidy lingerie violet lingerie": toMap({
      "id": "cassidy lingerie violet lingerie",
      "category": "lingerie",
      "name": "violet lingerie",
      "flavor": "These violet delights have voluptuous ends.",
      "description": "white bra and panties",
      "price": 50,
      "type": "lingerie",
      "sluttiness": 3,
      "comfort": 4,
      "durability": 8,
      "style": "sexy",
      "colors": ["purple"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    })
  }),
  "lounge": toMap({
    "cassidy lounge bathrobe": toMap({
      "id": "cassidy lounge bathrobe",
      "category": "lounge",
      "name": "bathrobe",
      "flavor": "The material is pretty luxurious.",
      "description": "pink silk bathrobe",
      "price": 180,
      "type": "loungewear",
      "sluttiness": 5,
      "comfort": 9,
      "durability": 5,
      "style": "elegant",
      "colors": ["pink"],
      "tags": ["sleep", "one piece"],
      "emphasizes": ["cleavage", "legs"],
      "reveals": ["legs", "cleavage"],
      "top": "silk bathrobe",
      "breasts": "silk bathrobe",
      "bottom": "silk bathrobe",
      "pussy": "silk bathrobe",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge", "casual"]
    }),
    "cassidy lounge bodysuit": toMap({
      "id": "cassidy lounge bodysuit",
      "category": "lounge",
      "name": "bodysuit",
      "flavor": "It's super comfy and sexy.",
      "description": "black bodysuit",
      "price": 60,
      "type": "loungewear",
      "sluttiness": 7,
      "comfort": 9,
      "durability": 5,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "spandex bodysuit",
      "breasts": "spandex bodysuit",
      "bottom": "spandex bodysuit",
      "pussy": "spandex bodysuit",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge", "casual"]
    }),
    "cassidy lounge game night": toMap({
      "id": "cassidy lounge game night",
      "category": "lounge",
      "name": "game night",
      "flavor": "This might get you tackled by a squad of burly men… but in a different way.",
      "description": "slutty football outfit",
      "price": 95,
      "type": "loungewear",
      "sluttiness": 8,
      "comfort": 5,
      "durability": 2,
      "style": "sexy",
      "colors": ["blue"],
      "tags": [],
      "emphasizes": ["underboob"],
      "reveals": ["underboob", "butt", "legs", "tummy"],
      "top": "sports top",
      "breasts": "sports top",
      "bottom": "sport shorts",
      "pussy": "sport shorts",
      "breast support": 1,
      "panties under": "can",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge", "casual", "gym"]
    }),
    "cassidy lounge tank top": toMap({
      "id": "cassidy lounge tank top",
      "category": "lounge",
      "name": "tank top",
      "flavor": "These panties are so soft and this top is almost transparent!",
      "description": "thin white tanktop and blue panties",
      "price": 35,
      "type": "loungewear",
      "sluttiness": 7,
      "comfort": 9,
      "durability": 1,
      "style": "sexy",
      "colors": ["white", "blue"],
      "tags": ["standalone lingerie", "sleep"],
      "emphasizes": ["cleavage", "nipples"],
      "reveals": ["cleavage", "tummy", "butt", "legs", "nipples"],
      "top": "thin tanktop",
      "breasts": "thin tanktop",
      "bottom": "blue panties",
      "pussy": "blue panties",
      "breast support": 3,
      "panties under": "can",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge", "lingerie"]
    }),
    "cassidy lounge velvet pjs": toMap({
      "id": "cassidy lounge velvet pjs",
      "category": "lounge",
      "name": "velvet pjs",
      "flavor": "The velvet is so soft draped against your skin.",
      "description": "soft pjs and pink panties",
      "price": 110,
      "type": "loungewear",
      "sluttiness": 4,
      "comfort": 10,
      "durability": 4,
      "style": "elegant",
      "colors": ["pink"],
      "tags": ["sleep"],
      "emphasizes": ["cleavage", "butt"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "velvet pj top",
      "breasts": "velvet pj top",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 1,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "cassidy lounge yellow top": toMap({
      "id": "cassidy lounge yellow top",
      "category": "lounge",
      "name": "yellow top",
      "flavor": "Bzz bzz you're a bumblebee.",
      "description": "soft yellow tanktop and black panties",
      "price": 50,
      "type": "loungewear",
      "sluttiness": 5,
      "comfort": 7,
      "durability": 2,
      "style": "sexy",
      "colors": ["yellow", "black"],
      "tags": ["sleep"],
      "emphasizes": ["cleavage", "butt"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "soft tank top",
      "breasts": "soft tank top",
      "bottom": "black panties",
      "pussy": "black panties",
      "breast support": 1,
      "panties under": "no",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge", "casual"]
    })
  }),
  "office": toMap({
    "cassidy office little black dress": toMap({
      "id": "cassidy office little black dress",
      "category": "office",
      "name": "little black dress",
      "flavor": "Little black dress, meet big fat tits.",
      "description": "black satin dress",
      "price": 180,
      "type": "sexy office",
      "sluttiness": 8,
      "comfort": 6,
      "durability": 2,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["one piece", "easy access dress", "professional"],
      "emphasizes": ["cleavage", "sideboob"],
      "reveals": ["cleavage", "sideboob"],
      "top": "little black dress",
      "breasts": "little black dress",
      "bottom": "little black dress",
      "pussy": "little black dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office", "stylin"]
    }),
    "cassidy office button down": toMap({
      "id": "cassidy office button down",
      "category": "office",
      "name": "button down",
      "flavor": "Good thing they have a water cooler, because the whole office is going to be thirsty.",
      "description": "button down shirt and black skirt",
      "price": 120,
      "type": "sexy office",
      "sluttiness": 5,
      "comfort": 8,
      "durability": 5,
      "style": "sexy",
      "colors": ["white", "black"],
      "tags": ["professional", "buttons"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "button-down shirt",
      "breasts": "button-down shirt",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "cassidy office grey dress": toMap({
      "id": "cassidy office grey dress",
      "category": "office",
      "name": "grey dress",
      "flavor": "Good for working behind a desk, or under one, or bent over one…",
      "description": "stretchy grey dress",
      "price": 70,
      "type": "sexy office",
      "sluttiness": 6,
      "comfort": 9,
      "durability": 4,
      "style": "sexy",
      "colors": ["grey"],
      "tags": ["professional", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "grey dress",
      "breasts": "grey dress",
      "bottom": "grey dress",
      "pussy": "grey dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office", "stylin", "casual"]
    }),
    "cassidy office leather skirt": toMap({
      "id": "cassidy office leather skirt",
      "category": "office",
      "name": "leather skirt",
      "flavor": "You're pretty sure this doesn't meet the dress code, but who's gonna call you on it?",
      "description": "low-cut grey top and leather skirt",
      "price": 200,
      "type": "sexy office",
      "sluttiness": 7,
      "comfort": 4,
      "durability": 3,
      "style": "sexy",
      "colors": ["grey", "black"],
      "tags": ["very professional", "easy access skirt"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "low-cut top",
      "breasts": "low-cut top",
      "bottom": "leather skirt",
      "pussy": "leather skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "cassidy office plaid skirt": toMap({
      "id": "cassidy office plaid skirt",
      "category": "office",
      "name": "plaid skirt",
      "flavor": "Eye candy? I'll have you know I'm very knowledgeable about stockings- er, stocks…",
      "description": "low-cut grey top and leather skirt",
      "price": 80,
      "type": "casual office",
      "sluttiness": 3,
      "comfort": 5,
      "durability": 5,
      "style": "professional",
      "colors": ["white", "grey"],
      "tags": ["professional", "easy access skirt", "stockings", "buttons"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "button-down top",
      "breasts": "button-down top",
      "bottom": "grey skirt",
      "pussy": "grey skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    })
  }),
  "stylin": toMap({
    "cassidy stylin leopard dress": toMap({
      "id": "cassidy stylin leopard dress",
      "category": "stylin",
      "name": "leopard dress",
      "flavor": "A cute dress with a wild print!",
      "description": "dress with leopard print",
      "price": 135,
      "type": "dress",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 6,
      "style": "cute",
      "colors": ["brown"],
      "tags": ["one piece"],
      "emphasizes": [],
      "reveals": ["cleavage", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "casual"]
    }),
    "cassidy stylin tight dress": toMap({
      "id": "cassidy stylin tight dress",
      "category": "stylin",
      "name": "tight dress",
      "flavor": "Extremely form-fitting, this dress was made for you!",
      "description": "tight black dress",
      "price": 330,
      "type": "dress",
      "sluttiness": 6,
      "comfort": 3,
      "durability": 5,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["one piece", "easy access dress"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 3,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "casual"]
    }),
    "cassidy stylin drape dress": toMap({
      "id": "cassidy stylin drape dress",
      "category": "stylin",
      "name": "drape dress",
      "flavors": [
        "Clearly highlights the important bits.",
        "Complete with boob window for easy access."
      ],
      "description": "black dress",
      "price": 350,
      "type": "dress",
      "sluttiness": 9,
      "comfort": 6,
      "durability": 3,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["one piece", "bounce free"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "black dress",
      "breasts": "black dress",
      "bottom": "black dress",
      "pussy": "black dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "cassidy stylin qipao": toMap({
      "id": "cassidy stylin qipao",
      "category": "stylin",
      "name": "qipao",
      "flavors": [
        "This Chinese style dress really hugs your curves nicely.",
        "A qipao doesn't traditionally show cleavage but you're anything but traditional."
      ],
      "description": "red and white qipao",
      "price": 400,
      "type": "dress",
      "sluttiness": 5,
      "comfort": 4,
      "durability": 7,
      "style": "elegant",
      "colors": ["red", "white"],
      "tags": ["one piece", "easy access dress"],
      "emphasizes": ["legs"],
      "reveals": ["cleavage", "legs"],
      "top": "qipao",
      "breasts": "qipao",
      "bottom": "qipao",
      "pussy": "qipao",
      "breast support": 2,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "fetish"]
    }),
    "cassidy stylin black dress": toMap({
      "id": "cassidy stylin black dress",
      "category": "stylin",
      "name": "black dress",
      "flavor": "While it looks mostly tasteful, the discerning eye can tell it's semi-transparent.",
      "description": "black dress",
      "price": 650,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 5,
      "durability": 8,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["gift", "semi-transparent", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "black dress",
      "breasts": "black dress",
      "bottom": "black dress",
      "pussy": "black dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "cassidy stylin blue dress": toMap({
      "id": "cassidy stylin blue dress",
      "category": "stylin",
      "name": "blue dress",
      "flavor": "Blue is really your color!",
      "description": "blue dress",
      "price": 350,
      "type": "dress",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["blue"],
      "tags": ["one piece", "easy access dress"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "blue dress",
      "breasts": "blue dress",
      "bottom": "blue dress",
      "pussy": "blue dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "cassidy stylin camo shorts": toMap({
      "id": "cassidy stylin camo shorts",
      "category": "stylin",
      "name": "camo shorts",
      "flavors": [
        "What camo pants? Ohh now I see them.",
        "That's a big rifle. Is it for fighting or for fun?",
        "The shirt is transparent and it has a camo skirt... tactical AF.",
        "You feel tacti-COOL in this."
      ],
      "description": "camo mini-skirt with semi-transparent bralette",
      "price": 275,
      "type": "stylish outfit",
      "sluttiness": 10,
      "comfort": 5,
      "durability": 4,
      "style": "slutty",
      "colors": ["pink", "green"],
      "tags": ["one piece", "transparent"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs", "tummy", "nipples"],
      "top": "pink bralette",
      "breasts": "pink bralette",
      "bottom": "camo shorts",
      "pussy": "camo shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["stylin", "casual", "lounge"]
    })
  })
}))