window.GE.outfit_database = window.GE.outfit_database || new Map();

window.GE.outfit_database.set("ella", toMap({
  "purchasable": toMap({
    "beach": 4,
    "casual": 3,
    "fetish": 2,
    "lingerie": 3,
    "gym": 2,
    "lounge": 3,
    "office": 3,
    "stylin": 3
  }),
  "beach": toMap({
    "ella beach barely contained": toMap({
      "id": "ella beach barely contained",
      "category": "beach",
      "name": "barely contained",
      "flavors": [
        "Promises the mother of all wedgies... but you'll always be the center of attention.",
        "Form over function.",
        "The perfect swimsuit, when you don't actually want to swim.",
        "This'll surely make some heads turn.",
        "(͠≖ ͜ʖ͠≖)👌"
      ],
      "description": "black mobius strip of a swimsuit",
      "price": 290,
      "type": "one piece",
      "sluttiness": 9,
      "comfort": 1,
      "durability": 1,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["one piece", "boobs fall out"],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "boobs", "legs", "butt"],
      "top": "black one piece",
      "breasts": "black one piece",
      "bottom": "black one piece",
      "pussy": "black one piece",
      "breast support": 2,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach", "fetish"]
    }),
    "ella beach black one piece": toMap({
      "id": "ella beach black one piece",
      "category": "beach",
      "name": "black one piece",
      "flavor": "A safe option.",
      "description": "modest black swimsuit",
      "price": 80,
      "type": "one piece",
      "sluttiness": 2,
      "comfort": 8,
      "durability": 7,
      "style": "modest",
      "colors": ["black"],
      "tags": ["one piece", "swim"],
      "emphasizes": ["butt"],
      "reveals": ["butt"],
      "top": "black one piece",
      "breasts": "black one piece",
      "bottom": "black one piece",
      "pussy": "black one piece",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "ella beach blue and yellow": toMap({
      "id": "ella beach blue and yellow",
      "category": "beach",
      "name": "blue and yellow",
      "flavor": "Colorful fare for a colorful gal.",
      "description": "yellow string bikini top and blue bikini bottom",
      "price": 95,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 4,
      "durability": 4,
      "style": "sexy",
      "colors": ["yellow", "blue"],
      "tags": ["swim", "strings"],
      "emphasizes": ["boobs", "butt"],
      "reveals": ["butt", "boobs", "tummy", "legs"],
      "top": "triangle bikini top",
      "breasts": "triangle bikini top",
      "bottom": "blue bikini bottom",
      "pussy": "blue bikini bottom",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "ella beach halter top bikini": toMap({
      "id": "ella beach halter top bikini",
      "category": "beach",
      "name": "halter top bikini",
      "flavor": "When looking sexy in a bikini is more important than using it for swimming.",
      "description": "black halter top bikini and chain-link bottom",
      "price": 130,
      "type": "bikini",
      "sluttiness": 7,
      "comfort": 3,
      "durability": 3,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["jingle", "strings"],
      "emphasizes": ["cleavage"],
      "reveals": ["butt", "boobs", "tummy", "legs"],
      "top": "halter bikini top",
      "breasts": "halter bikini top",
      "bottom": "chain bikini bottom",
      "pussy": "chain bikini bottom",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "ella beach see through bikini": toMap({
      "id": "ella beach see through bikini",
      "category": "beach",
      "name": "see through bikini",
      "flavors": [
        "This material is so thin... if your top gets wet, people will totally see your knockers.",
        "No one in their right mind would wear this swimming."
      ],
      "description": "white t-shirt bikini top and pink bottom",
      "price": 25,
      "type": "bikini",
      "sluttiness": 7,
      "comfort": 8,
      "durability": 1,
      "style": "sexy",
      "colors": ["white", "pink"],
      "tags": ["semi-transparent", "transparent wet", "swim"],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "cleavage", "butt", "legs"],
      "top": "t-shirt bikini top",
      "breasts": "t-shirt bikini top",
      "bottom": "pink bikini bottom",
      "pussy": "pink bikini bottom",
      "breast support": 2,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "ella beach teamskeet t-shirt": toMap({
      "id": "ella beach teamskeet t-shirt",
      "category": "beach",
      "name": "teamskeet t-shirt",
      "flavor": "Sorry, what's 'TEAMSKEET'? Some kind of band?",
      "description": "white 'TEAMSKEET' t-shirt and white bikini bottom",
      "price": 65,
      "type": "casual beachwear",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 5,
      "style": "sexy",
      "colors": ["white"],
      "tags": ["transparent wet"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs", "butt"],
      "top": "t-shirt",
      "breasts": "t-shirt",
      "bottom": "white bikini bottom",
      "pussy": "white bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach", "lounge"]
    }),
    "ella beach wet tshirt day": toMap({
      "id": "ella beach wet tshirt day",
      "category": "beach",
      "name": "wet tshirt day",
      "flavor": "A look that says, 'My shirt's clingy, but I'm not.'",
      "description": "tropical bikini and t-shirt",
      "price": 75,
      "type": "bikini",
      "sluttiness": 3,
      "comfort": 8,
      "durability": 5,
      "style": "casual",
      "colors": ["white", "blue", "red"],
      "tags": ["swim", "two top layers"],
      "emphasizes": ["boobs"],
      "reveals": ["butt", "legs"],
      "top": "white t-shirt",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 2,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach", "lounge"]
    }),
    "ella beach white bikini": toMap({
      "id": "ella beach white bikini",
      "category": "beach",
      "name": "white bikini",
      "flavor": "Simple can be sexy.",
      "description": "white string bikini",
      "price": 120,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["white"],
      "tags": ["swim"],
      "emphasizes": ["boobs"],
      "reveals": ["butt", "legs", "boobs", "tummy"],
      "top": "string bikini top",
      "breasts": "string bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "ella beach yellow bikini": toMap({
      "id": "ella beach yellow bikini",
      "category": "beach",
      "name": "yellow bikini",
      "flavor": "Be the second sun at the beach.",
      "description": "yellow triangle top bikini",
      "price": 110,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["yellow"],
      "tags": ["swim", "strings"],
      "emphasizes": ["boobs"],
      "reveals": ["butt", "legs", "boobs", "tummy"],
      "top": "string bikini top",
      "breasts": "string bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    })
  }),
  "casual": toMap({
    "ella casual booty shorts": toMap({
      "id": "ella casual booty shorts",
      "category": "casual",
      "name": "booty shorts",
      "flavor": "Step aside, Daisy Duke.",
      "description": "orange tanktop and booty shorts",
      "price": 65,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 6,
      "style": "sexy",
      "colors": ["orange", "blue"],
      "tags": ["visible underwear"],
      "emphasizes": ["asscheeks"],
      "reveals": ["butt", "legs"],
      "top": "tanktop",
      "breasts": "tanktop",
      "bottom": "booty shorts",
      "pussy": "booty shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "ella casual crop top sweater": toMap({
      "id": "ella casual crop top sweater",
      "category": "casual",
      "name": "crop top sweater",
      "flavor": "This sweater won't really keep you warm on a cold day…",
      "description": "red cropped sweater and jean shorts",
      "price": 90,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 5,
      "style": "sexy",
      "colors": ["red", "blue"],
      "tags": [],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "legs", "butt"],
      "top": "cropped sweater",
      "breasts": "cropped sweater",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "ella casual earthy velour": toMap({
      "id": "ella casual earthy velour",
      "category": "casual",
      "name": "earthy velour",
      "flavors": [
        "The velvet fabric feels really nice.",
        "This color goes nicely with your skin tone.",
        "Comes with a fun little choker.",
        "Shower thought: If you were pregnant, this top would frame your belly like a theater curtain.",
        "Cozy. Soft. Makes your tits look good too."
      ],
      "description": "brown velvet top and jeans",
      "price": 135,
      "type": "casual",
      "sluttiness": 3,
      "comfort": 9,
      "durability": 8,
      "style": "casual",
      "colors": ["brown", "blue"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy"],
      "top": "velvet top",
      "breasts": "velvet top",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "ella casual eyes up here": toMap({
      "id": "ella casual eyes up here",
      "category": "casual",
      "name": "eyes up here",
      "flavors": [
        "You won't be taken very seriously in this.",
        "Your boobs aren't even close to fitting into this."
      ],
      "description": "low-cut pink top and jean shorts",
      "price": 110,
      "type": "casual",
      "sluttiness": 10,
      "comfort": 6,
      "durability": 4,
      "style": "slutty",
      "colors": ["pink", "blue"],
      "tags": ["boobs fall out", "not serious"],
      "emphasizes": ["cleavage", "tons of cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "low-cut top",
      "breasts": "low-cut top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "ella casual fun colors": toMap({
      "id": "ella casual fun colors",
      "category": "casual",
      "name": "fun colors",
      "flavor": "The thigh-highs complete this teenybopping outfit.",
      "description": "low-cut tanktop, yellow shorts and rainbow thigh-highs",
      "price": 150,
      "type": "casual",
      "sluttiness": 9,
      "comfort": 8,
      "durability": 5,
      "style": "slutty",
      "colors": ["red", "yellow"],
      "tags": ["not serious"],
      "emphasizes": ["cleavage", "tons of cleavage"],
      "reveals": ["cleavage"],
      "top": "low-cut top",
      "breasts": "low-cut top",
      "bottom": "yellow shorts",
      "pussy": "yellow shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "ella casual jean shorts": toMap({
      "id": "ella casual jean shorts",
      "category": "casual",
      "name": "jean shorts",
      "flavor": "A comfortable white T-shirt and shorts combo.",
      "description": "t-shirt and shorts",
      "price": 55,
      "type": "casual",
      "sluttiness": 3,
      "comfort": 9,
      "durability": 7,
      "style": "relaxed",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "t-shirt",
      "breasts": "t-shirt",
      "bottom": "blue shorts",
      "pussy": "blue shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "ella casual low cut t-shirt": toMap({
      "id": "ella casual low cut t-shirt",
      "category": "casual",
      "name": "low cut t-shirt",
      "flavor": "With a top as thin as this, you might want to wear a bra.",
      "description": "t-shirt and shorts",
      "price": 70,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 10,
      "durability": 5,
      "style": "relaxed",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": ["cleavage", "lots of cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "low-cut t-shirt",
      "breasts": "low-cut t-shirt",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "ella casual mauve top": toMap({
      "id": "ella casual mauve top",
      "category": "casual",
      "name": "mauve top",
      "flavor": "Cheap. Trashy. Irresistible.",
      "description": "casual halter top and ripped denim shorts combination",
      "price": 35,
      "type": "casual",
      "sluttiness": 5,
      "comfort": 10,
      "durability": 3,
      "style": "relaxed",
      "colors": ["pink", "blue"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "mauve top",
      "breasts": "mauve top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "ella casual nava-ho": toMap({
      "id": "ella casual nava-ho",
      "category": "casual",
      "name": "nava-ho",
      "flavor": "A casual combo of light blue denim cut-offs and a thin olive tank top.",
      "description": "thin olive tank top and denim cutoffs",
      "price": 55,
      "type": "casual",
      "sluttiness": 7,
      "comfort": 8,
      "durability": 4,
      "style": "sexy",
      "colors": ["brown", "blue"],
      "tags": ["choker"],
      "emphasizes": ["cleavage", "sideboob"],
      "reveals": ["cleavage", "legs", "sideboob"],
      "top": "tanktop",
      "breasts": "tanktop",
      "bottom": "cutoffs",
      "pussy": "cutoffs",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "ella casual picnic": toMap({
      "id": "ella casual picnic",
      "category": "casual",
      "name": "picnic",
      "flavor": "Maybe *you* are the picnic.",
      "description": "fun bow-tied top with a polka-dot skirt",
      "price": 55,
      "type": "skirt and blouse",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 3,
      "style": "cute",
      "colors": ["pink", "white"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "tube top",
      "breasts": "tube top",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "ella casual tie-dye crop top": toMap({
      "id": "ella casual tie-dye crop top",
      "category": "casual",
      "name": "tie-dye crop top",
      "flavor": "Cute yet sexy.",
      "description": "purple crop top and blue shorts",
      "price": 70,
      "type": "tshirt and shorts",
      "sluttiness": 5,
      "comfort": 8,
      "durability": 2,
      "style": "sexy",
      "colors": ["purple", "blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy", "legs"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "ella casual white maxi dress": toMap({
      "id": "ella casual white maxi dress",
      "category": "casual",
      "name": "white maxi dress",
      "flavor": "You should consider wearing a bra under this... unless you want a certain kind of attention.",
      "description": "white maxi dress",
      "price": 110,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 10,
      "durability": 4,
      "style": "sexy",
      "colors": ["white"],
      "tags": ["semi-transparent", "one piece"],
      "emphasizes": ["nipples"],
      "reveals": [],
      "top": "maxi dress",
      "breasts": "maxi dress",
      "bottom": "maxi dress",
      "pussy": "maxi dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    })
  }),
  "fetish": toMap({
    "ella fetish chained up": toMap({
      "id": "ella fetish chained up",
      "category": "fetish",
      "name": "chained up",
      "flavor": "Jingles a lot.",
      "description": "chain-link one-piece",
      "price": 250,
      "type": "fetishwear",
      "sluttiness": 10,
      "comfort": 1,
      "durability": 10,
      "style": "slutty",
      "colors": ["grey"],
      "tags": ["jingles", "one piece"],
      "emphasizes": ["boobs", "nipples", "pussy", "butt"],
      "reveals": ["boobs", "nipples", "pussy", "butt", "legs"],
      "top": "chain outfit",
      "breasts": "chain outfit",
      "bottom": "chain outfit",
      "pussy": "chain outfit",
      "breast support": 2,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish", "beach"]
    }),
    "ella fetish chained": toMap({
      "id": "ella fetish chained",
      "category": "fetish",
      "name": "chained",
      "flavor": "You look like a mint chocolate chip.",
      "description": "short green dress and collar",
      "price": 120,
      "type": "fetishwear",
      "sluttiness": 7,
      "comfort": 4,
      "durability": 6,
      "style": "sexy",
      "colors": ["green"],
      "tags": ["jingles", "one piece", "easy access dress", "collar"],
      "emphasizes": ["sideboob", "cleavage"],
      "reveals": ["sideboob", "cleavage", "legs"],
      "top": "minidress",
      "breasts": "minidress",
      "bottom": "minidress",
      "pussy": "minidress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["fetish", "stylin"]
    }),
    "ella fetish cheetah": toMap({
      "id": "ella fetish cheetah",
      "category": "fetish",
      "name": "cheetah",
      "flavors": [
        "You may get pregnant almost instantly.",
        "RAWR!",
        "The cheetah is a ferocious huntress - but what meat is she after?",
        "It barely qualifies as covering.",
        "You feel more naked than being actually naked."
      ],
      "description": "cheetah-patterend nipple covers and panties",
      "price": 150,
      "type": "fetishwear",
      "sluttiness": 10,
      "comfort": 2,
      "durability": 1,
      "style": "slutty",
      "colors": ["yellow"],
      "tags": ["jingles", "collar"],
      "emphasizes": ["boobs", "entire boobs"],
      "reveals": ["entire boobs", "belly", "legs", "butt"],
      "top": "nipple clamps",
      "breasts": "nipple clamps",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    }),
    "ella fetish flamingo": toMap({
      "id": "ella fetish flamingo",
      "category": "fetish",
      "name": "flamingo",
      "flavor": "Doesn't really qualify as an outfit.",
      "description": "micro pink bikini that often malfunctions",
      "price": 120,
      "type": "bikini",
      "sluttiness": 10,
      "comfort": 3,
      "durability": 1,
      "style": "slutty",
      "colors": ["white", "pink"],
      "tags": ["boobs fall out"],
      "emphasizes": ["boobs", "entire boobs"],
      "reveals": ["entire boobs", "belly", "legs", "butt"],
      "top": "mesh shirt",
      "breasts": "pink bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish", "beach"]
    }),
    "ella fetish maid": toMap({
      "id": "ella fetish maid",
      "category": "fetish",
      "name": "maid",
      "flavor": "The ideal outfit to wearing when you're spit-polishing… floors.",
      "description": "french maid dress",
      "price": 240,
      "type": "dress",
      "sluttiness": 8,
      "comfort": 5,
      "durability": 3,
      "style": "slutty",
      "colors": ["black", "white"],
      "tags": ["chores", "one piece", "easy access dress", "stockings"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["fetish", "lounge"]
    }),
    "ella fetish red garter": toMap({
      "id": "ella fetish red garter",
      "category": "fetish",
      "name": "red garter",
      "flavor": "Someone is going to fall in love with you when you wear this.",
      "description": "fancy red set of lingerie",
      "price": 350,
      "type": "lingerie",
      "sluttiness": 6,
      "comfort": 4,
      "durability": 5,
      "style": "sexy",
      "colors": ["red"],
      "tags": ["standalone lingerie", "garter"],
      "emphasizes": ["cleavage", "asscheeks"],
      "reveals": ["cleavage", "tummy", "legs", "butt"],
      "top": "red bra",
      "breasts": "red bra",
      "bottom": "red garter",
      "pussy": "red garter",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish", "lingerie"]
    })
  }),
  "gym": toMap({
    "ella gym blue spinner": toMap({
      "id": "ella gym blue spinner",
      "category": "gym",
      "name": "blue spinner",
      "flavor": "You're ready to work up a sweat in this!",
      "description": "blue sports bra and bike shorts",
      "price": 95,
      "type": "fitness",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 6,
      "style": "sexy",
      "colors": ["blue"],
      "tags": ["workout"],
      "emphasizes": ["butt"],
      "reveals": ["tummy", "legs"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "bike shorts",
      "pussy": "bike shorts",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge", "casual"]
    }),
    "ella gym jump around": toMap({
      "id": "ella gym jump around",
      "category": "gym",
      "name": "jump around",
      "flavor": "A comfortable workout set.",
      "description": "black sports bra and matching leggings",
      "price": 140,
      "type": "fitness",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 7,
      "style": "casual",
      "colors": ["black"],
      "tags": ["workout"],
      "emphasizes": [],
      "reveals": ["tummy", "legs"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "leggings",
      "pussy": "leggings",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge", "casual"]
    }),
    "ella gym pink sports bra": toMap({
      "id": "ella gym pink sports bra",
      "category": "gym",
      "name": "pink sports bra",
      "flavor": "You're ready to work up a sweat in this, and you don't care how!",
      "description": "pink sports bra and grey sport shorts",
      "price": 80,
      "type": "fitness",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["pink", "grey"],
      "tags": ["workout", "stockings"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "legs"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "sport shorts",
      "pussy": "sport shorts",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    }),
    "ella gym simple": toMap({
      "id": "ella gym simple",
      "category": "gym",
      "name": "simple",
      "flavors": [
        "Look at the clock! It's time to burn some calories.",
        "A safe option, but not a lot of boob support.",
        "For when you're slumming it a bit."
      ],
      "description": "white t-shirt and grey sport shorts",
      "price": 25,
      "type": "fitness",
      "sluttiness": 3,
      "comfort": 6,
      "durability": 3,
      "style": "relaxed",
      "colors": ["white", "grey"],
      "tags": ["workout", "sleep"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "t-shirt",
      "breasts": "t-shirt",
      "bottom": "sport shorts",
      "pussy": "sport shorts",
      "breast support": 2,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    })
  }),
  "lingerie": toMap({
    "ella lingerie black and white": toMap({
      "id": "ella lingerie black and white",
      "category": "lingerie",
      "name": "black and white",
      "flavor": "There's beautiful lace-stitching on both the bra and panties.",
      "description": "white push-up bra and black panties",
      "price": 100,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 5,
      "durability": 7,
      "style": "elegant",
      "colors": ["white", "black"],
      "tags": ["push-up"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "butt", "legs"],
      "top": "push-up bra",
      "breasts": "push-up bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "ella lingerie black garter": toMap({
      "id": "ella lingerie black garter",
      "category": "lingerie",
      "name": "black garter",
      "flavor": "Stockings and push-up bra in a comfortable and alluring package.",
      "description": "black bra and silken garter",
      "price": 130,
      "type": "lingerie",
      "sluttiness": 3,
      "comfort": 6,
      "durability": 6,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["push-up", "stockings"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "push-up bra",
      "breasts": "push-up bra",
      "bottom": "garter",
      "pussy": "garter",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "ella lingerie comfy lilac bra": toMap({
      "id": "ella lingerie comfy lilac bra",
      "category": "lingerie",
      "name": "comfy lilac bra",
      "flavor": "Comfortable. Girly. And quite sexy!",
      "description": "lilac bra and panties",
      "price": 50,
      "type": "lingerie",
      "sluttiness": 5,
      "comfort": 8,
      "durability": 4,
      "style": "cute",
      "colors": ["pink", "purple"],
      "tags": ["strings"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "ella lingerie floral multiway bra": toMap({
      "id": "ella lingerie floral multiway bra",
      "category": "lingerie",
      "name": "floral multiway bra",
      "flavor": "Sexy lingerie that is comfortable and durable enough for everyday wear and 'tear'.",
      "description": "floral multiway bra and panties",
      "price": 95,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 9,
      "durability": 9,
      "style": "elegant",
      "colors": ["brown", "black"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "ella lingerie purple multiway bra": toMap({
      "id": "ella lingerie purple multiway bra",
      "category": "lingerie",
      "name": "purple multiway bra",
      "flavor": "I think this comes in black too.",
      "description": "purple multiway bra and panties",
      "price": 95,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 9,
      "durability": 9,
      "style": "elegant",
      "colors": ["purple"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["boobs", "tummy", "butt"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "ella lingerie red halter neck bra": toMap({
      "id": "ella lingerie red halter neck bra",
      "category": "lingerie",
      "name": "red halter neck bra",
      "flavor": "The definition of a comfortable set of undies.",
      "description": "halter neck bra and panties",
      "price": 75,
      "type": "lingerie",
      "sluttiness": 3,
      "comfort": 10,
      "durability": 7,
      "style": "casual",
      "colors": ["red"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "ella lingerie red lingerie": toMap({
      "id": "ella lingerie red lingerie",
      "category": "lingerie",
      "name": "red lingerie",
      "flavor": "You feel so sexy in this.",
      "description": "red bra and panties, with stockings",
      "price": 110,
      "type": "lingerie",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 5,
      "style": "casual",
      "colors": ["red"],
      "tags": ["stockings"],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "butt", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "ella lingerie white lace": toMap({
      "id": "ella lingerie white lace",
      "category": "lingerie",
      "name": "white lace",
      "flavor": "The lace just barely obscures your nipples.",
      "description": "white underwire bra and panties",
      "price": 80,
      "type": "lingerie",
      "sluttiness": 5,
      "comfort": 4,
      "durability": 6,
      "style": "casual",
      "colors": ["white"],
      "tags": ["stockings", "underwire"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "butt", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 10,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    })
  }),
  "lounge": toMap({
    "ella lounge floral dressing gown": toMap({
      "id": "ella lounge floral dressing gown",
      "category": "lounge",
      "name": "floral dressing gown",
      "flavor": "Sheer in all the right places, while not being too revealing.",
      "description": "flowery dressing gown",
      "price": 65,
      "type": "loungewear",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 3,
      "style": "cute",
      "colors": ["purple"],
      "tags": ["sleep", "one piece", "robe", "semi-transparent"],
      "emphasizes": [],
      "reveals": [],
      "top": "dressing gown",
      "breasts": "dressing gown",
      "bottom": "dressing gown",
      "pussy": "dressing gown",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "ella lounge kimono": toMap({
      "id": "ella lounge kimono",
      "category": "lounge",
      "name": "kimono",
      "flavor": "Made from the finest silk.",
      "description": "silk kimono",
      "price": 210,
      "type": "loungewear",
      "sluttiness": 7,
      "comfort": 9,
      "durability": 4,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["sleep", "one piece", "robe"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "silk kimono",
      "breasts": "silk kimono",
      "bottom": "silk kimono",
      "pussy": "silk kimono",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "ella lounge loose white t-shirt": toMap({
      "id": "ella lounge loose white t-shirt",
      "category": "lounge",
      "name": "loose white t-shirt",
      "flavor": "It's not your size, but it's comfy.",
      "description": "big white t-shirt and panties",
      "price": 30,
      "type": "loungewear",
      "sluttiness": 6,
      "comfort": 9,
      "durability": 5,
      "style": "relaxed",
      "colors": ["white"],
      "tags": ["sleep"],
      "emphasizes": ["boobs"],
      "reveals": ["belly", "butt", "legs"],
      "top": "big t-shirt",
      "breasts": "big t-shirt",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "ella lounge tight white t-shirt": toMap({
      "id": "ella lounge tight white t-shirt",
      "category": "lounge",
      "name": "tight white t-shirt",
      "flavor": "It's a bit small, but it's comfy.",
      "description": "tight white t-shirt and panties",
      "price": 30,
      "type": "loungewear",
      "sluttiness": 7,
      "comfort": 8,
      "durability": 5,
      "style": "sexy",
      "colors": ["white"],
      "tags": ["sleep"],
      "emphasizes": ["boobs"],
      "reveals": ["belly", "butt", "legs"],
      "top": "t-shirt",
      "breasts": "t-shirt",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "ella lounge nightgown": toMap({
      "id": "ella lounge nightgown",
      "category": "lounge",
      "name": "nightgown",
      "flavor": "This gown does absolutely nothing to hide your nipples.",
      "description": "white nightgown without much coverage",
      "price": 55,
      "type": "loungewear",
      "sluttiness": 8,
      "comfort": 4,
      "durability": 4,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["sleep", "one piece"],
      "emphasizes": ["nipples"],
      "reveals": ["nipple", "legs", "cleavage"],
      "top": "nightgown",
      "breasts": "nightgown",
      "bottom": "nightgown",
      "pussy": "nightgown",
      "breast support": 1,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "ella lounge sweater weather": toMap({
      "id": "ella lounge sweater weather",
      "category": "lounge",
      "name": "sweater weather",
      "flavor": "Check out your sweater puppies in THIS!",
      "description": "soft cable-knit sweater, panties and stockings",
      "price": 60,
      "type": "loungewear",
      "sluttiness": 8,
      "comfort": 10,
      "durability": 4,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["breasts come out"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "sweater",
      "breasts": "sweater",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 1,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    })
  }),
  "office": toMap({
    "ella office black dress": toMap({
      "id": "ella office black dress",
      "category": "office",
      "name": "black dress",
      "flavor": "Cleavage aplenty, short dress, and fishnets. The guys at the office will be all over you.",
      "description": "black dress",
      "price": 210,
      "type": "skirt and blouse",
      "sluttiness": 8,
      "comfort": 6,
      "durability": 4,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["one piece", "easy access dress", "professional", "strings"],
      "emphasizes": ["cleavage", "lots of cleavage"],
      "reveals": ["cleavage"],
      "top": "black dress",
      "breasts": "black dress",
      "bottom": "black dress",
      "pussy": "black dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office", "stylin"]
    }),
    "ella office forest green blouse": toMap({
      "id": "ella office forest green blouse",
      "category": "office",
      "name": "forest green blouse",
      "flavor": "An outfit for the professional, not the office bicycle.",
      "description": "green blouse and black skirt combo",
      "price": 115,
      "type": "office",
      "sluttiness": 2,
      "comfort": 6,
      "durability": 8,
      "style": "modest",
      "colors": ["green", "black"],
      "tags": ["professional"],
      "emphasizes": [],
      "reveals": [],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "black skirt",
      "pussy": "black skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["office", "casual"]
    }),
    "ella office navy skirt": toMap({
      "id": "ella office navy skirt",
      "category": "office",
      "name": "navy skirt",
      "flavor": "This skirt is insanely cute.",
      "description": "green blouse and black skirt combo",
      "price": 90,
      "type": "office",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 8,
      "style": "cute",
      "colors": ["white", "blue"],
      "tags": ["professional", "easy access skirt"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "ella office polka dots": toMap({
      "id": "ella office polka dots",
      "category": "office",
      "name": "polka dots",
      "flavor": "The top is basically transparent! You better wear a bra.",
      "description": "see-through black blouse and polka-dot skirt",
      "price": 120,
      "type": "office",
      "sluttiness": 9,
      "comfort": 5,
      "durability": 6,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["professional", "easy access skirt", "transparent"],
      "emphasizes": ["nipples"],
      "reveals": ["nipples", "boobs", "tummy"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "ella office royal blue skirt": toMap({
      "id": "ella office royal blue skirt",
      "category": "office",
      "name": "royal blue skirt",
      "flavor": "The buttons are for decoration only and serve no actual purpose.",
      "description": "white blouse and blue skirt",
      "price": 70,
      "type": "skirt and blouse",
      "sluttiness": 7,
      "comfort": 6,
      "durability": 5,
      "style": "sexy",
      "colors": ["white", "blue"],
      "tags": ["professional", "easy access skirt"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "ella office skirt and blouse": toMap({
      "id": "ella office skirt and blouse",
      "category": "office",
      "name": "skirt and blouse",
      "flavor": "You try buttoning the top button but it keeps snapping…",
      "description": "white blouse and black skirt",
      "price": 180,
      "type": "skirt and blouse",
      "sluttiness": 7,
      "comfort": 6,
      "durability": 5,
      "style": "sexy",
      "colors": ["white", "black"],
      "tags": ["very professional", "easy access skirt"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "ella office tan tank top": toMap({
      "id": "ella office tan tank top",
      "category": "office",
      "name": "tan tank top",
      "flavor": "Your boobs are definitely on display in this outfit, and your short skirt looks pretty inviting.",
      "description": "tan tank top and short black skirt",
      "price": 140,
      "type": "skirt and blouse",
      "sluttiness": 8,
      "comfort": 4,
      "durability": 3,
      "style": "slutty",
      "colors": ["brown", "black"],
      "tags": ["very professional", "easy access skirt"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    })
  }),
  "stylin": toMap({
    "ella stylin blue dress": toMap({
      "id": "ella stylin blue dress",
      "category": "stylin",
      "name": "blue dress",
      "flavor": "Sexy but proper.",
      "description": "blue dress",
      "price": 215,
      "type": "dress",
      "sluttiness": 2,
      "comfort": 6,
      "durability": 6,
      "style": "modest",
      "colors": ["blue"],
      "tags": ["one piece"],
      "emphasizes": ["butt"],
      "reveals": ["cleavage"],
      "top": "blue dress",
      "breasts": "blue dress",
      "bottom": "blue dress",
      "pussy": "blue dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["stylin", "casual", "lounge"]
    }),
    "ella stylin bright blue dress": toMap({
      "id": "ella stylin bright blue dress",
      "category": "stylin",
      "name": "bright blue dress",
      "flavor": "I'm blue - Da Boo Dee Da Boo Dai…",
      "description": "bright blue dress",
      "price": 240,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 8,
      "style": "elegant",
      "colors": ["blue"],
      "tags": ["one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "blue dress",
      "breasts": "blue dress",
      "bottom": "blue dress",
      "pussy": "blue dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["stylin", "casual", "office"]
    }),
    "ella stylin dress and fishnets": toMap({
      "id": "ella stylin dress and fishnets",
      "category": "stylin",
      "name": "dress and fishnets",
      "flavor": "The dress is too tight for a bra... feature or bug? ",
      "description": "black dress and fishnet stockings",
      "price": 150,
      "type": "dress",
      "sluttiness": 8,
      "comfort": 5,
      "durability": 3,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["one piece", "easy access dress", "stockings"],
      "emphasizes": ["boobs"],
      "reveals": [],
      "top": "black dress",
      "breasts": "black dress",
      "bottom": "black dress",
      "pussy": "black dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["stylin", "casual", "office"]
    }),
    "ella stylin little black dress": toMap({
      "id": "ella stylin little black dress",
      "category": "stylin",
      "name": "little black dress",
      "flavor": "The top part wraps around your plentiful bosom quite snugly.",
      "description": "little black dress",
      "price": 390,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 3,
      "durability": 4,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["one piece", "easy access dress", "fancy"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "black dress",
      "breasts": "black dress",
      "bottom": "black dress",
      "pussy": "black dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["stylin", "casual", "office"]
    }),
    "ella stylin red dress": toMap({
      "id": "ella stylin red dress",
      "category": "stylin",
      "name": "red dress",
      "flavor": "Sophisticated but sexy! You can conquer the world in this dress.",
      "description": "red dress",
      "price": 250,
      "type": "dress",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["red"],
      "tags": ["one piece", "fancy"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "red dress",
      "breasts": "red dress",
      "bottom": "red dress",
      "pussy": "red dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "casual", "office"]
    }),
    "ella stylin see-through dress": toMap({
      "id": "ella stylin see-through dress",
      "category": "stylin",
      "name": "see-through dress",
      "flavor": "The dress makes you feel like a diva, all eyes on you!",
      "description": "white dress with see-through top",
      "price": 800,
      "type": "dress",
      "sluttiness": 6,
      "comfort": 4,
      "durability": 8,
      "style": "elegant",
      "colors": ["white"],
      "tags": ["one piece", "fancy"],
      "emphasizes": ["cleavage", "lots of cleavage"],
      "reveals": ["cleavage", "lots of cleavage"],
      "top": "fancy dress",
      "breasts": "fancy dress",
      "bottom": "fancy dress",
      "pussy": "fancy dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "ella stylin shiny neon dress": toMap({
      "id": "ella stylin shiny neon dress",
      "category": "stylin",
      "name": "shiny neon dress",
      "flavor": "You read this outfit is 'waterproof' and it makes you excited.",
      "description": "plasticy neon dress",
      "price": 350,
      "type": "dress",
      "sluttiness": 9,
      "comfort": 2,
      "durability": 10,
      "style": "slutty",
      "colors": ["green"],
      "tags": ["one piece", "waterproof", "boobs fall out"],
      "emphasizes": ["cleavage", "lots of cleavage"],
      "reveals": ["cleavage", "lots of cleavage"],
      "top": "plasticy dress",
      "breasts": "plasticy dress",
      "bottom": "plasticy dress",
      "pussy": "plasticy dress",
      "breast support": 2,
      "panties under": "can",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["stylin"]
    })
  })
}));