window.GE.outfit_database = window.GE.outfit_database || new Map();

window.GE.outfit_database.set("jade", toMap({
  "purchasable": toMap({
    "beach": 4,
    "casual": 3,
    "fetish": 3,
    "lingerie": 3,
    "gym": 2,
    "lounge": 2,
    "office": 2,
    "stylin": 3
  }),
  "beach": toMap({
    "jade beach black and green": toMap({
      "id": "jade beach black and green",
      "category": "beach",
      "name": "black and green",
      "flavor": "For 'getting wet' in.",
      "description": "black triangle bikini top and green bottom",
      "price": 60,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 3,
      "durability": 3,
      "style": "sexy",
      "colors": ["black", "green"],
      "tags": ["swim", "strings"],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "boobs", "legs", "butt"],
      "top": "triangle bikini top",
      "breasts": "triangle bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "jade beach burgundy one piece": toMap({
      "id": "jade beach burgundy one piece",
      "category": "beach",
      "name": "burgundy one piece",
      "flavor": "It's a bit transparent for a bathing suit.",
      "description": "semi-transparent burgundy one-piece",
      "price": 80,
      "type": "bikini",
      "sluttiness": 8,
      "comfort": 5,
      "durability": 2,
      "style": "slutty",
      "colors": ["red"],
      "tags": ["swim", "one piece"],
      "emphasizes": ["nipples"],
      "reveals": ["tummy", "boobs", "legs", "butt", "nipples"],
      "top": "swimsuit",
      "breasts": "swimsuit",
      "bottom": "swimsuit",
      "pussy": "swimsuit",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach", "lingerie"]
    }),
    "jade beach chevron bikini": toMap({
      "id": "jade beach chevron bikini",
      "category": "beach",
      "name": "chevron bikini",
      "flavor": "You can't help but think you'd look great on a yacht in this. ",
      "description": "black and white chevron triangle bikini",
      "price": 135,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 4,
      "durability": 3,
      "style": "sexy",
      "colors": ["black", "white", "pink"],
      "tags": ["swim", "strings"],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "boobs", "legs", "butt"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach", "lingerie"]
    }),
    "jade beach fishnet one piece": toMap({
      "id": "jade beach fishnet one piece",
      "category": "beach",
      "name": "fishnet one piece",
      "flavor": "Cap'n, we caught something!",
      "description": "white fishnet swimsuit",
      "price": 135,
      "type": "bikini",
      "sluttiness": 9,
      "comfort": 2,
      "durability": 2,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["swim", "strings", "transparent"],
      "emphasizes": ["nipples", "boobs"],
      "reveals": ["tummy", "boobs", "legs", "butt", "nipples"],
      "top": "fishnet swimsuit",
      "breasts": "fishnet swimsuit",
      "bottom": "fishnet swimsuit",
      "pussy": "fishnet swimsuit",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "jade beach halter top bikini": toMap({
      "id": "jade beach halter top bikini",
      "category": "beach",
      "name": "halter top bikini",
      "flavor": "For when you can't decide whether to show underboob or cleavage!",
      "description": "pink bikini and jean shorts",
      "price": 120,
      "type": "casual beach outfit",
      "sluttiness": 7,
      "comfort": 4,
      "durability": 4,
      "style": "slutty",
      "colors": ["pink", "blue"],
      "tags": ["swim"],
      "emphasizes": ["underboob", "cleavage"],
      "reveals": ["tummy", "boobs", "legs", "butt"],
      "top": "halter top bikini",
      "breasts": "halter top bikini",
      "bottom": "jean shorts",
      "pussy": "bikini bottom",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "jade beach purple string bikini": toMap({
      "id": "jade beach purple string bikini",
      "category": "beach",
      "name": "purple string bikini",
      "flavors": [
        "For those perfect bikini tan lines!",
        "Simple purple two piece bikini, standard issue."
      ],
      "description": "purple string bikini top and bottom",
      "price": 80,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 3,
      "durability": 3,
      "style": "sexy",
      "colors": ["purple"],
      "tags": ["swim"],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "boobs", "legs", "butt"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "jade beach white bandeau": toMap({
      "id": "jade beach white bandeau",
      "category": "beach",
      "name": "white bandeau",
      "flavor": "A tight squeeze. Better hope this top doesn't give out.",
      "description": "white bandeau bikini top and bottom",
      "price": 110,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 1,
      "style": "casual",
      "colors": ["white"],
      "tags": ["swim"],
      "emphasizes": [],
      "reveals": ["tummy", "legs", "butt"],
      "top": "bandeau top",
      "breasts": "bandeau top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 1,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "jade beach white microkini": toMap({
      "id": "jade beach white microkini",
      "category": "beach",
      "name": "white microkini",
      "flavor": "Wearing nothing at all might be more conservative than this.",
      "description": "white micro bikini top and bottom",
      "price": 50,
      "type": "bikini",
      "sluttiness": 10,
      "comfort": 2,
      "durability": 1,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["swim", "boobs fall out", "basically naked"],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "legs", "butt", "boobs"],
      "top": "microkini top",
      "breasts": "microkini top",
      "bottom": "microkini bottom",
      "pussy": "microkini bottom",
      "breast support": 1,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    })
  }),
  "casual": toMap({
    "jade casual burning man": toMap({
      "id": "jade casual burning man",
      "category": "casual",
      "name": "burning man",
      "flavor": "Is it hot out here, or is it just you?",
      "description": "black crop top and black shorts",
      "price": 65,
      "type": "casual",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 6,
      "style": "casual",
      "colors": ["black"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["legs", "tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "jade casual cage front": toMap({
      "id": "jade casual cage front",
      "category": "casual",
      "name": "cage front",
      "flavor": "It's hard keeping these puppies all caged up.",
      "description": "pink cage front top and jeans",
      "price": 90,
      "type": "casual",
      "sluttiness": 7,
      "comfort": 6,
      "durability": 3,
      "style": "sexy",
      "colors": ["pink", "blue"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "flats",
      "locations": ["casual", "lounge", "stylin"]
    }),
    "jade casual comfy grey sweatshirt": toMap({
      "id": "jade casual comfy grey sweatshirt",
      "category": "casual",
      "name": "comfy grey sweatshirt",
      "flavor": "For when you want to keep things comfy and casual.",
      "description": "grey sweatshirt and jeans",
      "price": 45,
      "type": "casual",
      "sluttiness": 1,
      "comfort": 10,
      "durability": 10,
      "style": "casual",
      "colors": ["grey", "blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": [],
      "top": "sweatshirt",
      "breasts": "sweatshirt",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "jade casual crop top": toMap({
      "id": "jade casual crop top",
      "category": "casual",
      "name": "crop top",
      "flavor": "Easy outfit for daily errands.",
      "description": "pink crop top and jean shorts",
      "price": 60,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 8,
      "durability": 5,
      "style": "relaxed",
      "colors": ["pink", "blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy", "legs"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "jade casual dip dye dress": toMap({
      "id": "jade casual dip dye dress",
      "category": "casual",
      "name": "dip dye dress",
      "flavor": "This elegant number is to 'dye' for!",
      "description": "dip-dyed dress",
      "price": 190,
      "type": "dress",
      "sluttiness": 5,
      "comfort": 10,
      "durability": 6,
      "style": "elegant",
      "colors": ["blue", "white"],
      "tags": ["zipper", "one piece", "pull down dress"],
      "emphasizes": ["nipples"],
      "reveals": [],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge", "stylin"]
    }),
    "jade casual florida orange": toMap({
      "id": "jade casual florida orange",
      "category": "casual",
      "name": "florida orange",
      "flavor": "Orange you glad I wore this outfit?",
      "description": "orange fishnet top and green shorts",
      "price": 25,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 4,
      "durability": 3,
      "style": "slutty",
      "colors": ["orange", "green"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "fishnet top",
      "breasts": "bandeau bra",
      "bottom": "green shorts",
      "pussy": "green shorts",
      "breast support": 3,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["casual", "stylin"]
    }),
    "jade casual hypebeast": toMap({
      "id": "jade casual hypebeast",
      "category": "casual",
      "name": "hypebeast",
      "flavors": [
        "Aggressive, fashionable, striking.",
        "You know you're every man's fantasy, so why not put it in writing?"
      ],
      "description": "cropped black turtleneck and black jeans",
      "price": 290,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 8,
      "style": "streetwear",
      "colors": ["black"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "cropped turtleneck",
      "breasts": "cropped turtleneck",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "boots",
      "locations": ["casual", "stylin"]
    }),
    "jade casual knot front top": toMap({
      "id": "jade casual knot front top",
      "category": "casual",
      "name": "knot front top",
      "flavor": "For a fun girl that likes being outdoors.",
      "description": "pink tanktop and jeans",
      "price": 80,
      "type": "casual",
      "sluttiness": 4,
      "comfort": 9,
      "durability": 6,
      "style": "relaxed",
      "colors": ["pink", "blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "beach", "lounge"]
    }),
    "jade casual militaristic": toMap({
      "id": "jade casual militaristic",
      "category": "casual",
      "name": "militaristic",
      "flavor": "Will you be giving the orders, or taking them?",
      "description": "green t-shirt and camo pants",
      "price": 110,
      "type": "casual",
      "sluttiness": 1,
      "comfort": 4,
      "durability": 10,
      "style": "modest",
      "colors": ["green"],
      "tags": ["camo"],
      "emphasizes": [],
      "reveals": [],
      "top": "t-shirt",
      "breasts": "t-shirt",
      "bottom": "camo pants",
      "pussy": "camo pants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "boots",
      "locations": ["casual"]
    }),
    "jade casual pink crop top": toMap({
      "id": "jade casual pink crop top",
      "category": "casual",
      "name": "pink crop top",
      "flavor": "You can't deny that pink suits you!",
      "description": "pink crop top and jean shorts",
      "price": 65,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 8,
      "durability": 4,
      "style": "sexy",
      "colors": ["pink", "blue"],
      "tags": [],
      "emphasizes": ["asscheeks"],
      "reveals": ["tummy", "asscheeks"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "jade casual plaid schoolgirl": toMap({
      "id": "jade casual plaid schoolgirl",
      "category": "casual",
      "name": "plaid schoolgirl",
      "flavor": "Lectures and skirts are both best when kept short.",
      "description": "yellow blouse and plaid skirt",
      "price": 120,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["yellow", "black"],
      "tags": ["easy access skirt", "intelligent"],
      "emphasizes": ["asscheeks"],
      "reveals": ["asscheeks"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["casual", "office", "stylin"]
    }),
    "jade casual red crop top": toMap({
      "id": "jade casual red crop top",
      "category": "casual",
      "name": "red crop top",
      "flavor": "Bratty yet seductive.",
      "description": "red crop top and black jean shorts",
      "price": 90,
      "type": "casual",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 3,
      "style": "sexy",
      "colors": ["red", "black"],
      "tags": [],
      "emphasizes": ["asscheeks"],
      "reveals": ["asscheeks", "tummy", "legs"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "office", "stylin"]
    }),
    "jade casual red hoodie": toMap({
      "id": "jade casual red hoodie",
      "category": "casual",
      "name": "red hoodie",
      "flavor": "Some say red is a lucky color.",
      "description": "red hoodie and white sweatpants",
      "price": 110,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 5,
      "style": "relaxed",
      "colors": ["red", "white"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "cropped hoodie",
      "breasts": "cropped hoodie",
      "bottom": "sweatpants",
      "pussy": "sweatpants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "jade casual holographic sailor": toMap({
      "id": "jade casual holographic sailor",
      "category": "casual",
      "name": "holographic sailor",
      "flavors": [
        "Loved by lechers and manga enthusiasts everywhere.",
        "This outfit is soo kawaii!", "Oh, I love this color!"
      ],
      "description": "cropped blouse and skirt",
      "price": 160,
      "type": "skirt and blouse",
      "sluttiness": 8,
      "comfort": 5,
      "durability": 3,
      "style": "slutty",
      "colors": ["blue"],
      "tags": ["easy access skirt", "nerd magnet"],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "jade casual yellow bodysuit": toMap({
      "id": "jade casual yellow bodysuit",
      "category": "casual",
      "name": "yellow bodysuit",
      "flavor": "Funky and fresh.",
      "description": "yellow bodysuit and jean shorts",
      "price": 180,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 7,
      "style": "sexy",
      "colors": ["yellow", "blue"],
      "tags": ["zipper"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    })
  }),
  "fetish": toMap({
    "jade fetish caught mermaid": toMap({
      "id": "jade fetish caught mermaid",
      "category": "fetish",
      "name": "caught mermaid",
      "flavor": "You're the catch of the day!",
      "description": "fishnet bodysuit",
      "price": 140,
      "type": "fetishwear",
      "sluttiness": 9,
      "comfort": 2,
      "durability": 1,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["one piece", "transparent"],
      "emphasizes": ["nipples"],
      "reveals": ["nipples", "boobs", "tummy", "butt", "legs"],
      "top": "fishnet bodysuit",
      "breasts": "fishnet bodysuit",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish", "beach"]
    }),
    "jade fetish chun li": toMap({
      "id": "jade fetish chun li",
      "category": "fetish",
      "name": "chun li",
      "flavor": "I'm going to Spinning-Bird-Strike you…",
      "description": "cosplay outfit",
      "price": 200,
      "type": "cosplay",
      "sluttiness": 8,
      "comfort": 3,
      "durability": 4,
      "style": "sexy",
      "colors": ["blue", "white"],
      "tags": ["one piece", "nerd magnet"],
      "emphasizes": ["cleavage", "legs"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "cosplay outfit",
      "breasts": "cosplay outfit",
      "bottom": "cosplay outfit",
      "pussy": "cosplay outfit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish", "casual"]
    }),
    "jade fetish dva": toMap({
      "id": "jade fetish dva",
      "category": "fetish",
      "name": "dva",
      "flavor": "You know what they say: if you can't fuck the gamer girl, BE the gamer girl!",
      "description": "cosplay outfit",
      "price": 120,
      "type": "cosplay",
      "sluttiness": 5,
      "comfort": 5,
      "durability": 6,
      "style": "sexy",
      "colors": ["blue", "black", "white"],
      "tags": ["one piece", "nerd magnet"],
      "emphasizes": [],
      "reveals": [],
      "top": "cosplay outfit",
      "breasts": "cosplay outfit",
      "bottom": "cosplay outfit",
      "pussy": "cosplay outfit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["fetish", "casual"]
    }),
    "jade fetish killer": toMap({
      "id": "jade fetish killer",
      "category": "fetish",
      "name": "killer",
      "flavor": "Slay, queen!",
      "description": "black bralette and high-waisted buckled panties",
      "price": 210,
      "type": "cosplay",
      "sluttiness": 8,
      "comfort": 3,
      "durability": 7,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["jingles", "stockings", "buckle"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "asscheeks"],
      "top": "bralette",
      "breasts": "bralette",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["fetish", "stylin"]
    }),
    "jade fetish maid": toMap({
      "id": "jade fetish maid",
      "category": "fetish",
      "name": "maid",
      "flavor": "Mon dieu! Zat ees *not* a duster!",
      "description": "french maid outfit",
      "price": 130,
      "type": "dress",
      "sluttiness": 8,
      "comfort": 3,
      "durability": 7,
      "style": "slutty",
      "colors": ["white", "black"],
      "tags": ["chores", "stockings", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["fetish", "lounge"]
    }),
    "jade fetish sex toy": toMap({
      "id": "jade fetish sex toy",
      "category": "fetish",
      "name": "sex toy",
      "flavor": "Screaming 'PLEASE FUCK ME!' would still be less subtle than this outfit.",
      "description": "fishnet top, with a tiny skirt and collar",
      "price": 210,
      "type": "dress",
      "sluttiness": 10,
      "comfort": 3,
      "durability": 2,
      "style": "slutty",
      "colors": ["black", "pink"],
      "tags": ["easy access skirt", "transparent", "collar"],
      "emphasizes": ["cleavage", "asscheeks"],
      "reveals": ["cleavage", "asscheeks", "boobs", "nipples"],
      "top": "fishnet top",
      "breasts": "fishnet top",
      "bottom": "short skirt",
      "pussy": "short skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["fetish", "lounge", "stylin"]
    }),
    "jade fetish slutty kitty sling bikini": toMap({
      "id": "jade fetish slutty kitty sling bikini",
      "category": "fetish",
      "name": "slutty kitty sling bikini",
      "flavors": [
        "Maybe those guys in seventh grade were right to call you a pussy.",
        "For when the kitty wants to be pet.",
        "Meow!",
        "I wonder, what's your equivalent to catnip?"
      ],
      "description": "sling bikini",
      "price": 95,
      "type": "slutty bikini",
      "sluttiness": 10,
      "comfort": 2,
      "durability": 1,
      "style": "slutty",
      "colors": ["blue", "pink"],
      "tags": ["boobs fall out", "straps", "swim"],
      "emphasizes": ["boobs", "asscheeks"],
      "reveals": ["cleavage", "asscheeks", "boobs", "butt", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["fetish", "beach"]
    }),
    "jade fetish stripper": toMap({
      "id": "jade fetish stripper",
      "category": "fetish",
      "name": "stripper",
      "flavor": "Because this body was meant to be seen.",
      "description": "stripper outfit",
      "price": 130,
      "type": "fetishwear",
      "sluttiness": 10,
      "comfort": 2,
      "durability": 4,
      "style": "slutty",
      "colors": ["blue"],
      "tags": ["boobs fall out", "straps", "waterproof", "stripping"],
      "emphasizes": ["boobs", "asscheeks"],
      "reveals": ["cleavage", "asscheeks", "boobs", "butt", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["fetish"]
    })
  }),
  "gym": toMap({
    "jade gym 80s fitness": toMap({
      "id": "jade gym 80s fitness",
      "category": "gym",
      "name": "80s fitness",
      "flavor": "Let's get physical!",
      "description": "black gym bodysuit",
      "price": 145,
      "type": "fitness",
      "sluttiness": 4,
      "comfort": 3,
      "durability": 6,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["great workout", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym"]
    }),
    "jade gym athletic swimsuit": toMap({
      "id": "jade gym athletic swimsuit",
      "category": "gym",
      "name": "athletic swimsuit",
      "flavor": "Why is this in the activewear section?",
      "description": "white one-piece swimsuit",
      "price": 95,
      "type": "fitness",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 1,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["workout", "one piece", "transparent when wet", "swim"],
      "emphasizes": ["cleavage", "legs", "butt"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "beach"]
    }),
    "jade gym bouncy": toMap({
      "id": "jade gym bouncy",
      "category": "gym",
      "name": "bouncy",
      "flavor": "You love big bouncing balls!",
      "description": "white sports bra and sport shorts",
      "price": 130,
      "type": "fitness",
      "sluttiness": 8,
      "comfort": 7,
      "durability": 4,
      "style": "slutty",
      "colors": ["white", "pink"],
      "tags": ["workout"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "legs"],
      "top": "zip-up hoodie",
      "breasts": "sports bra",
      "bottom": "sport shorts",
      "pussy": "sports panties",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym"]
    }),
    "jade gym runner": toMap({
      "id": "jade gym runner",
      "category": "gym",
      "name": "runner",
      "flavor": "Feeling ready for a run, wanna join me?",
      "description": "black sports bra and running shorts",
      "price": 150,
      "type": "fitness",
      "sluttiness": 5,
      "comfort": 5,
      "durability": 8,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["workout"],
      "emphasizes": [],
      "reveals": ["legs", "tummy"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "running shorts",
      "pussy": "running shorts",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    })
  }),
  "lingerie": toMap({
    "jade lingerie black lace lingerie": toMap({
      "id": "jade lingerie black lace lingerie",
      "category": "lingerie",
      "name": "black lace lingerie",
      "flavor": "All the best presents come with a bow, so whose present are you?",
      "description": "black lace bra and panties",
      "price": 80,
      "type": "lingerie",
      "sluttiness": 3,
      "comfort": 4,
      "durability": 6,
      "style": "sexy",
      "colors": ["black"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "butt", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "jade lingerie black strapless bra": toMap({
      "id": "jade lingerie black strapless bra",
      "category": "lingerie",
      "name": "black strapless bra",
      "flavor": "Elegant, sexy, and classic! But not as much support.",
      "description": "black strapless bra and panties",
      "price": 95,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 3,
      "durability": 6,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["strapless"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "butt", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "jade lingerie burgundy multiway bra": toMap({
      "id": "jade lingerie burgundy multiway bra",
      "category": "lingerie",
      "name": "burgundy multiway bra",
      "flavor": "With fabric the color of good wine, there's no doubt they'll all want a taste.",
      "description": "burgundy lace bra and high-waisted string panties",
      "price": 50,
      "type": "lingerie",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 3,
      "style": "sexy",
      "colors": ["black"],
      "tags": [],
      "emphasizes": ["sideboob"],
      "reveals": ["tummy", "butt", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "jade lingerie fancy pink garter": toMap({
      "id": "jade lingerie fancy pink garter",
      "category": "lingerie",
      "name": "fancy pink garter",
      "flavor": "A sugar baby's lingerie of choice.",
      "description": "peach-colored lingerie, with extra trimmings",
      "price": 140,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 4,
      "durability": 6,
      "style": "elegant",
      "colors": ["pink"],
      "tags": ["stockings"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "butt", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "jade lingerie gold velour lingerie": toMap({
      "id": "jade lingerie gold velour lingerie",
      "category": "lingerie",
      "name": "gold velour lingerie",
      "flavor": "Sexy, smooth, and above all, really comfy!",
      "description": "velvety gold bra and panties",
      "price": 120,
      "type": "lingerie",
      "sluttiness": 5,
      "comfort": 10,
      "durability": 4,
      "style": "elegant",
      "colors": ["yellow"],
      "tags": [],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "butt", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "jade lingerie lacy pink lingerie": toMap({
      "id": "jade lingerie lacy pink lingerie",
      "category": "lingerie",
      "name": "lacy pink lingerie",
      "flavor": "Lacy, pink, quite feminine.",
      "description": "pink push-up bra and panties",
      "price": 65,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 3,
      "style": "casual",
      "colors": ["pink"],
      "tags": [],
      "emphasizes": ["cleavage", "push-up bra"],
      "reveals": ["tummy", "butt", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "jade lingerie navy multiway bra": toMap({
      "id": "jade lingerie navy multiway bra",
      "category": "lingerie",
      "name": "navy multiway bra",
      "flavor": "And they say there's no cure for the blues.",
      "description": "lacy blue underwire bra and panties",
      "price": 70,
      "type": "lingerie",
      "sluttiness": 3,
      "comfort": 6,
      "durability": 3,
      "style": "casual",
      "colors": ["blue"],
      "tags": ["underwire"],
      "emphasizes": [],
      "reveals": ["tummy", "butt", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 10,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "jade lingerie navy satin lingerie": toMap({
      "id": "jade lingerie navy satin lingerie",
      "category": "lingerie",
      "name": "navy satin lingerie",
      "flavor": "Perfectly girly. You feel so cute!",
      "description": "blue satin bra and panties",
      "price": 65,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 4,
      "style": "cute",
      "colors": ["blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy", "butt", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "jade lingerie red micro lingerie": toMap({
      "id": "jade lingerie red micro lingerie",
      "category": "lingerie",
      "name": "red micro lingerie",
      "flavor": "Roses are red, his balls are blue…",
      "description": "tiny red bra and panties",
      "price": 120,
      "type": "lingerie",
      "sluttiness": 10,
      "comfort": 4,
      "durability": 2,
      "style": "slutty",
      "colors": ["red"],
      "tags": [],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "butt", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 2,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "jade lingerie sugar baby lingerie": toMap({
      "id": "jade lingerie sugar baby lingerie",
      "category": "lingerie",
      "name": "sugar baby lingerie",
      "flavors": [
        "You look as sweet as candy in this.",
        "You bring the baby, he'll bring the sugar."
      ],
      "description": "fancy bra, panties and garter",
      "price": 250,
      "type": "lingerie",
      "sluttiness": 7,
      "comfort": 3,
      "durability": 8,
      "style": "elegant",
      "colors": ["pink"],
      "tags": ["stockings"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "butt", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "jade lingerie white lace lingerie": toMap({
      "id": "jade lingerie white lace lingerie",
      "category": "lingerie",
      "name": "white lace lingerie",
      "flavor": "Indecent? Maybe. Indecorous? Probably. Insanely hot? Definitely.",
      "description": "cage-front white bra and panties",
      "price": 70,
      "type": "lingerie",
      "sluttiness": 9,
      "comfort": 7,
      "durability": 3,
      "style": "sexy",
      "colors": ["white"],
      "tags": ["stockings", "semi-transparent"],
      "emphasizes": ["cleavage", "nipples"],
      "reveals": ["tummy", "butt", "legs", "boobs", "nipples"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    })
  }),
  "lounge": toMap({
    "jade lounge bra and shorts": toMap({
      "id": "jade lounge bra and shorts",
      "category": "lounge",
      "name": "bra and shorts",
      "flavor": "Can I walk around the house like this?",
      "description": "bra and jean shorts",
      "price": 35,
      "type": "loungewear",
      "sluttiness": 8,
      "comfort": 6,
      "durability": 6,
      "style": "slutty",
      "colors": ["pink", "blue"],
      "tags": ["bra on top"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "jean shorts",
      "pussy": "panties",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "jade lounge kimono": toMap({
      "id": "jade lounge kimono",
      "category": "lounge",
      "name": "kimono",
      "flavors": [
        "Who wouldn't love to watch those cherry blossoms fall?",
        "A comfy kimono that's easy to walk around in."
      ],
      "description": "soft kimono",
      "price": 90,
      "type": "loungewear",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 5,
      "style": "elegant",
      "colors": ["white"],
      "tags": ["one piece", "robe", "sleep"],
      "emphasizes": [],
      "reveals": [],
      "top": "kimono",
      "breasts": "kimono",
      "bottom": "kimono",
      "pussy": "kimono",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "jade lounge nightgown": toMap({
      "id": "jade lounge nightgown",
      "category": "lounge",
      "name": "nightgown",
      "flavor": "The silk feels delicious on your soft, sensitive skin.",
      "description": "comfy, silky nightgown",
      "price": 150,
      "type": "loungewear",
      "sluttiness": 4,
      "comfort": 10,
      "durability": 3,
      "style": "elegant",
      "colors": ["white"],
      "tags": ["one piece", "robe", "sleep"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "nightgown",
      "breasts": "nightgown",
      "bottom": "nightgown",
      "pussy": "nightgown",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "jade lounge underboob top": toMap({
      "id": "jade lounge underboob top",
      "category": "lounge",
      "name": "underboob top",
      "flavor": "Cleavage is out, underboob is in!",
      "description": "crop top and panties",
      "price": 35,
      "type": "loungewear",
      "sluttiness": 9,
      "comfort": 8,
      "durability": 2,
      "style": "slutty",
      "colors": ["white", "black"],
      "tags": ["sleep"],
      "emphasizes": ["underboob"],
      "reveals": ["underboob", "tummy", "butt", "legs"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    })
  }),
  "office": toMap({
    "jade office black dress": toMap({
      "id": "jade office black dress",
      "category": "office",
      "name": "black dress",
      "flavor": "For the girl who wants to own her sexiness. You go, sis!",
      "description": "black dress",
      "price": 180,
      "type": "sexy office",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 3,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["one piece", "easy access dress", "professional", "semi-transparent"],
      "emphasizes": [],
      "reveals": [],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "jade office black pencil skirt": toMap({
      "id": "jade office black pencil skirt",
      "category": "office",
      "name": "black pencil skirt",
      "flavor": "Boss Bitch, or Sexy Secretary?",
      "description": "blouse and skirt",
      "price": 180,
      "type": "office",
      "sluttiness": 1,
      "comfort": 6,
      "durability": 5,
      "style": "elegant",
      "colors": ["white", "black"],
      "tags": ["professional"],
      "emphasizes": [],
      "reveals": [],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "jade office blue plaid skirt": toMap({
      "id": "jade office blue plaid skirt",
      "category": "office",
      "name": "blue plaid skirt",
      "flavor": "A good outfit is like a good slogan. Short, sweet, and to the point.",
      "description": "blouse and plaid skirt",
      "price": 140,
      "type": "office",
      "sluttiness": 3,
      "comfort": 5,
      "durability": 4,
      "style": "cute",
      "colors": ["white", "blue"],
      "tags": ["professional", "easy access skirt"],
      "emphasizes": [],
      "reveals": [],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office", "louge", "stylin"]
    }),
    "jade office low cut blouse": toMap({
      "id": "jade office low cut blouse",
      "category": "office",
      "name": "low cut blouse",
      "flavor": "Sure, you're adorable, but be ready for the jokes about 'bring your daughter to work day'.",
      "description": "blouse and plaid skirt with stockings",
      "price": 160,
      "type": "office",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["white", "green"],
      "tags": ["professional", "easy access skirt", "stockings"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    })
  }),
  "stylin": toMap({
    "jade stylin a coat makes it acceptable": toMap({
      "id": "jade stylin a coat makes it acceptable",
      "category": "stylin",
      "name": "a coat makes it acceptable",
      "flavor": "Sorry, even with the coat you're still more 'pussy' than 'punk'.",
      "description": "leather jacket and fishnet outfit",
      "price": 250,
      "type": "slutty outfit",
      "sluttiness": 10,
      "comfort": 2,
      "durability": 7,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["transparent"],
      "emphasizes": ["boobs", "nipples"],
      "reveals": ["nipples", "boobs", "tummy", "butt"],
      "top": "leather jacket",
      "breasts": "leather jacket",
      "bottom": "fishnet outfit",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "casual"]
    }),
    "jade stylin black dragon": toMap({
      "id": "jade stylin black dragon",
      "category": "stylin",
      "name": "black dragon",
      "flavor": "Brave men don't kill dragons, they ride them!",
      "description": "bomber jacket, mesh top and green pants",
      "price": 270,
      "type": "slutty outfit",
      "sluttiness": 8,
      "comfort": 7,
      "durability": 5,
      "style": "slutty",
      "colors": ["black", "green"],
      "tags": ["transparent", "two layer top"],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "boobs"],
      "top": "bomber jacket",
      "breasts": "mesh top",
      "bottom": "pants",
      "pussy": "pants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "casual"]
    }),
    "jade stylin flames": toMap({
      "id": "jade stylin flames",
      "category": "stylin",
      "name": "flames",
      "flavors": [
        "Great at a rave!",
        "Hot and bothered, not to mention collared.",
        "You'll make everyone burn with desire."
      ],
      "description": "crop top and legless shorts",
      "price": 110,
      "type": "sexy outfit",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["collar"],
      "emphasizes": [],
      "reveals": ["tummy", "butt", "legs"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "legless shorts",
      "pussy": "legless shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "stylish shoes",
      "locations": ["stylin", "casual"]
    }),
    "jade stylin pink velvet dress": toMap({
      "id": "jade stylin pink velvet dress",
      "category": "stylin",
      "name": "pink velvet dress",
      "flavor": "This crushed velvet will get the attention of your crush.",
      "description": "pink velvet dress",
      "price": 350,
      "type": "sexy outfit",
      "sluttiness": 7,
      "comfort": 6,
      "durability": 4,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["easy access dress", "one piece"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "office"]
    }),
    "jade stylin red dress": toMap({
      "id": "jade stylin red dress",
      "category": "stylin",
      "name": "red dress",
      "flavor": "Red can stand for a lot of things. Power, sensuality, all the blood flowing into his cock right now…",
      "description": "low-cut red dress",
      "price": 270,
      "type": "sexy outfit",
      "sluttiness": 8,
      "comfort": 5,
      "durability": 6,
      "style": "sexy",
      "colors": ["red"],
      "tags": ["easy access dress", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["lots of cleavage", "cleavage", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "office"]
    })
  })
}));