window.GE.outfit_database = window.GE.outfit_database || new Map();

window.GE.outfit_database.set("jia", toMap({
  "purchasable": toMap({
    "beach": 3,
    "casual": 3,
    "fetish": 3,
    "lingerie": 3,
    "gym": 3,
    "lounge": 3,
    "office": 2,
    "stylin": 3
  }),
  "beach": toMap({
    "jia beach green one piece": toMap({
      "id": "jia beach green one piece",
      "category": "beach",
      "name": "green one piece",
      "flavor": "For the genuine swimmer (who still likes to flaunt a bit).",
      "description": "forest green one piece",
      "price": 60,
      "type": "one piece",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 4,
      "style": "elegant",
      "colors": ["green"],
      "tags": ["swim", "one piece"],
      "emphasizes": ["butt"],
      "reveals": ["legs", "butt"],
      "top": "green one piece",
      "breasts": "green one piece",
      "bottom": "green one piece",
      "pussy": "green one piece",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach", "lounge"]
    }),
    "jia beach lacy beach dress": toMap({
      "id": "jia beach lacy beach dress",
      "category": "beach",
      "name": "lacy beach dress",
      "flavor": "Really lets your skin breathe.",
      "description": "netted beach dress",
      "price": 75,
      "type": "casual beachwear",
      "sluttiness": 3,
      "comfort": 8,
      "durability": 6,
      "style": "cute",
      "colors": ["white"],
      "tags": ["one piece", "easy access dress"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "beach dress",
      "breasts": "beach dress",
      "bottom": "beach dress",
      "pussy": "beach dress",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach", "lounge"]
    }),
    "jia beach crochet halter top": toMap({
      "id": "jia beach crochet halter top",
      "category": "beach",
      "name": "crochet halter top",
      "flavor": "The top is quite distinctive.",
      "description": "white crochet halter bikini top with brazilian bikini bottom",
      "price": 90,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 8,
      "durability": 6,
      "style": "sexy",
      "colors": ["white"],
      "tags": ["swim", "strings"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "tummy", "legs"],
      "top": "white crochet top",
      "breasts": "white crochet top",
      "bottom": "brazilian bikini bottom",
      "pussy": "brazilian bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),

    "jia beach v-neck swimsuit": toMap({
      "id": "jia beach v-neck swimsuit",
      "category": "beach",
      "name": "v-neck swimsuit",
      "flavor": "You'd think orange would be too much, with your red hair. But you just look so fucking gorgeous in this!",
      "description": "orange v-neck one piece swimsuit",
      "price": 120,
      "type": "one-piece swimsuit",
      "sluttiness": 5,
      "comfort": 7,
      "durability": 7,
      "style": "sexy",
      "colors": ["orange"],
      "tags": ["swim", "one piece"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "tummy", "legs"],
      "top": "orange one-piece",
      "breasts": "orange one-piece",
      "bottom": "orange one-piece",
      "pussy": "orange one-piece",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),

    "jia beach tiny teal bikini": toMap({
      "id": "jia beach tiny teal bikini",
      "category": "beach",
      "name": "tiny teal bikini",
      "flavor": "This barely there bikini set barely covers your nipples or your pussy. But somehow, you can pull it off!",
      "description": "teal coloured string bikini",
      "price": 70,
      "type": "bikini",
      "sluttiness": 9,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["teal"],
      "tags": ["swim", "strings"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "tummy", "legs"],
      "top": "teal bikini top",
      "breasts": "teal bikini top",
      "bottom": "teal bikini bottom",
      "pussy": "teal bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),

    "jia beach red string bikini": toMap({
      "id": "jia beach red string bikini",
      "category": "beach",
      "name": "red string bikini",
      "flavor": "This is sure to give you some looks.",
      "description": "red string bikini",
      "price": 70,
      "type": "bikini",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 6,
      "style": "sexy",
      "colors": ["red"],
      "tags": ["swim", "strings"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "tummy", "legs"],
      "top": "red bikini top",
      "breasts": "red bikini top",
      "bottom": "red bikini bottom",
      "pussy": "red bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),

    "jia beach lavender bikini": toMap({
      "id": "jia beach lavender bikini",
      "category": "beach",
      "name": "lavender bikini",
      "flavor": "Lavender! People don't think about this color enough for bikinis.",
      "description": "lavender bikini",
      "price": 70,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 6,
      "style": "cute",
      "colors": ["lavender"],
      "tags": ["swim", "strings"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "tummy", "legs"],
      "top": "lavender bikini top",
      "breasts": "lavender bikini top",
      "bottom": "lavender bikini bottom",
      "pussy": "lavender bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),

    "jia beach teal tropical bikini": toMap({
      "id": "jia beach teal tropical bikini",
      "category": "beach",
      "name": "teal tropical bikini",
      "flavor": "Time for a vacation!",
      "description": "tropical pattern teal bikini",
      "price": 70,
      "type": "bikini",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["teal"],
      "tags": ["swim", "strings"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "tummy", "legs"],
      "top": "teal bikini top",
      "breasts": "teal bikini top",
      "bottom": "teal bikini bottom",
      "pussy": "teal bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),

    "jia beach navy blue bikini": toMap({
      "id": "jia beach navy blue bikini",
      "category": "beach",
      "name": "navy blue bikini",
      "flavor": "The high-waisted bottom is so freaking cute!",
      "description": "navy blue string bikini",
      "price": 65,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 5,
      "style": "sexy",
      "colors": ["navy blue"],
      "tags": ["swim", "strings"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "tummy", "legs"],
      "top": "navy blue bikini top",
      "breasts": "navy blue bikini top",
      "bottom": "navy blue bikini bottom",
      "pussy": "navy blue bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "jia beach orange bikini": toMap({
      "id": "jia beach orange bikini",
      "category": "beach",
      "name": "orange bikini",
      "flavor": "Now you get to *be* the sun!",
      "description": "bikini top and bottom",
      "price": 80,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 5,
      "durability": 3,
      "style": "sexy",
      "colors": ["orange"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["legs", "butt", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "jia beach black bikini": toMap({
      "id": "jia beach black bikini",
      "category": "beach",
      "name": "black bikini",
      "flavor": "Doesn't cover much - be sure to use sunscreen!",
      "description": "black bikini top and bottom",
      "price": 65,
      "type": "bikini",
      "sluttiness": 7,
      "comfort": 4,
      "durability": 3,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["swim", "basically naked"],
      "emphasizes": ["butt"],
      "reveals": ["legs", "butt", "tummy", "boobs"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "jia beach purple bikini": toMap({
      "id": "jia beach purple bikini",
      "category": "beach",
      "name": "purple bikini",
      "flavor": "Tight and tiny - just like you!",
      "description": "purple bikini top and bottom",
      "price": 45,
      "type": "bikini",
      "sluttiness": 8,
      "comfort": 3,
      "durability": 1,
      "style": "slutty",
      "colors": ["purple"],
      "tags": ["swim", "basically naked"],
      "emphasizes": ["butt"],
      "reveals": ["legs", "butt", "tummy", "boobs"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "jia beach red booty shorts": toMap({
      "id": "jia beach red booty shorts",
      "category": "beach",
      "name": "red booty shorts",
      "flavor": "It takes no small amount of cheek to put on shorts that tiny.",
      "description": "tank top and red booty shorts",
      "price": 65,
      "type": "casual beachwear",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 3,
      "style": "sexy",
      "colors": ["red"],
      "tags": [],
      "emphasizes": ["asscheeks"],
      "reveals": ["legs", "butt", "tummy"],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "booty shorts",
      "pussy": "booty shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach", "casual", "lounge"]
    })
  }),
  "casual": toMap({
    "jia casual blue dress": toMap({
      "id": "jia casual blue dress",
      "category": "casual",
      "name": "blue dress",
      "flavor": "Cute, feminine, and just the right balance between casual and dressy!",
      "description": "blue dress",
      "price": 95,
      "type": "dress",
      "sluttiness": 3,
      "comfort": 6,
      "durability": 5,
      "style": "cute",
      "colors": ["blue"],
      "tags": ["easy access dress"],
      "emphasizes": [],
      "reveals": [],
      "top": "blue dress",
      "breasts": "blue dress",
      "bottom": "blue dress",
      "pussy": "blue dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge", "stylin"]
    }),
    "jia casual bookworm": toMap({
      "id": "jia casual bookworm",
      "category": "casual",
      "name": "bookworm",
      "flavor": "Low effort is best effort.",
      "description": "loose white blouse and blue shorts",
      "price": 40,
      "type": "casual",
      "sluttiness": 4,
      "comfort": 9,
      "durability": 4,
      "style": "relaxed",
      "colors": ["blue"],
      "tags": ["easy access dress", "intelligent"],
      "emphasizes": [],
      "reveals": ["legs", "asscheeks"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "jia casual crop top": toMap({
      "id": "jia casual crop top",
      "category": "casual",
      "name": "crop top",
      "flavor": "This outfit conceals so little... but then, why would you want to hide those curves?",
      "description": "crop top and short shorts",
      "price": 55,
      "type": "casual",
      "sluttiness": 9,
      "comfort": 6,
      "durability": 2,
      "style": "slutty",
      "colors": ["white"],
      "tags": [],
      "emphasizes": ["butt", "asscheeks"],
      "reveals": ["butt", "asscheeks", "tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge", "beach", "stylin"]
    }),
    "jia casual fields of wheat": toMap({
      "id": "jia casual fields of wheat",
      "category": "casual",
      "name": "fields of wheat",
      "flavors": [
        "It makes you feel like such a good girl!",
        "Every woman looks good in a sundress!",
        "Who doesn't want a white sundress and straw hat?"
      ],
      "description": "flowy sundress and hat",
      "price": 55,
      "type": "casual",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 5,
      "style": "cute",
      "colors": ["white"],
      "tags": ["easy access dress", "hat"],
      "emphasizes": [],
      "reveals": ["boobs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "beach", "stylin"]
    }),
    "jia casual fishnets": toMap({
      "id": "jia casual fishnets",
      "category": "casual",
      "name": "fishnets",
      "flavors": [
        "Bright and sparkly, just in case your legs weren't drawing enough attention already!",
        "Do you like the looks you get when you wear fishnets?"
      ],
      "description": "pink bodysuit and fishnet leggings",
      "price": 110,
      "type": "casual",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["stockings"],
      "emphasizes": ["legs"],
      "reveals": ["legs", "butt"],
      "top": "pink bodysuit",
      "breasts": "pink bodysuit",
      "bottom": "fishnet leggings",
      "pussy": "fishnet leggings",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "jia casual hypnotic": toMap({
      "id": "jia casual hypnotic",
      "category": "casual",
      "name": "hypnotic",
      "flavor": "The hypnotic pattern is going to keep men staring even longer than usual, which is really saying something.",
      "description": "short dress with sleeves",
      "price": 135,
      "type": "dress",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 5,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["easy access dress", "short dress"],
      "emphasizes": ["legs", "asscheeks"],
      "reveals": ["legs", "butt"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge", "stylin", "office"]
    }),
    "jia casual lemonade": toMap({
      "id": "jia casual lemonade",
      "category": "casual",
      "name": "lemonade",
      "flavors": [
        "So cute! Would be super modest if it wasn't so short.",
        "Who'd think yellow would go so well with your red hair?",
        "Tastes like girlhood!"
      ],
      "description": "yellow turtleneck and overalls",
      "price": 90,
      "type": "casual",
      "sluttiness": 3,
      "comfort": 8,
      "durability": 10,
      "style": "cute",
      "colors": ["blue", "yellow"],
      "tags": ["easy access skirt"],
      "emphasizes": ["legs"],
      "reveals": ["legs"],
      "top": "turtleneck",
      "breasts": "turtleneck",
      "bottom": "denim skirt",
      "pussy": "denim skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge", "stylin"]
    }),
    "jia casual pink dress": toMap({
      "id": "jia casual pink dress",
      "category": "casual",
      "name": "pink dress",
      "flavor": "Get used to feeling the breeze each time you bend over.",
      "description": "pink dress",
      "price": 75,
      "type": "casual",
      "sluttiness": 7,
      "comfort": 7,
      "durability": 5,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["easy access dress", "short dress"],
      "emphasizes": ["asscheeks"],
      "reveals": ["legs", "asscheeks"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge", "stylin", "office"]
    }),
    "jia casual plaid skirt": toMap({
      "id": "jia casual plaid skirt",
      "category": "casual",
      "name": "plaid skirt",
      "flavor": "You're never too old to release your inner schoolgirl!",
      "description": "pink sweater and plaid skirt",
      "price": 90,
      "type": "casual",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 7,
      "style": "cute",
      "colors": ["pink"],
      "tags": ["easy access skirt"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "sweater",
      "breasts": "sweater",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "office", "lounge"]
    }),
    "jia casual red dress": toMap({
      "id": "jia casual red dress",
      "category": "casual",
      "name": "red dress",
      "flavor": "Flowery and femme, it makes you look the way you feel inside!",
      "description": "red dress",
      "price": 110,
      "type": "casual",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 6,
      "style": "elegant",
      "colors": ["red"],
      "tags": ["easy access dress", "one piece"],
      "emphasizes": [],
      "reveals": ["legs", "boobs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "office", "lounge", "stylin"]
    })
  }),
  "fetish": toMap({
    "jia fetish black garter": toMap({
      "id": "jia fetish black garter",
      "category": "fetish",
      "name": "black garter",
      "flavors": [
        "Oh, dear, what shall I do? Baby's in black and my balls are so blue…",
        "Looking for a dom? Nothing advertises your subbie body better than something like this..."
      ],
      "description": "black bra and panties with garter",
      "price": 110,
      "type": "fetishwear",
      "sluttiness": 8,
      "comfort": 2,
      "durability": 3,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["straps", "stripping", "stockings"],
      "emphasizes": ["butt"],
      "reveals": ["tummy", "butt"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["fetish", "lingerie"]
    }),
    "jia fetish black teddy": toMap({
      "id": "jia fetish black teddy",
      "category": "fetish",
      "name": "black teddy",
      "flavors": [
        "When you were a kid, you clung tight to a teddy; but now that you're a woman, the teddy clings tight to you!",
        "Though it's revealing... it keeps just enough mystery about it to leave someone asking for more...",
        "Just because it's patterned lace doesn't mean they can't see through it...",
        "The long leg line gives it a bit of respectability and elegance."
      ],
      "description": "black bra and panties with garter",
      "price": 45,
      "type": "fetishwear",
      "sluttiness": 7,
      "comfort": 4,
      "durability": 3,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["one piece lingerie", "standalone lingerie"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "legs"],
      "top": "teddy",
      "breasts": "teddy",
      "bottom": "teddy",
      "pussy": "teddy",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish", "lingerie"]
    }),
    "jia fetish purple bodysuit": toMap({
      "id": "jia fetish purple bodysuit",
      "category": "fetish",
      "name": "purple bodysuit",
      "flavors": [
        "The fabric is deliberately made as sheer as possible - why wear all those straps underneath if you don't want people to see them?",
        "Might want to do up those poppers... not that it'll hide much - its essentially transparent."
      ],
      "description": "purple bodysuit and black leather harness",
      "price": 340,
      "type": "fetishwear",
      "sluttiness": 9,
      "comfort": 2,
      "durability": 2,
      "style": "slutty",
      "colors": ["purple", "black"],
      "tags": ["push aside panties", "two layer one piece", "transparent", "no obstruction"],
      "emphasizes": ["nipples", "butt"],
      "reveals": ["butt", "legs", "nipples", "boobs", "pussy"],
      "top": "purple bodysuit",
      "breasts": "leather harness",
      "bottom": "purple bodysuit",
      "pussy": "purple bodysuit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    }),
    "jia fetish red leather straps": toMap({
      "id": "jia fetish red leather straps",
      "category": "fetish",
      "name": "red leather straps",
      "flavor": "Strap yourself in, it's gonna be a bumpy ride!",
      "description": "black teddy and red leather harness",
      "price": 70,
      "type": "fetishwear",
      "sluttiness": 8,
      "comfort": 1,
      "durability": 8,
      "style": "slutty",
      "colors": ["black", "red"],
      "tags": ["push aside panties", "hard to remove", "straps", "jingles", "no obstruction"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "legs", "boobs"],
      "top": "teddy",
      "breasts": "teddy",
      "bottom": "red harness",
      "pussy": "teddy",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    }),
    "jia fetish velvet bodysuit": toMap({
      "id": "jia fetish velvet bodysuit",
      "category": "fetish",
      "name": "velvet bodysuit",
      "flavor": "It's almost smoother than your own skin!",
      "description": "velvet bodysuit",
      "price": 135,
      "type": "fetishwear",
      "sluttiness": 4,
      "comfort": 10,
      "durability": 5,
      "style": "elegant",
      "colors": ["blue"],
      "tags": ["one piece", "push aside panties"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "legs"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    }),
    "jia fetish white bodysuit": toMap({
      "id": "jia fetish white bodysuit",
      "category": "fetish",
      "name": "white bodysuit",
      "flavor": "Covers your whole torso and yet hides absolutely nothing.",
      "description": "white fishnet bodysuit",
      "price": 110,
      "type": "fetishwear",
      "sluttiness": 9,
      "comfort": 7,
      "durability": 3,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["one piece", "push aside panties", "transparent"],
      "emphasizes": ["butt", "nipples", "pussy"],
      "reveals": ["butt", "legs", "nipples", "pussy"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    })
  }),
  "lingerie": toMap({
    "jia lingerie blue lingerie": toMap({
      "id": "jia lingerie blue lingerie",
      "category": "lingerie",
      "name": "blue lingerie",
      "flavor": "You only need the teensiest of bras to cover your tiny, perky boobies.",
      "description": "embroidered blue bra and panties",
      "price": 55,
      "type": "lingerie",
      "sluttiness": 3,
      "comfort": 3,
      "durability": 4,
      "style": "elegant",
      "colors": ["blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy", "butt", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "jia lingerie cute af": toMap({
      "id": "jia lingerie cute af",
      "category": "lingerie",
      "name": "cute af",
      "flavor": "It's not a crime to advertise. Especially when the product really does live up to the hype!",
      "description": "white bra and red panties",
      "price": 25,
      "type": "lingerie",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 3,
      "style": "cute",
      "colors": ["white", "red"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy", "butt", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "jia lingerie red panties": toMap({
      "id": "jia lingerie red panties",
      "category": "lingerie",
      "name": "red panties",
      "flavors": [
        "They fit you perfectly.",
        "A Redhead in Red Panties is just asking for a good dicking...",
        "Your 'getting lucky' panties!",
        "My fav band is Red hot booty lovers, what's yours?",
        "These nestle between your cheeks with a feminine delicacy that makes you tingle. So girly.",
        "You can get away without a bra and these thong panties are about as sexy as it gets."
      ],
      "description": "pair of red panties",
      "price": 10,
      "type": "lingerie",
      "sluttiness": 8,
      "comfort": 7,
      "durability": 2,
      "style": "sexy",
      "colors": ["red"],
      "tags": ["just panties"],
      "emphasizes": ["nipples"],
      "reveals": ["tummy", "butt", "legs", "boobs", "nipples"],
      "top": "none",
      "breasts": "none",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "jia lingerie underwire bra": toMap({
      "id": "jia lingerie underwire bra",
      "category": "lingerie",
      "name": "underwire bra",
      "flavor": "Flesh tone and provocative, this'll make people stare is they see it.",
      "description": "underwire bra and decorative panties",
      "price": 80,
      "type": "lingerie",
      "sluttiness": 6,
      "comfort": 3,
      "durability": 8,
      "style": "elegant",
      "colors": ["brown"],
      "tags": ["just panties"],
      "emphasizes": ["nipples"],
      "reveals": ["tummy", "butt", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    })
  }),
  "gym": toMap({
    "jia gym blue yoga": toMap({
      "id": "jia gym blue yoga",
      "category": "gym",
      "name": "blue yoga",
      "flavors": [
        "Yes, honey, this does make your butt look big.",
        "You know your butt looks great but now it can look divine.",
        "Blue's a good color for you!"
      ],
      "description": "blue yoga outfit with toe socks",
      "price": 75,
      "type": "fitness",
      "sluttiness": 6,
      "comfort": 8,
      "durability": 8,
      "style": "sexy",
      "colors": ["blue"],
      "tags": ["great workout"],
      "emphasizes": ["butt"],
      "reveals": ["tummy"],
      "top": "yoga top",
      "breasts": "yoga top",
      "bottom": "yoga pants",
      "pussy": "yoga pants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "weird toe socks",
      "locations": ["gym", "lounge"]
    }),
    "jia gym workout bunny": toMap({
      "id": "jia gym workout bunny",
      "category": "gym",
      "name": "workout bunny",
      "flavor": "Damn, just imagine how you'll look doing squats in this.",
      "description": "neon green sports bra and sports thong",
      "price": 80,
      "type": "workout",
      "sluttiness": 7,
      "comfort": 6,
      "durability": 4,
      "style": "sexy fitness",
      "colors": ["lavender"],
      "tags": ["standalone lingerie"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "tummy", "legs"],
      "top": "neon green sports bra",
      "breasts": "neon green sports bra",
      "bottom": "neon green sports thong",
      "pussy": "neon green sports thong",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    }),
    "jia gym peach sports bra": toMap({
      "id": "jia gym peach sports bra",
      "category": "gym",
      "name": "peach sports bra",
      "flavor": "Your female body may not be very busty, but at least you don't have to worry about flopping around everywhere when you work out!",
      "description": "set of comfy workout clothes",
      "price": 40,
      "type": "fitness",
      "sluttiness": 4,
      "comfort": 10,
      "durability": 4,
      "style": "sexy",
      "colors": ["pink", "blue"],
      "tags": ["workout"],
      "emphasizes": ["asscheeks"],
      "reveals": ["tummy", "legs", "asscheeks"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "frilly sport shorts",
      "pussy": "frilly sport shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    }),
    "jia gym yellow shorts": toMap({
      "id": "jia gym yellow shorts",
      "category": "gym",
      "name": "yellow shorts",
      "flavors": [
        "Wedgies feel way less uncool in this outfit... maybe this time the gym bros will agree?",
        "Perfect for showing off... your GAINS, of course!",
        "Short shorts, sports bra and long white socks. The whole gym be looking at you..."
      ],
      "description": "white sports bra and yellow sport shorts",
      "price": 55,
      "type": "fitness",
      "sluttiness": 8,
      "comfort": 8,
      "durability": 3,
      "style": "slutty",
      "colors": ["white", "yellow"],
      "tags": ["great workout"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "tummy", "legs"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "sport shorts",
      "pussy": "sport shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    })
  }),
  "lounge": toMap({
    "jia lounge cherry": toMap({
      "id": "jia lounge cherry",
      "category": "lounge",
      "name": "cherry",
      "flavor": "An easy way to remind yourself where your own personal cherry is... or was, if you've already popped it.",
      "description": "tank top and panties",
      "price": 30,
      "type": "loungewear",
      "sluttiness": 7,
      "comfort": 10,
      "durability": 4,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["sleep"],
      "emphasizes": [],
      "reveals": ["butt", "legs"],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "jia lounge floral pjs": toMap({
      "id": "jia lounge floral pjs",
      "category": "lounge",
      "name": "floral pjs",
      "flavor": "You look pretty as a painting in these!",
      "description": "frilly crop top and panties",
      "price": 40,
      "type": "loungewear",
      "sluttiness": 9,
      "comfort": 8,
      "durability": 2,
      "style": "cute",
      "colors": ["pink"],
      "tags": ["sleep"],
      "emphasizes": [],
      "reveals": ["butt", "legs", "tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "frilly panties",
      "pussy": "frilly panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "jia lounge flowery wrap robe": toMap({
      "id": "jia lounge flowery wrap robe",
      "category": "lounge",
      "name": "flowery wrap robe",
      "flavor": "You really are just a little red flower, waiting to be plucked!",
      "description": "comfy floral robe",
      "price": 90,
      "type": "loungewear",
      "sluttiness": 1,
      "comfort": 10,
      "durability": 5,
      "style": "cute",
      "colors": ["pink"],
      "tags": ["sleep", "robe", "one piece"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "robe",
      "breasts": "robe",
      "bottom": "robe",
      "pussy": "robe",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "jia lounge game night": toMap({
      "id": "jia lounge game night",
      "category": "lounge",
      "name": "game night",
      "flavor": "You couldn't cut this top shorter without flashing and the briefs while cute are small enough to draw attention.",
      "description": "cropped sports top and white panties",
      "price": 35,
      "type": "loungewear",
      "sluttiness": 10,
      "comfort": 6,
      "durability": 2,
      "style": "slutty",
      "colors": ["black", "white"],
      "tags": ["sleep", "distracting", "not serious"],
      "emphasizes": ["butt"],
      "reveals": ["legs", "tummy", "butt"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "jia lounge green pjs": toMap({
      "id": "jia lounge green pjs",
      "category": "lounge",
      "name": "green pjs",
      "flavor": "These match your hair so nicely.",
      "description": "soft pj top and panties",
      "price": 45,
      "type": "loungewear",
      "sluttiness": 7,
      "comfort": 9,
      "durability": 4,
      "style": "sexy",
      "colors": ["green"],
      "tags": ["sleep"],
      "emphasizes": [],
      "reveals": ["butt", "legs"],
      "top": "pajama top",
      "breasts": "pajama top",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "jia lounge lacy chemise": toMap({
      "id": "jia lounge lacy chemise",
      "category": "lounge",
      "name": "lacy chemise",
      "flavor": "This is WAY classier than flannel pajamas.",
      "description": "soft pj top and panties",
      "price": 90,
      "type": "loungewear",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 7,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["sleep", "semi-transparent", "one piece"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "chemise",
      "breasts": "chemise",
      "bottom": "chemise",
      "pussy": "chemise",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "jia lounge stripey pjs": toMap({
      "id": "jia lounge stripey pjs",
      "category": "lounge",
      "name": "stripey pjs",
      "flavor": "A hot cup of tea would be a perfect accompaniment.",
      "description": "pj top and panties",
      "price": 40,
      "type": "loungewear",
      "sluttiness": 5,
      "comfort": 9,
      "durability": 6,
      "style": "cute",
      "colors": ["purple"],
      "tags": ["sleep"],
      "emphasizes": ["butt"],
      "reveals": ["legs", "butt"],
      "top": "pajama top",
      "breasts": "pajama top",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "jia lounge teal pjs": toMap({
      "id": "jia lounge teal pjs",
      "category": "lounge",
      "name": "teal pjs",
      "flavor": "Minty fresh!",
      "description": "pj top and panties",
      "price": 45,
      "type": "loungewear",
      "sluttiness": 6,
      "comfort": 9,
      "durability": 6,
      "style": "cute",
      "colors": ["green", "white"],
      "tags": ["sleep"],
      "emphasizes": ["butt"],
      "reveals": ["legs", "butt", "tummu"],
      "top": "pajama top",
      "breasts": "pajama top",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "jia lounge warm and cozy": toMap({
      "id": "jia lounge warm and cozy",
      "category": "lounge",
      "name": "warm and cozy",
      "flavors": [
        "Pair this with some hot cocoa, for a perfect night in!",
        "Cute, cozy, and shows just the right amount of skin."
      ],
      "description": "comfy off-shoulder nightgown",
      "price": 60,
      "type": "dress",
      "sluttiness": 1,
      "comfort": 10,
      "durability": 8,
      "style": "cute",
      "colors": ["grey"],
      "tags": ["great sleep", "sleep", "easy access dress", "one piece"],
      "emphasizes": ["legs"],
      "reveals": ["legs", "butt", "tummy"],
      "top": "pajama dress",
      "breasts": "pajama dress",
      "bottom": "pajama dress",
      "pussy": "pajama dress",
      "breast support": 0,
      "panties under": "no",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "jia lounge white t-shirt": toMap({
      "id": "jia lounge white t-shirt",
      "category": "lounge",
      "name": "white t-shirt",
      "flavor": "he wears short shorts, you wear... no shorts?",
      "description": "t-shirt and panties",
      "price": 45,
      "type": "loungewear",
      "sluttiness": 6,
      "comfort": 8,
      "durability": 5,
      "style": "cute",
      "colors": ["white"],
      "tags": ["sleep"],
      "emphasizes": ["butt"],
      "reveals": ["legs", "butt"],
      "top": "pajama dress",
      "breasts": "pajama dress",
      "bottom": "pajama dress",
      "pussy": "pajama dress",
      "breast support": 0,
      "panties under": "no",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    })
  }),
  "office": toMap({
    "jia office houndstooth skirt": toMap({
      "id": "jia office houndstooth skirt",
      "category": "office",
      "name": "houndstooth skirt",
      "flavor": "Putting a classic pattern on a club-length skirt makes it acceptable as officewear, right?",
      "description": "black blouse and houndstooth skirt",
      "price": 160,
      "type": "skirt and blouse",
      "sluttiness": 6,
      "comfort": 4,
      "durability": 6,
      "style": "sexy",
      "colors": ["black", "grey"],
      "tags": ["professional", "easy access skirt"],
      "emphasizes": ["butt"],
      "reveals": ["legs"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office", "stylin", "casual"]
    }),
    "jia office plaid dress": toMap({
      "id": "jia office plaid dress",
      "category": "office",
      "name": "plaid dress",
      "flavor": "Sheer and swishy to keep you cool and confident at work.",
      "description": "plaid dress",
      "price": 130,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 5,
      "durability": 5,
      "style": "cute",
      "colors": ["grey"],
      "tags": ["professional", "easy access dress", "one piece"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "jia office purple dress": toMap({
      "id": "jia office purple dress",
      "category": "office",
      "name": "purple dress",
      "flavors": [
        "Like, zoinks Scoobs! It's Daphne!",
        "Eye-catching and *just* restrained enough to fit into the dress code.",
        "Retro sexy!"
      ],
      "description": "purple dress",
      "price": 180,
      "type": "dress",
      "sluttiness": 7,
      "comfort": 7,
      "durability": 4,
      "style": "sexy",
      "colors": ["purple"],
      "tags": ["very professional", "easy access dress", "one piece", "short dress"],
      "emphasizes": ["asscheeks"],
      "reveals": ["legs", "asscheeks"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office", "stylin"]
    }),
    "jia office red dress": toMap({
      "id": "jia office red dress",
      "category": "office",
      "name": "red dress",
      "flavor": "This would be absolutely perfect for work.",
      "description": "red dress",
      "price": 120,
      "type": "dress",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 7,
      "style": "elegant",
      "colors": ["red"],
      "tags": ["professional", "easy access dress", "one piece", "short dress"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    })
  }),
  "stylin": toMap({
    "jia stylin green dress": toMap({
      "id": "jia stylin green dress",
      "category": "stylin",
      "name": "green dress",
      "flavor": "Red and green... feels like Christmas came early!",
      "description": "shiny green dress",
      "price": 350,
      "type": "dress",
      "sluttiness": 3,
      "comfort": 4,
      "durability": 9,
      "style": "elegant",
      "colors": ["green"],
      "tags": ["easy access dress", "one piece"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "jia stylin night out": toMap({
      "id": "jia stylin night out",
      "category": "stylin",
      "name": "night out",
      "flavor": "Wonder how many free drinks you'll get in this…",
      "description": "yellow jacket and green dress",
      "price": 150,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 6,
      "style": "sexy",
      "colors": ["green", "yellow"],
      "tags": ["easy access dress", "one piece"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "casual"]
    }),
    "jia stylin parisian": toMap({
      "id": "jia stylin parisian",
      "category": "stylin",
      "name": "parisian",
      "flavors": [
        "The perfect outfit for mastering the 'language of love' at home OR abroad.",
        "Mon Dieu! How chic.",
        "Je suis une jolie mademoiselle. Sophisticated and exotic."
      ],
      "description": "tan dress and a beret",
      "price": 220,
      "type": "dress",
      "sluttiness": 2,
      "comfort": 8,
      "durability": 6,
      "style": "elegant",
      "colors": ["brown"],
      "tags": ["easy access dress", "one piece"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "office", "casual"]
    })
  })
}));