window.GE.outfit_database = window.GE.outfit_database || new Map();

window.GE.outfit_database.set("lana", toMap({
  "purchasable": toMap({
    "beach": 5,
    "casual": 5,
    "fetish": 2,
    "lingerie": 4,
    "gym": 3,
    "lounge": 3,
    "office": 2,
    "stylin": 3
  }),
  "beach": toMap({
    "lana beach art deco one piece": toMap({
      "id": "lana beach art deco one piece",
      "category": "beach",
      "name": "art deco one piece",
      "flavor": "You're a piece of art yourself!",
      "description": "white and tan geometric one piece",
      "price": 60,
      "type": "one-piece swimsuit",
      "sluttiness": 2,
      "comfort": 7,
      "durability": 7,
      "style": "modest",
      "colors": ["white", "brown"],
      "tags": ["swim", "one piece"],
      "emphasizes": [],
      "reveals": ["legs", "butt"],
      "top": "one-piece swimsuit",
      "breasts": "one-piece swimsuit",
      "bottom": "one-piece swimsuit",
      "pussy": "one-piece swimsuit",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "lana beach black bikini": toMap({
      "id": "lana beach black bikini",
      "category": "beach",
      "name": "black bikini",
      "flavor": "For the classy girl at the pool party.",
      "description": "black bikini with touches of gold",
      "price": 70,
      "type": "bikini",
      "sluttiness": 4,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["swim"],
      "emphasizes": [],
      "reveals": ["legs", "butt", "tummy", "boobs"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "lana beach backless v thong": toMap({
      "id": "lana beach backless v thong",
      "category": "beach",
      "name": "backless v thong",
      "flavor": "The extreme high cut leaves nothing to the imagination.",
      "description": "orange backless v thong one piece swimsuit",
      "price": 150,
      "type": "one-piece swimsuit",
      "sluttiness": 9,
      "comfort": 4,
      "durability": 3,
      "style": "slutty",
      "colors": ["orange"],
      "tags": ["swim", "one piece"],
      "emphasizes": ["boobs", "butt"],
      "reveals": ["boobs", "butt", "tummy", "legs"],
      "top": "one piece swimsuit",
      "breasts": "one piece swimsuit",
      "bottom": "one piece swimsuit",
      "pussy": "one piece swimsuit",
      "breast support": 1,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "lana beach black one piece": toMap({
      "id": "lana beach black one piece",
      "category": "beach",
      "name": "black one piece",
      "flavor": "Shows quite a bit of boobage, for a one piece.",
      "description": "black one-piece swimsuit",
      "price": 55,
      "type": "one-piece swimsuit",
      "sluttiness": 4,
      "comfort": 3,
      "durability": 6,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["swim", "one piece"],
      "emphasizes": ["boobs"],
      "reveals": ["legs", "butt", "boobs"],
      "top": "one-piece swimsuit",
      "breasts": "one-piece swimsuit",
      "bottom": "one-piece swimsuit",
      "pussy": "one-piece swimsuit",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "lana beach blue bikini": toMap({
      "id": "lana beach blue bikini",
      "category": "beach",
      "name": "blue bikini",
      "flavor": "Held together with wishes and dreams… and bows!",
      "description": "lacy blue bikini",
      "price": 65,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 2,
      "style": "cute",
      "colors": ["blue"],
      "tags": ["swim"],
      "emphasizes": ["boobs"],
      "reveals": ["legs", "butt", "boobs", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "lana beach cheap pink bikini": toMap({
      "id": "lana beach cheap pink bikini",
      "category": "beach",
      "name": "cheap pink bikini",
      "flavor": "This cheap material feels like it could snap at any time.",
      "description": "pink bikini",
      "price": 25,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 4,
      "durability": 1,
      "style": "relaxed",
      "colors": ["pink"],
      "tags": ["swim"],
      "emphasizes": ["boobs"],
      "reveals": ["legs", "butt", "boobs", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "lana beach fishnet bikini": toMap({
      "id": "lana beach fishnet bikini",
      "category": "beach",
      "name": "fishnet bikini",
      "flavor": "And behold, I say unto you, I shall make you a fisher of men!",
      "description": "white fishnet bikini",
      "price": 95,
      "type": "bikini",
      "sluttiness": 10,
      "comfort": 4,
      "durability": 7,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["swim", "zipper", "transparent", "basically naked"],
      "emphasizes": ["nipples"],
      "reveals": ["legs", "butt", "boobs", "tummy", "nipples", "pussy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "lana beach green bikini": toMap({
      "id": "lana beach green bikini",
      "category": "beach",
      "name": "green bikini",
      "flavor": "This makes your ass look UH-MAZING!",
      "description": "green bikini",
      "price": 55,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["green"],
      "tags": ["swim"],
      "emphasizes": ["butt"],
      "reveals": ["legs", "butt", "boobs", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "lana beach lady of the lake": toMap({
      "id": "lana beach lady of the lake",
      "category": "beach",
      "name": "lady of the lake",
      "flavors": [
        "What the hell is this?",
        "What's the joke about strange women lying in ponds, distributing erections?",
        "Wow, can you imagine actually wearing this?",
        "You have to apply each piece to yourself with adhesive. God."
      ],
      "description": "adhesive gold pieces",
      "price": 1500,
      "type": "???",
      "sluttiness": 10,
      "comfort": 5,
      "durability": 4,
      "style": "elegant",
      "colors": ["yellow"],
      "tags": ["swim", "basically naked", "one piece", "peel pieces", "long changing"],
      "emphasizes": ["boobs"],
      "reveals": ["legs", "butt", "boobs", "tummy"],
      "top": "gold shell",
      "breasts": "gold shell",
      "bottom": "gold shell",
      "pussy": "gold shell",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach", "fetish"]
    }),
    "lana beach nautical": toMap({
      "id": "lana beach nautical",
      "category": "beach",
      "name": "nautical",
      "flavors": [
        "A good bikini to take on a cruise.",
        "Yo ho ho, a pirate's life for you!",
        "I've never been lost at sea, but I sure would like to be blown ashore!",
        "I'll put the wind in your sails if you raise my mast.",
        "Brandy, you're a fine girl, what a good wife you would be, but my life my love my lady, is the sea.",
        "You're the wench I'd like to wrap my sheet around...",
        "My ancestors must have been pirates because I'm going to plunder that booty.",
        "Are you a Sunfish? Because I’d like to find out how tight your cockpit is.",
        "I've seemed to misplaced my anchor, Can I tie up with you?",
        "Are we head-to-wind because I think I luff you.",
        "I must be hunting treasure cause I'm digging you."
      ],
      "description": "blue and white bikini",
      "price": 100,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 6,
      "style": "sexy",
      "colors": ["blue"],
      "tags": ["swim"],
      "emphasizes": ["sideboob"],
      "reveals": ["legs", "butt", "boobs", "tummy", "sideboob"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach"]
    }),
    "lana beach pink bikini": toMap({
      "id": "lana beach pink bikini",
      "category": "beach",
      "name": "pink bikini",
      "flavor": "Ready to hit the beach in style!",
      "description": "pink bikini with matching necklace",
      "price": 130,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 5,
      "durability": 7,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["swim"],
      "emphasizes": [],
      "reveals": ["legs", "butt", "boobs", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach"]
    }),
    "lana beach purple bikini": toMap({
      "id": "lana beach purple bikini",
      "category": "beach",
      "name": "purple bikini",
      "flavor": "It's quite small.",
      "description": "purple triangle bikini",
      "price": 110,
      "type": "bikini",
      "sluttiness": 7,
      "comfort": 4,
      "durability": 3,
      "style": "slutty",
      "colors": ["purple"],
      "tags": ["swim", "strings"],
      "emphasizes": ["boobs"],
      "reveals": ["legs", "butt", "boobs", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach"]
    }),
    "lana beach string bikini": toMap({
      "id": "lana beach string bikini",
      "category": "beach",
      "name": "string bikini",
      "flavors": [
        "The strings to the bottom go over your shoulders!",
        "A tag inside says 'size 420'... that can't be right!"
      ],
      "description": "vegetation themed bikini top and bottom",
      "price": 60,
      "type": "bikini",
      "sluttiness": 8,
      "comfort": 3,
      "durability": 2,
      "style": "slutty",
      "colors": ["blue", "green"],
      "tags": ["swim", "strings"],
      "emphasizes": ["boobs"],
      "reveals": ["legs", "butt", "boobs", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach"]
    }),
    "lana beach supergirl": toMap({
      "id": "lana beach supergirl",
      "category": "beach",
      "name": "supergirl",
      "flavor": "Geez, this is a lot of underboob.",
      "description": "red bikini top and blue bottom",
      "price": 75,
      "type": "bikini",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 2,
      "style": "slutty",
      "colors": ["red", "blue"],
      "tags": ["swim", "strings", "boobs fall out"],
      "emphasizes": ["underboob"],
      "reveals": ["legs", "butt", "boobs", "tummy", "underboob"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 2,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach"]
    }),
    "lana beach tiki": toMap({
      "id": "lana beach tiki",
      "category": "beach",
      "name": "tiki",
      "flavor": "Perfect for torchlit parties!",
      "description": "orange bikini top and bikini skirt",
      "price": 45,
      "type": "bikini",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 5,
      "style": "slutty",
      "colors": ["orange"],
      "tags": ["swim"],
      "emphasizes": [],
      "reveals": ["legs", "butt", "boobs", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini skirt",
      "pussy": "bikini skirt",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach"]
    }),
    "lana beach tropical one piece": toMap({
      "id": "lana beach tropical one piece",
      "category": "beach",
      "name": "tropical one piece",
      "flavor": "Perfect tropical vibes for Summer City!",
      "description": "blue one piece",
      "price": 75,
      "type": "one-piece swimsuit",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 6,
      "style": "cute",
      "colors": ["blue"],
      "tags": ["swim", "one piece"],
      "emphasizes": ["butt"],
      "reveals": ["legs", "butt", "boobs"],
      "top": "swimsuit",
      "breasts": "swimsuit",
      "bottom": "swimsuit",
      "pussy": "swimsuit",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach"]
    })
  }),
  "casual": toMap({
    "lana casual baby blue tank top": toMap({
      "id": "lana casual baby blue tank top",
      "category": "casual",
      "name": "baby blue tank top",
      "flavor": "It's pretty tight, and really shows off your curves.",
      "description": "tank top and jeans",
      "price": 55,
      "type": "casual",
      "sluttiness": 5,
      "comfort": 4,
      "durability": 4,
      "style": "sexy",
      "colors": ["blue"],
      "tags": [],
      "emphasizes": ["boobs"],
      "reveals": [],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "lana casual bikini top": toMap({
      "id": "lana casual bikini top",
      "category": "casual",
      "name": "bikini top",
      "flavor": "It's just a bikini top with some jean shorts.",
      "description": "bikini top and jean shorts",
      "price": 45,
      "type": "casual",
      "sluttiness": 7,
      "comfort": 3,
      "durability": 3,
      "style": "sexy",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "legs"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 4,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["casual", "lounge", "beach"]
    }),
    "lana casual blue sweatshirt": toMap({
      "id": "lana casual blue sweatshirt",
      "category": "casual",
      "name": "blue sweatshirt",
      "flavor": "Your butt really fills out these sweatpants.",
      "description": "blue sweatshirt and green sweatpants",
      "price": 45,
      "type": "casual",
      "sluttiness": 2,
      "comfort": 8,
      "durability": 5,
      "style": "relaxed",
      "colors": ["blue", "green"],
      "tags": [],
      "emphasizes": ["butt"],
      "reveals": [],
      "top": "sweatshirt",
      "breasts": "sweatshirt",
      "bottom": "sweatpants",
      "pussy": "sweatpants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "lana casual grey sweatpants": toMap({
      "id": "lana casual grey sweatpants",
      "category": "casual",
      "name": "grey sweatpants",
      "flavor": "You could take a nap in this, or go out.",
      "description": "tube top and grey Calvin Klein sweatpants",
      "price": 60,
      "type": "casual",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 5,
      "style": "relaxed",
      "colors": ["brown", "grey"],
      "tags": ["sleep"],
      "emphasizes": ["butt"],
      "reveals": ["tummy"],
      "top": "tube top",
      "breasts": "tube top",
      "bottom": "sweatpants",
      "pussy": "sweatpants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "lana casual high waisted jeans": toMap({
      "id": "lana casual high waisted jeans",
      "category": "casual",
      "name": "high waisted jeans",
      "flavor": "Goddamn, that ass. You're such a dump truck, even when you cover up!",
      "description": "purple sweater and jeans",
      "price": 70,
      "type": "casual",
      "sluttiness": 3,
      "comfort": 6,
      "durability": 7,
      "style": "casual",
      "colors": ["purple", "blue"],
      "tags": [],
      "emphasizes": ["butt"],
      "reveals": [],
      "top": "sweater",
      "breasts": "sweater",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "lana casual jean shorts": toMap({
      "id": "lana casual jean shorts",
      "category": "casual",
      "name": "jean shorts",
      "flavor": "Casual summer wear.",
      "description": "white tank top and jean shorts",
      "price": 50,
      "type": "casual",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 4,
      "style": "casual",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": ["cleavage", "asscheeks"],
      "reveals": ["asscheeks", "cleavage"],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "lana casual layerz": toMap({
      "id": "lana casual layerz",
      "category": "casual",
      "name": "layerz",
      "flavor": "How can you wear so many layers, and still look slutty?",
      "description": "white tank top, blue sweatshirt and jeans",
      "price": 90,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 8,
      "style": "sexy",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "sweatshirt",
      "breasts": "tank top",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "lana casual pineapple sundress": toMap({
      "id": "lana casual pineapple sundress",
      "category": "casual",
      "name": "pineapple sundress",
      "flavor": "Pineapples make the boys want to see your coconuts.",
      "description": "pink sundress with a fun pineapple pattern",
      "price": 70,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 5,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["easy access dress", "short dress", "one piece"],
      "emphasizes": ["legs"],
      "reveals": ["legs"],
      "top": "sundress",
      "breasts": "sundress",
      "bottom": "sundress",
      "pussy": "sundress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sandals",
      "locations": ["casual", "lounge", "stylin"]
    }),
    "lana casual red sweatpants": toMap({
      "id": "lana casual red sweatpants",
      "category": "casual",
      "name": "red sweatpants",
      "flavor": "These red sweats really hug your big hips.",
      "description": "red sweatpants and cherry graphic tee",
      "price": 60,
      "type": "casual",
      "sluttiness": 5,
      "comfort": 7,
      "durability": 4,
      "style": "sexy",
      "colors": ["white", "red"],
      "tags": ["workout"],
      "emphasizes": ["butt"],
      "reveals": ["tummy"],
      "top": "t-shirt",
      "breasts": "t-shirt",
      "bottom": "sweatpants",
      "pussy": "sweatpants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge", "gym"]
    }),
    "lana casual scrunchy pink crop top": toMap({
      "id": "lana casual scrunchy pink crop top",
      "category": "casual",
      "name": "scrunchy pink crop top",
      "flavor": "You feel like a cling-wrapped snack.",
      "description": "crop top and jeggings",
      "price": 70,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 3,
      "style": "cute",
      "colors": ["pink", "blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "jeggings",
      "pussy": "jeggings",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge", "stylin"]
    }),
    "lana casual daisy sundress": toMap({
      "id": "lana casual daisy sundress",
      "category": "casual",
      "name": "daisy sundress",
      "flavor": "They're gonna want to pollinate your flower.",
      "description": "sundress with daisy patterns",
      "price": 45,
      "type": "dress",
      "sluttiness": 7,
      "comfort": 7,
      "durability": 4,
      "style": "cute",
      "colors": ["yellow"],
      "tags": ["easy access dress", "short dress", "one piece"],
      "emphasizes": ["asscheeks"],
      "reveals": ["legs", "butt", "asscheeks"],
      "top": "sundress",
      "breasts": "sundress",
      "bottom": "sundress",
      "pussy": "sundress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge", "stylin"]
    }),
    "lana casual red sundress": toMap({
      "id": "lana casual red sundress",
      "category": "casual",
      "name": "red sundress",
      "flavor": "They're gonna want to pollinate your flower.",
      "description": "sundress with white floral patterns",
      "price": 50,
      "type": "dress",
      "sluttiness": 8,
      "comfort": 7,
      "durability": 3,
      "style": "cute",
      "colors": ["red"],
      "tags": ["easy access dress", "short dress", "one piece"],
      "emphasizes": ["asscheeks"],
      "reveals": ["legs", "butt", "asscheeks"],
      "top": "sundress",
      "breasts": "sundress",
      "bottom": "sundress",
      "pussy": "sundress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge", "stylin"]
    }),
    "lana casual stripey tank top": toMap({
      "id": "lana casual stripey tank top",
      "category": "casual",
      "name": "stripey tank top",
      "flavor": "Quite a normal, hum-drum outfit. But gets the job done.",
      "description": "tank top and jean shorts",
      "price": 35,
      "type": "casual",
      "sluttiness": 2,
      "comfort": 6,
      "durability": 4,
      "style": "relaxed",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "lana casual support your local fuckboy": toMap({
      "id": "lana casual support your local fuckboy",
      "category": "casual",
      "name": "support your local fuckboy",
      "flavor": "Have you lost all self-respect?",
      "description": "tank top and yoga pants",
      "price": 55,
      "type": "casual",
      "sluttiness": 9,
      "comfort": 7,
      "durability": 3,
      "style": "slutty",
      "colors": ["black", "white"],
      "tags": ["fuckboy magnet"],
      "emphasizes": ["butt"],
      "reveals": ["tummy"],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "lana casual teal yoga pants": toMap({
      "id": "lana casual teal yoga pants",
      "category": "casual",
      "name": "teal yoga pants",
      "flavor": "The skin-tight fabric enhances every jiggle of your phat ass.",
      "description": "crop top and tight sweatpants",
      "price": 60,
      "type": "casual",
      "sluttiness": 5,
      "comfort": 8,
      "durability": 4,
      "style": "sexy",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": ["butt"],
      "reveals": ["tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "sweatpants",
      "pussy": "sweatpants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge", "gym"]
    }),
    "lana casual thank you enjoy": toMap({
      "id": "lana casual thank you enjoy",
      "category": "casual",
      "name": "thank you enjoy",
      "flavor": "Good for take-out!",
      "description": "crop top and ripped jeans",
      "price": 40,
      "type": "casual",
      "sluttiness": 7,
      "comfort": 6,
      "durability": 2,
      "style": "sexy",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "lana casual white crop top": toMap({
      "id": "lana casual white crop top",
      "category": "casual",
      "name": "white crop top",
      "flavor": "Just add water.",
      "description": "crop top and jeans",
      "price": 50,
      "type": "casual",
      "sluttiness": 7,
      "comfort": 7,
      "durability": 4,
      "style": "sexy",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    })
  }),
  "fetish": toMap({
    "lana fetish a real catch": toMap({
      "id": "lana fetish a real catch",
      "category": "fetish",
      "name": "a real catch",
      "flavor": "Somehow, you feel MORE exposed than when you were just naked.",
      "description": "fishnet outfit",
      "price": 150,
      "type": "fetishwear",
      "sluttiness": 10,
      "comfort": 3,
      "durability": 2,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["waterproof", "basically naked", "transparent", "one piece", "swim"],
      "emphasizes": ["nipples", "pussy"],
      "reveals": ["boobs", "tummy", "legs", "ass", "pussy", "nipples"],
      "top": "fishnet outfit",
      "breasts": "fishnet outfit",
      "bottom": "fishnet outfit",
      "pussy": "fishnet outfit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish", "beach"]
    }),
    "lana fetish blue teddy": toMap({
      "id": "lana fetish blue teddy",
      "category": "fetish",
      "name": "blue teddy",
      "flavor": "Very cute powder blue lingerie.",
      "description": "blue lingerie",
      "price": 125,
      "type": "fetishwear",
      "sluttiness": 7,
      "comfort": 3,
      "durability": 5,
      "style": "sexy",
      "colors": ["blue"],
      "tags": ["one piece", "underwire"],
      "emphasizes": [],
      "reveals": ["boobs", "butt", "legs"],
      "top": "teddy",
      "breasts": "teddy",
      "bottom": "teddy",
      "pussy": "teddy",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish", "lingerie"]
    }),
    "lana fetish masquerade": toMap({
      "id": "lana fetish masquerade",
      "category": "fetish",
      "name": "masquerade",
      "flavor": "Eyes Wide Shut, Crotch Wide Open.",
      "description": "see-through mesh outfit and Venetian mask",
      "price": 190,
      "type": "fetishwear",
      "sluttiness": 10,
      "comfort": 4,
      "durability": 1,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["transparent", "full access", "one piece", "waterproof"],
      "emphasizes": ["pussy"],
      "reveals": ["cleavage", "asscheeks", "boobs", "butt", "tummy", "pussy"],
      "top": "lace outfit",
      "breasts": "lace outfit",
      "bottom": "lace outfit",
      "pussy": "lace outfit",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["fetish"]
    }),
    "lana fetish nympho": toMap({
      "id": "lana fetish nympho",
      "category": "fetish",
      "name": "nympho",
      "flavor": "For when you don't even feel like trying to pretend this body isn't made for sex.",
      "description": "fishnet top and rainbow short shorts",
      "price": 130,
      "type": "fetishwear",
      "sluttiness": 10,
      "comfort": 5,
      "durability": 3,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["semi-transparent", "collar"],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "nipples", "boobs", "legs", "butt"],
      "top": "fishnet crop top",
      "breasts": "fishnet crop top",
      "bottom": "rainbow shorts",
      "pussy": "rainbow shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["fetish"]
    })
  }),
  "gym": toMap({
    "lana gym apple bottom": toMap({
      "id": "lana gym apple bottom",
      "category": "gym",
      "name": "apple bottom",
      "flavor": "Let it wiggle while you walk.",
      "description": "red sports bra and bike shorts",
      "price": 120,
      "type": "fitness",
      "sluttiness": 7,
      "comfort": 6,
      "durability": 7,
      "style": "sexy",
      "colors": ["red"],
      "tags": ["workout"],
      "emphasizes": ["asscheeks"],
      "reveals": ["legs", "tummy", "asscheeks"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "bike shorts",
      "pussy": "bike shorts",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    }),
    "lana gym camo yoga pants": toMap({
      "id": "lana gym camo yoga pants",
      "category": "gym",
      "name": "camo yoga pants",
      "flavor": "Sure to help you blend in with your surroundings!",
      "description": "purple sports bra and camo-patterned yoga pants",
      "price": 140,
      "type": "fitness",
      "sluttiness": 6,
      "comfort": 8,
      "durability": 4,
      "style": "sexy",
      "colors": ["purple"],
      "tags": ["workout", "camo"],
      "emphasizes": ["butt"],
      "reveals": ["tummy"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "yoga pants",
      "pussy": "yoga pants",
      "breast support": 6,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    }),
    "lana gym cheetah": toMap({
      "id": "lana gym cheetah",
      "category": "gym",
      "name": "cheetah",
      "flavor": "This pussycat loves the thrill of the chase.",
      "description": "pink sports bralette and cheetah-patterned shorts",
      "price": 110,
      "type": "fitness",
      "sluttiness": 8,
      "comfort": 6,
      "durability": 3,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["workout"],
      "emphasizes": ["butt"],
      "reveals": ["tummy", "asscheeks"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 6,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    }),
    "lana gym fashion nova": toMap({
      "id": "lana gym fashion nova",
      "category": "gym",
      "name": "fashion nova",
      "flavor": "With all the looks your ass is gonna get, you should be charging this place for free advertising!",
      "description": "green shorts and tank top",
      "price": 90,
      "type": "fitness",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 4,
      "style": "sexy",
      "colors": ["white", "green"],
      "tags": ["workout"],
      "emphasizes": ["asscheeks"],
      "reveals": ["tummy", "asscheeks"],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    }),
    "lana gym camo sports bra": toMap({
      "id": "lana gym camo sports bra",
      "category": "gym",
      "name": "camo sports bra",
      "flavor": "Where'd you go? Shoot, I didn't see you there, with all that camo!",
      "description": "camo sports bra and grey shorts",
      "price": 70,
      "type": "fitness",
      "sluttiness": 5,
      "comfort": 8,
      "durability": 5,
      "style": "sexy",
      "colors": ["grey"],
      "tags": ["workout"],
      "emphasizes": [],
      "reveals": ["tummy", "asscheeks"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    }),
    "lana gym now you see me": toMap({
      "id": "lana gym now you see me",
      "category": "gym",
      "name": "now you see me",
      "flavors": [
        "Yoga wear for the budding exhibitionist.",
        "Ever read the Kata Sutra?"
      ],
      "description": "fishnet top and see-through yoga pants",
      "price": 65,
      "type": "fitness",
      "sluttiness": 10,
      "comfort": 7,
      "durability": 2,
      "style": "slutty",
      "colors": ["white", "blue"],
      "tags": ["workout", "transparent"],
      "emphasizes": ["nipples"],
      "reveals": ["tummy", "nipples", "boobs", "legs", "pussy", "butt"],
      "top": "fishnet top",
      "breasts": "fishnet top",
      "bottom": "yoga pants",
      "pussy": "yoga pants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["gym", "lounge"]
    }),
    "lana gym practical gym outfit": toMap({
      "id": "lana gym practical gym outfit",
      "category": "gym",
      "name": "practical gym outfit",
      "flavor": "The label says 'practical,' but the instant wedgie suggests otherwise…",
      "description": "sports bralette and 'shorts'",
      "price": 50,
      "type": "fitness",
      "sluttiness": 8,
      "comfort": 8,
      "durability": 4,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["great workout"],
      "emphasizes": ["cleavage", "butt"],
      "reveals": ["cleavage", "butt", "legs", "tummy"],
      "top": "sports bralette",
      "breasts": "sports bralette",
      "bottom": "sports shorts",
      "pussy": "sports shorts",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["gym", "lounge"]
    }),
    "lana gym stars and stripes": toMap({
      "id": "lana gym stars and stripes",
      "category": "gym",
      "name": "stars and stripes",
      "flavor": "Shake twice for America!",
      "description": "sports bra and panties thing",
      "price": 120,
      "type": "fitness",
      "sluttiness": 9,
      "comfort": 3,
      "durability": 2,
      "style": "slutty",
      "colors": ["red", "white", "blue"],
      "tags": ["workout"],
      "emphasizes": ["cleavage", "butt"],
      "reveals": ["cleavage", "butt", "legs", "tummy"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "sport panties",
      "pussy": "sport panties",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["gym", "lounge"]
    }),
    "lana gym teal running wear": toMap({
      "id": "lana gym teal running wear",
      "category": "gym",
      "name": "teal running wear",
      "flavor": "Getting tired of showing off your massive, dump truck of an ass?",
      "description": "sports crop top and matching bike shorts",
      "price": 180,
      "type": "fitness",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 8,
      "style": "sexy",
      "colors": ["green"],
      "tags": ["great workout"],
      "emphasizes": ["butt"],
      "reveals": ["tummy"],
      "top": "sports crop top",
      "breasts": "sports crop top",
      "bottom": "sport shorts",
      "pussy": "sport shorts",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    })
  }),
  "lingerie": toMap({
    "lana lingerie calvin klein lingerie": toMap({
      "id": "lana lingerie calvin klein lingerie",
      "category": "lingerie",
      "name": "calvin klein lingerie",
      "flavor": "As basic as lingerie gets, white on white.",
      "description": "simple bra and panties",
      "price": 30,
      "type": "lingerie",
      "sluttiness": 3,
      "comfort": 10,
      "durability": 4,
      "style": "casual",
      "colors": ["white"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "lana lingerie lacy white lingerie": toMap({
      "id": "lana lingerie lacy white lingerie",
      "category": "lingerie",
      "name": "lacy white lingerie",
      "flavor": "Sexy lacework and frills, a classic.",
      "description": "fancy bra and panties",
      "price": 120,
      "type": "lingerie",
      "sluttiness": 6,
      "comfort": 3,
      "durability": 6,
      "style": "elegant",
      "colors": ["white"],
      "tags": ["straps", "stockings"],
      "emphasizes": ["butt"],
      "reveals": ["tummy", "butt", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie", "fetish"]
    }),
    "lana lingerie not much to the imagination": toMap({
      "id": "lana lingerie not much to the imagination",
      "category": "lingerie",
      "name": "not much to the imagination",
      "flavors": [
        "Doesn't offer support. Or any coverage up top.",
        "You feel like a the manufacturer forgot a few crucial pieces of fabric!",
        "Shows literally everything except your actual pussy."
      ],
      "description": "cupless bra and panties",
      "price": 90,
      "type": "lingerie",
      "sluttiness": 9,
      "comfort": 5,
      "durability": 2,
      "style": "slutty",
      "colors": ["black"],
      "tags": [],
      "emphasizes": ["boobs", "nipples"],
      "reveals": ["boobs", "nipples", "butt", "legs", "tummy"],
      "top": "cupless bra",
      "breasts": "cupless bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "lana lingerie pink bodysuit": toMap({
      "id": "lana lingerie pink bodysuit",
      "category": "lingerie",
      "name": "pink bodysuit",
      "flavor": "Sugar, spice and everything nice…",
      "description": "pink bodysuit with black outlines",
      "price": 85,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 4,
      "durability": 6,
      "style": "cute",
      "colors": ["pink"],
      "tags": ["one piece"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "butt", "legs"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "lana lingerie princess jasmine": toMap({
      "id": "lana lingerie princess jasmine",
      "category": "lingerie",
      "name": "princess jasmine",
      "flavor": "Airy and swishy, feels like wearing a cloud!",
      "description": "fancy bra and panties",
      "price": 110,
      "type": "lingerie",
      "sluttiness": 5,
      "comfort": 5,
      "durability": 4,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["underwire"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "butt", "legs", "nipples", "tummy"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie", "fetish"]
    }),
    "lana lingerie red lingerie": toMap({
      "id": "lana lingerie red lingerie",
      "category": "lingerie",
      "name": "red lingerie",
      "flavor": "Red's a good color, it draws the eyes.",
      "description": "red bra and panties",
      "price": 40,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 5,
      "style": "sexy",
      "colors": ["red"],
      "tags": [],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "butt", "legs", "tummy"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "lana lingerie soft lingerie": toMap({
      "id": "lana lingerie soft lingerie",
      "category": "lingerie",
      "name": "soft lingerie",
      "flavor": "You look like a bond girl in this.",
      "description": "green bra and panties",
      "price": 65,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 10,
      "durability": 4,
      "style": "elegant",
      "colors": ["green"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy", "legs", "butt"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "lana lingerie sugar baby": toMap({
      "id": "lana lingerie sugar baby",
      "category": "lingerie",
      "name": "sugar baby",
      "flavor": "In this, you look like a million bucks. A night.",
      "description": "floral bra and panties",
      "price": 220,
      "type": "lingerie",
      "sluttiness": 5,
      "comfort": 4,
      "durability": 8,
      "style": "elegant",
      "colors": ["pink"],
      "tags": ["underwire"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 10,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "lana lingerie white lingerie": toMap({
      "id": "lana lingerie white lingerie",
      "category": "lingerie",
      "name": "white lingerie",
      "flavor": "Cute and lacy.",
      "description": "lacy white bra and panties",
      "price": 50,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 3,
      "style": "elegant",
      "colors": ["white"],
      "tags": ["clip"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "lana lingerie white ribbons": toMap({
      "id": "lana lingerie white ribbons",
      "category": "lingerie",
      "name": "white ribbons",
      "flavor": "A present, waiting to be unwrapped.",
      "description": "bra, panties, and tons of ribbons",
      "price": 110,
      "type": "lingerie",
      "sluttiness": 6,
      "comfort": 4,
      "durability": 6,
      "style": "elegant",
      "colors": ["white"],
      "tags": ["straps"],
      "emphasizes": ["butt"],
      "reveals": ["tummy", "cleavage", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    })
  }),
  "lounge": toMap({
    "lana lounge balinese beauty": toMap({
      "id": "lana lounge balinese beauty",
      "category": "lounge",
      "name": "balinese beauty",
      "flavor": "It's not your grandma's crochet!",
      "description": "knit bralette and beach shorts",
      "price": 45,
      "type": "loungewear",
      "sluttiness": 8,
      "comfort": 7,
      "durability": 4,
      "style": "sexy",
      "colors": ["pink", "white"],
      "tags": ["sleep", "semi-transparent bottom"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "legs"],
      "top": "bralette",
      "breasts": "bralette",
      "bottom": "knit shorts",
      "pussy": "knit shorts",
      "breast support": 5,
      "panties under": "can",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge", "beach"]
    }),
    "lana lounge fit for lounging": toMap({
      "id": "lana lounge fit for lounging",
      "category": "lounge",
      "name": "fit for lounging",
      "flavor": "It's a bit of a lazy look, to be honest…",
      "description": "cropped tanktop and blue shorts",
      "price": 35,
      "type": "loungewear",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 5,
      "style": "relaxed",
      "colors": ["white", "blue"],
      "tags": ["sleep"],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "cropped tanktop",
      "breasts": "cropped tanktop",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge", "gym", "casual"]
    }),
    "lana lounge gingerbread queen": toMap({
      "id": "lana lounge gingerbread queen",
      "category": "lounge",
      "name": "gingerbread queen",
      "flavors": [
        "Funky, something you might see in the 70s.",
        "The texture is like a velvet curtain.",
        "It's weird, but oozes 70s cool.",
        "You've got such great legs, that you're sure you can pull this off."
      ],
      "description": "velvet bodysuit",
      "price": 210,
      "type": "loungewear",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 9,
      "style": "elegant",
      "colors": ["brown"],
      "tags": ["sleep", "one piece"],
      "emphasizes": ["butt", "legs"],
      "reveals": ["butt", "legs", "cleavage"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge", "stylin", "fetish"]
    }),
    "lana lounge grey knit leggings": toMap({
      "id": "lana lounge grey knit leggings",
      "category": "lounge",
      "name": "grey knit leggings",
      "flavor": "Great for cold days - and butt selfies!",
      "description": "t-shirt and tight grey leggings",
      "price": 55,
      "type": "loungewear",
      "sluttiness": 3,
      "comfort": 10,
      "durability": 5,
      "style": "casual",
      "colors": ["white", "grey"],
      "tags": ["sleep"],
      "emphasizes": ["butt"],
      "reveals": [],
      "top": "t-shirt",
      "breasts": "t-shirt",
      "bottom": "leggings",
      "pussy": "leggings",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge", "casual"]
    }),
    "lana lounge red crop top": toMap({
      "id": "lana lounge red crop top",
      "category": "lounge",
      "name": "red crop top",
      "flavor": "Makes you look rebellious.",
      "description": "crop top and panties",
      "price": 40,
      "type": "loungewear",
      "sluttiness": 7,
      "comfort": 6,
      "durability": 4,
      "style": "sexy",
      "colors": ["red", "white"],
      "tags": ["sleep"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "legs", "tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "lana lounge white crop top": toMap({
      "id": "lana lounge white crop top",
      "category": "lounge",
      "name": "white crop top",
      "flavor": "A choker elevates this look a bit.",
      "description": "crop top and panties",
      "price": 55,
      "type": "loungewear",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 5,
      "style": "sexy",
      "colors": ["white", "blue"],
      "tags": ["sleep"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "legs", "tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "lana lounge white drawstring shirt": toMap({
      "id": "lana lounge white drawstring shirt",
      "category": "lounge",
      "name": "white drawstring shirt",
      "flavor": "It's a cute and beachy look.",
      "description": "crop top and panties",
      "price": 60,
      "type": "loungewear",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 6,
      "style": "cute",
      "colors": ["white", "yellow"],
      "tags": ["sleep"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "legs", "tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge", "beach"]
    })
  }),
  "office": toMap({
    "lana office buttondown workwear": toMap({
      "id": "lana office buttondown workwear",
      "category": "office",
      "name": "buttondown workwear",
      "flavor": "All business.",
      "description": "button blouse and khaki skirt",
      "price": 140,
      "type": "office",
      "sluttiness": 4,
      "comfort": 5,
      "durability": 8,
      "style": "professional",
      "colors": ["white", "brown"],
      "tags": ["professional", "easy access skirt"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "lana office golden silk blouse": toMap({
      "id": "lana office golden silk blouse",
      "category": "office",
      "name": "golden silk blouse",
      "flavor": "You get to decide how many buttons is enough.",
      "description": "blouse and short skirt",
      "price": 150,
      "type": "office",
      "sluttiness": 7,
      "comfort": 4,
      "durability": 6,
      "style": "sexy",
      "colors": ["brown", "black"],
      "tags": ["professional", "easy access skirt", "stockings"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "lana office minty": toMap({
      "id": "lana office minty",
      "category": "office",
      "name": "minty",
      "flavor": "Clean and fresh!",
      "description": "low-cut blouse and short skirt",
      "price": 160,
      "type": "office",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 7,
      "style": "sexy",
      "colors": ["green", "white"],
      "tags": ["professional", "easy access skirt"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "lana office striped": toMap({
      "id": "lana office striped",
      "category": "office",
      "name": "striped",
      "flavor": "Perfect for a sexy secretary!",
      "description": "off-shoulder tube top and skirt",
      "price": 140,
      "type": "office",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 5,
      "style": "sexy",
      "colors": ["red", "black"],
      "tags": ["professional", "easy access skirt", "stockings"],
      "emphasizes": [],
      "reveals": ["leags"],
      "top": "tube top",
      "breasts": "tube top",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "lana office tangerine": toMap({
      "id": "lana office tangerine",
      "category": "office",
      "name": "tangerine",
      "flavor": "This skirt is pretty short for the office. But they won't mind, right?",
      "description": "crop top and skirt",
      "price": 110,
      "type": "office",
      "sluttiness": 8,
      "comfort": 7,
      "durability": 5,
      "style": "slutty",
      "colors": ["orange", "white"],
      "tags": ["professional", "easy access skirt"],
      "emphasizes": ["asscheeks"],
      "reveals": ["tummy", "legs", "ass cheeks"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office", "stylin", "casual"]
    })
  }),
  "stylin": toMap({
    "lana stylin black flower dress": toMap({
      "id": "lana stylin black flower dress",
      "category": "stylin",
      "name": "black flower dress",
      "flavor": "Cute and elegant.",
      "description": "black dress",
      "price": 160,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 6,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["easy access dress", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "office"]
    }),
    "lana stylin black gala dress": toMap({
      "id": "lana stylin black gala dress",
      "category": "stylin",
      "name": "black gala dress",
      "flavor": "Beautiful formal dress, perfect for high-class outings.",
      "description": "black dress",
      "price": 450,
      "type": "dress",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 10,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["one piece"],
      "emphasizes": ["cleavage", "lots of cleavage"],
      "reveals": ["cleavage", "legs", "lots of cleavage"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "lana stylin high cut dress": toMap({
      "id": "lana stylin high cut dress",
      "category": "stylin",
      "name": "high cut dress",
      "flavor": "This makes you feel like a trophy wife just waiting to happen.",
      "description": "pink dress with flowers",
      "price": 200,
      "type": "dress",
      "sluttiness": 5,
      "comfort": 7,
      "durability": 7,
      "style": "elegant",
      "colors": ["pink"],
      "tags": ["one piece"],
      "emphasizes": ["legs"],
      "reveals": ["legs", "cleavage"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "lana stylin orange underboob dress": toMap({
      "id": "lana stylin orange underboob dress",
      "category": "stylin",
      "name": "orange underboob dress",
      "flavor": "Underboob windows… a clear mark of slutdom.",
      "description": "orange dress",
      "price": 180,
      "type": "dress",
      "sluttiness": 10,
      "comfort": 6,
      "durability": 7,
      "style": "slutty",
      "colors": ["orange"],
      "tags": ["one piece", "easy access dress"],
      "emphasizes": ["underboob"],
      "reveals": ["underboob", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "casual"]
    }),
    "lana stylin symmetry": toMap({
      "id": "lana stylin symmetry",
      "category": "stylin",
      "name": "symmetry",
      "flavor": "If you can't show skin, convince with curves.",
      "description": "black and white dress",
      "price": 240,
      "type": "dress",
      "sluttiness": 3,
      "comfort": 5,
      "durability": 9,
      "style": "modest",
      "colors": ["black", "white"],
      "tags": ["one piece", "professional"],
      "emphasizes": [],
      "reveals": [],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "office"]
    }),
    "lana stylin silvery sequins": toMap({
      "id": "lana stylin silvery sequins",
      "category": "stylin",
      "name": "silvery sequins",
      "flavor": "It honestly looks like an alpaca choking on aluminum foil. But I guess that's the price of fashion!",
      "description": "sparkly tpo and fluffy skirt",
      "price": 220,
      "type": "skirt and blouse",
      "sluttiness": 4,
      "comfort": 3,
      "durability": 6,
      "style": "elegant",
      "colors": ["grey", "white"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "sequin top",
      "breasts": "sequin top",
      "bottom": "fluffy skirt",
      "pussy": "fluffy skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["stylin"]
    }),
    "lana stylin mohican": toMap({
      "id": "lana stylin mohican",
      "category": "stylin",
      "name": "mohican",
      "flavor": "Something to wear at Woodstock.",
      "description": "handmade leather vest and jeans",
      "price": 160,
      "type": "stylish outfit",
      "sluttiness": 4,
      "comfort": 3,
      "durability": 6,
      "style": "sexy",
      "colors": ["black", "blue"],
      "tags": ["strings", "boobs fall out", "strings"],
      "emphasizes": ["lots of cleavage"],
      "reveals": ["lots of cleavage", "tummy"],
      "top": "handmade leather vest",
      "breasts": "handmade leather vest",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "moccasins",
      "locations": ["stylin", "casual"]
    }),
    "lana stylin cherry lemonade": toMap({
      "id": "lana stylin cherry lemonade",
      "category": "stylin",
      "name": "cherry lemonade",
      "flavor": "All the boys will in fact be brought to the yard. And they will be running.",
      "description": "cherry bralette and skirt thing",
      "price": 120,
      "type": "slutty outfit",
      "sluttiness": 10,
      "comfort": 2,
      "durability": 2,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["straps", "no obstruction", "stockings"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "asscheeks", "pussy"],
      "top": "bralette",
      "breasts": "bralette",
      "bottom": "miniskirt",
      "pussy": "miniskirt",
      "breast support": 5,
      "panties under": "can",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["stylin", "fetish"]
    }),
    "lana stylin burning man": toMap({
      "id": "lana stylin burning man",
      "category": "stylin",
      "name": "burning man",
      "flavor": "The weather may be hot, but you'll be hotter.",
      "description": "tan tanktop and red shorts",
      "price": 150,
      "type": "stylish outfit",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 7,
      "style": "sexy",
      "colors": ["brown", "red"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "tummy", "cleavage"],
      "top": "tanktop",
      "breasts": "tanktop",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sandals",
      "locations": ["stylin", "casual", "lounge"]
    })
  })
}));