window.GE.outfit_database = window.GE.outfit_database || new Map();

window.GE.outfit_database.set("liya", toMap({
  "purchasable": toMap({
    "beach": 5,
    "casual": 4,
    "fetish": 2,
    "lingerie": 5,
    "gym": 3,
    "lounge": 3,
    "office": 3,
    "stylin": 3
  }),
  "beach": toMap({
    "liya beach black front-zip one piece": toMap({
      "id": "liya beach black front-zip one piece",
      "category": "beach",
      "name": "black front-zip one piece",
      "flavor": "Gotta let these things breathe sometimes, ya know?",
      "description": "black one piece",
      "price": 75,
      "type": "one-piece swimsuit",
      "sluttiness": 4,
      "comfort": 5,
      "durability": 8,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["swim", "one piece", "zipper"],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "butt", "cleavage"],
      "top": "swimsuit",
      "breasts": "swimsuit",
      "bottom": "swimsuit",
      "pussy": "swimsuit",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach"]
    }),
    "liya beach red one piece": toMap({
      "id": "liya beach red one piece",
      "category": "beach",
      "name": "red one piece",
      "flavor": "Not the Baywatch you know.",
      "description": "red one-piece swimsuit",
      "price": 60,
      "type": "one-piece swimsuit",
      "sluttiness": 5,
      "comfort": 7,
      "durability": 6,
      "style": "elegant",
      "colors": ["red"],
      "tags": ["swim", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "butt", "cleavage"],
      "top": "swimsuit",
      "breasts": "swimsuit",
      "bottom": "swimsuit",
      "pussy": "swimsuit",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach"]
    }),
    "liya beach white one piece": toMap({
      "id": "liya beach white one piece",
      "category": "beach",
      "name": "white one piece",
      "flavor": "Shows quite a bit of boobage.",
      "description": "white one-piece swimsuit",
      "price": 65,
      "type": "one-piece swimsuit",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 3,
      "style": "sexy",
      "colors": ["white"],
      "tags": ["swim", "one piece"],
      "emphasizes": ["lots of cleavage", "cleavage"],
      "reveals": ["legs", "butt", "cleavage"],
      "top": "swimsuit",
      "breasts": "swimsuit",
      "bottom": "swimsuit",
      "pussy": "swimsuit",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach"]
    }),
    // This one appeared twice
    "liya beach black strap bikini": toMap({
      "id": "liya beach black strap bikini",
      "category": "beach",
      "name": "black strap bikini",
      "flavor": "Takes a while to put on, due to all these straps.",
      "description": "black bikini",
      "price": 75,
      "type": "bikini",
      "sluttiness": 7,
      "comfort": 3,
      "durability": 4,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["swim", "straps"],
      "emphasizes": ["sideboob"],
      "reveals": ["legs", "butt", "boobs", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottoms",
      "pussy": "bikini bottoms",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach"]
    }),
    // This one didn't appear
    "liya beach brown strapless bikini": toMap({
      "id": "liya beach brown strapless bikini",
      "category": "beach",
      "name": "brown strapless bikini",
      "flavor": "Simple covering of key areas for outdoor excursions.",
      "description": "strapless brown bikini top and bottom",
      "price": 80,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 2,
      "durability": 6,
      "style": "sexy",
      "colors": ["brown"],
      "tags": ["swim", "strapless"],
      "emphasizes": [],
      "reveals": ["legs", "butt", "boobs", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottoms",
      "pussy": "bikini bottoms",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach"]
    }),
    "liya beach cage bikini": toMap({
      "id": "liya beach cage bikini",
      "category": "beach",
      "name": "cage bikini",
      "flavor": "It's like shoelaces for your boobs.",
      "description": "cage-front bikini top and pink bottoms",
      "price": 110,
      "type": "bikini",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 2,
      "style": "elegant",
      "colors": ["brown"],
      "tags": ["swim", "strings", "boobs fall out"],
      "emphasizes": ["lots of cleavage"],
      "reveals": ["legs", "butt", "boobs", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottoms",
      "pussy": "bikini bottoms",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach", "lounge"]
    }),
    "liya beach lady of the lake": toMap({
      "id": "liya beach lady of the lake",
      "category": "beach",
      "name": "lady of the lake",
      "flavors": [
        "What the hell is this?",
        "What's the joke about strange women lying in ponds, distributing erections?",
        "Wow, can you imagine actually wearing this?",
        "You have to apply each piece to yourself with adhesive. God.",
        "As much work to put it on, as to peel it off."
      ],
      "description": "adhesive gold pieces",
      "price": 1500,
      "type": "???",
      "sluttiness": 10,
      "comfort": 5,
      "durability": 4,
      "style": "elegant",
      "colors": ["yellow"],
      "tags": ["swim", "basically naked", "one piece", "peel pieces", "long changing"],
      "emphasizes": ["boobs"],
      "reveals": ["legs", "butt", "boobs", "tummy"],
      "top": "gold shell",
      "breasts": "gold shell",
      "bottom": "gold shell",
      "pussy": "gold shell",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach", "fetish"]
    }),
    "liya beach nautical bikini": toMap({
      "id": "liya beach nautical bikini",
      "category": "beach",
      "name": "nautical bikini",
      "flavors": [
        "A good bikini to take on a cruise.",
        "Yo ho ho, a pirate's life for you!",
        "I've never been lost at sea, but I sure would like to be blown ashore!",
        "I'll put the wind in your sails if you raise my mast.",
        "Brandy, you're a fine girl, what a good wife you would be, but my life my love my lady, is the sea.",
        "You're the wench I'd like to wrap my sheet around...",
        "My ancestors must have been pirates because I'm going to plunder that booty.",
        "Are you a Sunfish? Because I’d like to find out how tight your cockpit is.",
        "I've seemed to misplaced my anchor, Can I tie up with you?",
        "Are we head-to-wind because I think I luff you.",
        "I must be hunting treasure cause I'm digging you.",
        "White thick-strapped bikini with some mesh windows, confident and sexual."
      ],
      "description": "striped white bikini",
      "price": 130,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 8,
      "style": "sexy",
      "colors": ["white", "brown"],
      "tags": ["swim"],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "butt", "boobs", "tummy", "sideboob"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "liya beach neon string bikini": toMap({
      "id": "liya beach neon string bikini",
      "category": "beach",
      "name": "neon string bikini",
      "flavor": "This really draws the eyes. The bikini is nice too!",
      "description": "neon yellow string bikini",
      "price": 90,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["yellow"],
      "tags": ["swim", "strings"],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "butt", "boobs", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottoms",
      "pussy": "bikini bottoms",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["beach"]
    }),
    "liya beach red bikini": toMap({
      "id": "liya beach red bikini",
      "category": "beach",
      "name": "red bikini",
      "flavor": "The bottoms are a little sparse in the fabric department.",
      "description": "red multiway string bikini",
      "price": 120,
      "type": "bikini",
      "sluttiness": 7,
      "comfort": 4,
      "durability": 3,
      "style": "slutty",
      "colors": ["red"],
      "tags": ["swim", "strings"],
      "emphasizes": ["sideboob"],
      "reveals": ["legs", "butt", "boobs", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottoms",
      "pussy": "bikini bottoms",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "liya beach red vixen bikini": toMap({
      "id": "liya beach red vixen bikini",
      "category": "beach",
      "name": "red vixen bikini",
      "flavor": "You're not sure about the brand, but the bikini offers great support.",
      "description": "red triangle bikini that says 'Vixen'",
      "price": 85,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 5,
      "style": "sexy",
      "colors": ["red"],
      "tags": ["swim"],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "butt", "boobs", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottoms",
      "pussy": "bikini bottoms",
      "breast support": 10,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "liya beach velour bikini": toMap({
      "id": "liya beach velour bikini",
      "category": "beach",
      "name": "velour bikini",
      "flavor": "It's made of a velvety material - is it really waterproof?",
      "description": "grey velvet top and white bikini bottoms",
      "price": 100,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 9,
      "durability": 4,
      "style": "sexy",
      "colors": ["grey", "white"],
      "tags": ["strings"],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "butt", "boobs", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottoms",
      "pussy": "bikini bottoms",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    // This one appeared twice
    "liya beach vixen bikini and jeans": toMap({
      "id": "liya beach vixen bikini and jeans",
      "category": "beach",
      "name": "vixen bikini and jeans",
      "flavor": "Keep things a bit more casual by wearing jeans over this bikini.",
      "description": "vixen bikini and jeans",
      "price": 140,
      "type": "casual beachwear",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 8,
      "style": "casual",
      "colors": ["black", "blue"],
      "tags": ["strings"],
      "emphasizes": ["cleavage"],
      "reveals": ["boobs", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "jeans",
      "pussy": "bikini bottoms",
      "breast support": 10,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach", "lounge", "casual"]
    }),
    "liya beach white string bikini": toMap({
      "id": "liya beach white string bikini",
      "category": "beach",
      "name": "white string bikini",
      "flavor": "The bow makes this really cute!",
      "description": "triangle bikini top and bikini bottoms with a bow",
      "price": 90,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 8,
      "durability": 5,
      "style": "cute",
      "colors": ["white"],
      "tags": ["strings"],
      "emphasizes": ["cleavage"],
      "reveals": ["boobs", "tummy", "legs", "butt"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottoms",
      "pussy": "bikini bottoms",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    })
  }),
  "casual": toMap({
    "liya casual abstract hoodie": toMap({
      "id": "liya casual abstract hoodie",
      "category": "casual",
      "name": "abstract hoodie",
      "flavor": "Big and comfy.",
      "description": "oversized hoodie and jeans",
      "price": 45,
      "type": "casual",
      "sluttiness": 1,
      "comfort": 10,
      "durability": 10,
      "style": "relaxed",
      "colors": ["blue"],
      "tags": ["masculine"],
      "emphasizes": [],
      "reveals": [],
      "top": "hoodie",
      "breasts": "hoodie",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "liya casual big comfy sweatshirt": toMap({
      "id": "liya casual big comfy sweatshirt",
      "category": "casual",
      "name": "big comfy sweatshirt",
      "flavor": "You're starting to understand why girls steal these from their boyfriends…",
      "description": "oversized sweatshirt",
      "price": 40,
      "type": "casual",
      "sluttiness": 3,
      "comfort": 10,
      "durability": 10,
      "style": "relaxed",
      "colors": ["grey"],
      "tags": ["easy access dress", "one piece"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "sweatshirt",
      "breasts": "sweatshirt",
      "bottom": "sweatshirt",
      "pussy": "sweatshirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "liya casual biker": toMap({
      "id": "liya casual biker",
      "category": "casual",
      "name": "biker",
      "flavor": "Still feeling masculine? No one said you have to wear a mini skirt and boob tube to be a girl. Go and hang out with the lads and have a laugh!",
      "description": "leather jacket and green canvas pants",
      "price": 125,
      "type": "casual",
      "sluttiness": 1,
      "comfort": 7,
      "durability": 10,
      "style": "relaxed",
      "colors": ["black", "blue", "green"],
      "tags": ["two layer top", "masculine"],
      "emphasizes": [],
      "reveals": [],
      "top": "leather jacket",
      "breasts": "hoodie",
      "bottom": "pants",
      "pussy": "pants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "boots",
      "locations": ["casual", "lounge"]
    }),
    "liya casual black crop top": toMap({
      "id": "liya casual black crop top",
      "category": "casual",
      "name": "black crop top",
      "flavor": "Black goes with everything!",
      "description": "black crop top and jean shorts",
      "price": 55,
      "type": "casual",
      "sluttiness": 5,
      "comfort": 5,
      "durability": 4,
      "style": "casual",
      "colors": ["black", "blue"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "legs"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "liya casual fishnet crop top": toMap({
      "id": "liya casual fishnet crop top",
      "category": "casual",
      "name": "fishnet crop top",
      "flavor": "The bra-top has built-in support!",
      "description": "white knit bralette and pink shorts",
      "price": 70,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 3,
      "style": "sexy",
      "colors": ["white", "pink"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "legs"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 5,
      "panties under": "can",
      "bra under": "no",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "liya casual little white dress": toMap({
      "id": "liya casual little white dress",
      "category": "casual",
      "name": "little white dress",
      "flavor": "It hugs your body in all the right places.",
      "description": "white dress",
      "price": 95,
      "type": "dress",
      "sluttiness": 5,
      "comfort": 7,
      "durability": 5,
      "style": "sexy",
      "colors": ["white"],
      "tags": ["one piece", "easy access dress", "short dress"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "liya casual pink hoodie": toMap({
      "id": "liya casual pink hoodie",
      "category": "casual",
      "name": "pink hoodie",
      "flavors": [
        "Cute, modest, and comfortable.",
        "Modest, but girly."
      ],
      "description": "oversized pink hoodie",
      "price": 55,
      "type": "casual",
      "sluttiness": 3,
      "comfort": 10,
      "durability": 8,
      "style": "cute",
      "colors": ["pink"],
      "tags": ["easy access dress", "one piece"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "hoodie",
      "breasts": "hoodie",
      "bottom": "hoodie",
      "pussy": "hoodie",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "liya casual red crop top": toMap({
      "id": "liya casual red crop top",
      "category": "casual",
      "name": "red crop top",
      "flavor": "An extremely versatile outfit.",
      "description": "red crop top and jean shorts",
      "price": 70,
      "type": "casual",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 6,
      "style": "sexy",
      "colors": ["red", "blue"],
      "tags": ["strings"],
      "emphasizes": [],
      "reveals": ["legs", "tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge", "stylin"]
    }),
    "liya casual tommy hilfiger": toMap({
      "id": "liya casual tommy hilfiger",
      "category": "casual",
      "name": "tommy hilfiger",
      "flavor": "A comfy and stylish hoodie.",
      "description": "hoodie and jeans",
      "price": 75,
      "type": "casual",
      "sluttiness": 2,
      "comfort": 9,
      "durability": 8,
      "style": "casual",
      "colors": ["white"],
      "tags": [],
      "emphasizes": [],
      "reveals": [],
      "top": "hoodie",
      "breasts": "hoodie",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "liya casual white crop top": toMap({
      "id": "liya casual white crop top",
      "category": "casual",
      "name": "white crop top",
      "flavor": "The outfit is nice enough, but no one's gonna notice it with all that underboob.",
      "description": "crop top and jean shorts",
      "price": 60,
      "type": "casual",
      "sluttiness": 8,
      "comfort": 6,
      "durability": 6,
      "style": "slutty",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": ["underboob"],
      "reveals": ["underboob", "tummy", "legs"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge", "stylin"]
    }),
    "liya casual white tank top": toMap({
      "id": "liya casual white tank top",
      "category": "casual",
      "name": "white tank top",
      "flavor": "A pretty casual outfit… except that it says 'dirty girl' on the front.",
      "description": "tank top and jean shorts",
      "price": 65,
      "type": "casual",
      "sluttiness": 7,
      "comfort": 7,
      "durability": 5,
      "style": "slutty",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "liya casual white t-shirt": toMap({
      "id": "liya casual white t-shirt",
      "category": "casual",
      "name": "white t-shirt",
      "flavor": "Chilling like its the eighties, some looks never age.",
      "description": "t-shirt and jean shorts",
      "price": 55,
      "type": "casual",
      "sluttiness": 3,
      "comfort": 9,
      "durability": 7,
      "style": "cute",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": ["asscheeks"],
      "reveals": ["tummy", "legs", "asscheeks"],
      "top": "t-shirt",
      "breasts": "t-shirt",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    })
  }),
  "fetish": toMap({
    "liya fetish bunny": toMap({
      "id": "liya fetish bunny",
      "category": "fetish",
      "name": "bunny",
      "flavor": "Shake that cottontail, girl!",
      "description": "leather bunny suit",
      "price": 250,
      "type": "fetishwear",
      "sluttiness": 8,
      "comfort": 4,
      "durability": 9,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["waterproof", "straps", "buckles", "one piece"],
      "emphasizes": ["butt"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "bunny suit",
      "breasts": "bunny suit",
      "bottom": "bunny suit",
      "pussy": "bunny suit",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["fetish"]
    }),
    "liya fetish caught mermaid": toMap({
      "id": "liya fetish caught mermaid",
      "category": "fetish",
      "name": "caught mermaid",
      "flavor": "You're the catch of the day!",
      "description": "fishnet bodysuit",
      "price": 140,
      "type": "fetishwear",
      "sluttiness": 10,
      "comfort": 2,
      "durability": 1,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["one piece", "transparent", "basically naked"],
      "emphasizes": ["nipples"],
      "reveals": ["nipples", "boobs", "tummy", "butt", "legs", "pussy"],
      "top": "fishnet bodysuit",
      "breasts": "fishnet bodysuit",
      "bottom": "fishnet bodysuit",
      "pussy": "fishnet bodysuit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish", "beach"]
    }),
    "liya fetish fishnet bodysuit": toMap({
      "id": "liya fetish fishnet bodysuit",
      "category": "fetish",
      "name": "fishnet bodysuit",
      "flavor": "You're the catch of the day!",
      "description": "fishnet bodysuit",
      "price": 110,
      "type": "fetishwear",
      "sluttiness": 9,
      "comfort": 2,
      "durability": 1,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["one piece", "transparent", "basically naked", "push aside"],
      "emphasizes": ["nipples"],
      "reveals": ["nipples", "boobs", "tummy", "butt", "legs"],
      "top": "fishnet bodysuit",
      "breasts": "fishnet bodysuit",
      "bottom": "fishnet bodysuit",
      "pussy": "fishnet bodysuit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish", "beach"]
    }),
    "liya fetish maid": toMap({
      "id": "liya fetish maid",
      "category": "fetish",
      "name": "maid",
      "flavor": "Mon dieu! Zat ees *not* a duster!",
      "description": "french maid outfit",
      "price": 130,
      "type": "dress",
      "sluttiness": 8,
      "comfort": 3,
      "durability": 7,
      "style": "slutty",
      "colors": ["white", "black"],
      "tags": ["chores", "one piece", "easy access dress"],
      "emphasizes": ["legs"],
      "reveals": ["legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["fetish", "lounge"]
    }),
    "liya fetish mon ami": toMap({
      "id": "liya fetish mon ami",
      "category": "fetish",
      "name": "mon ami",
      "flavor": "Why, French artists never wear underwear. This is what we mean by Liberté, just a strippy apron and a beret.",
      "description": "beret and an apron",
      "price": 80,
      "type": "fetishwear",
      "sluttiness": 7,
      "comfort": 4,
      "durability": 9,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "butt", "legs", "pussy"],
      "top": "apron",
      "breasts": "apron",
      "bottom": "apron",
      "pussy": "apron",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    }),
    "liya fetish high waisted": toMap({
      "id": "liya fetish high waisted",
      "category": "fetish",
      "name": "high waisted",
      "flavor": "A classic cut but with lace on those curves, this is suave and alluring.",
      "description": "set of lace-up fetishwear",
      "price": 95,
      "type": "fetishwear",
      "sluttiness": 8,
      "comfort": 3,
      "durability": 7,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["rich magnet"],
      "emphasizes": ["butt"],
      "reveals": ["cleavage", "butt", "legs", "tummy"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 10,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    })
  }),
  "gym": toMap({
    "liya gym sauna": toMap({
      "id": "liya gym sauna",
      "category": "gym",
      "name": "sauna",
      "flavor": "You'll sweat, one way or another.",
      "description": "colorful bikini top and bottom",
      "price": 110,
      "type": "fitness",
      "sluttiness": 7,
      "comfort": 6,
      "durability": 9,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["great workout", "waterproof", "swim"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "legs", "butt"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "sport panties",
      "pussy": "sport panties",
      "breast support": 10,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["gym", "beach"]
    }),
    "liya gym sports bra": toMap({
      "id": "liya gym sports bra",
      "category": "gym",
      "name": "sports bra",
      "flavor": "The supportive bra keeps your bazongas in a secure location while you exercise.",
      "description": "colorful sports bra and panties",
      "price": 70,
      "type": "fitness",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 6,
      "style": "sexy",
      "colors": ["green", "blue"],
      "tags": ["workout"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "legs", "butt"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "sport panties",
      "pussy": "sport panties",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["gym"]
    }),
    "liya gym white tennis skirt": toMap({
      "id": "liya gym white tennis skirt",
      "category": "gym",
      "name": "white tennis skirt",
      "flavor": "The supportive bra keeps your bazongas in a secure location while you exercise.",
      "description": "cropped sports top and tennis skirt",
      "price": 80,
      "type": "fitness",
      "sluttiness": 2,
      "comfort": 10,
      "durability": 5,
      "style": "cute",
      "colors": ["white", "pink"],
      "tags": ["great workout"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "legs"],
      "top": "sports top",
      "breasts": "sports top",
      "bottom": "tennis skirt",
      "pussy": "tennis skirt",
      "breast support": 7,
      "panties under": "can",
      "bra under": "no",
      "shoes": "none",
      "locations": ["gym"]
    })
  }),
  "lingerie": toMap({
    "liya lingerie black and white lingerie": toMap({
      "id": "liya lingerie black and white lingerie",
      "category": "lingerie",
      "name": "black and white lingerie",
      "flavor": "Goes with everything!",
      "description": "lacy bra and panties",
      "price": 70,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 5,
      "durability": 6,
      "style": "cute",
      "colors": ["white"],
      "tags": ["straps"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "liya lingerie black floral lingerie": toMap({
      "id": "liya lingerie black floral lingerie",
      "category": "lingerie",
      "name": "black floral lingerie",
      "flavor": "Those flowers will get polinated.",
      "description": "floral bra and panties",
      "price": 80,
      "type": "lingerie",
      "sluttiness": 6,
      "comfort": 4,
      "durability": 4,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["straps"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    // This shows up twice
    "liya lingerie black garter": toMap({
      "id": "liya lingerie black garter",
      "category": "lingerie",
      "name": "black garter",
      "flavor": "This makes you feel really sexy.",
      "description": "cropped bra top and panties",
      "price": 110,
      "type": "lingerie",
      "sluttiness": 7,
      "comfort": 3,
      "durability": 7,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["straps", "stockings"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "liya lingerie black mesh lingerie": toMap({
      "id": "liya lingerie black mesh lingerie",
      "category": "lingerie",
      "name": "black mesh lingerie",
      "flavor": "This makes you feel really sexy.",
      "description": "bra and high-waisted panties",
      "price": 80,
      "type": "lingerie",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 5,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["straps"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "butt", "legs", "pussy"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 9,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    // This shows up twice
    "liya lingerie black pushup lingerie": toMap({
      "id": "liya lingerie black pushup lingerie",
      "category": "lingerie",
      "name": "black pushup lingerie",
      "flavor": "As if your big boobs even needed a lift…",
      "description": "push-up bra and panties",
      "price": 90,
      "type": "lingerie",
      "sluttiness": 6,
      "comfort": 4,
      "durability": 7,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["straps", "stockings", "pushup"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 10,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "liya lingerie blue floral lingerie": toMap({
      "id": "liya lingerie blue floral lingerie",
      "category": "lingerie",
      "name": "blue floral lingerie",
      "flavor": "Something about this classy color combo really catches your eye.",
      "description": "flesh-toned bra and panties with blue floral lace",
      "price": 100,
      "type": "lingerie",
      "sluttiness": 5,
      "comfort": 8,
      "durability": 8,
      "style": "elegant",
      "colors": ["brown"],
      "tags": ["straps"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "liya lingerie burgundy balconette": toMap({
      "id": "liya lingerie burgundy balconette",
      "category": "lingerie",
      "name": "burgundy balconette",
      "flavor": "Not much coverage, but good support.",
      "description": "satin purple bra and panties",
      "price": 75,
      "type": "lingerie",
      "sluttiness": 8,
      "comfort": 3,
      "durability": 3,
      "style": "slutty",
      "colors": ["purple"],
      "tags": ["straps", "underwire"],
      "emphasizes": ["lots of cleavage"],
      "reveals": ["tummy", "cleavage", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "liya lingerie maid lingerie": toMap({
      "id": "liya lingerie maid lingerie",
      "category": "lingerie",
      "name": "maid lingerie",
      "flavor": "Wear this under your clothes to be a secret maid!",
      "description": "lacy bralette and panties",
      "price": 150,
      "type": "lingerie",
      "sluttiness": 10,
      "comfort": 8,
      "durability": 4,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["buttons", "chores"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie", "fetish", "lounge"]
    }),
    "liya lingerie white floral lingerie": toMap({
      "id": "liya lingerie white floral lingerie",
      "category": "lingerie",
      "name": "white floral lingerie",
      "flavor": "This one manages to offer support while still letting you flaunt those tits.",
      "description": "bra and panties",
      "price": 75,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 4,
      "style": "sexy",
      "colors": ["white"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 9,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "liya lingerie white lace lingerie": toMap({
      "id": "liya lingerie white lace lingerie",
      "category": "lingerie",
      "name": "white lace lingerie",
      "flavor": "Quite enticing.",
      "description": "bra and panties",
      "price": 60,
      "type": "lingerie",
      "sluttiness": 7,
      "comfort": 10,
      "durability": 4,
      "style": "sexy",
      "colors": ["white"],
      "tags": [],
      "emphasizes": ["boobs"],
      "reveals": ["tummy", "boobs", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "liya lingerie white bodysuit": toMap({
      "id": "liya lingerie white bodysuit",
      "category": "lingerie",
      "name": "white bodysuit",
      "flavor": "This bodysuit is fairly standard, with stripes and slight transparency.",
      "description": "bodysuit",
      "price": 80,
      "type": "lingerie",
      "sluttiness": 2,
      "comfort": 10,
      "durability": 9,
      "style": "sexy",
      "colors": ["white"],
      "tags": ["sleep"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie", "lounge"]
    }),
    "liya lingerie feathery white bodysuit": toMap({
      "id": "liya lingerie feathery white bodysuit",
      "category": "lingerie",
      "name": "feathery white bodysuit",
      "flavor": "You feel like some kind of sexy goose in this.",
      "description": "white bodysuit",
      "price": 50,
      "type": "lingerie",
      "sluttiness": 5,
      "comfort": 7,
      "durability": 6,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["sleep"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "butt", "legs"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie", "lounge"]
    })
  }),
  "lounge": toMap({
    "liya lounge black choker": toMap({
      "id": "liya lounge black choker",
      "category": "lounge",
      "name": "black choker",
      "flavors": [
        "A classy, relaxing look, but shows a lot of boobage.",
        "Choker? You've hardly even been 'er!",
        "This shows off the 'girls' nicely.",
        "Understated, but sure sexy as hell.",
        "Sure it looks like you forgot your skirt but its sleek and comfy."
      ],
      "description": "crop top and panties",
      "price": 75,
      "type": "loungewear",
      "sluttiness": 6,
      "comfort": 8,
      "durability": 4,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["sleep"],
      "emphasizes": ["lots of cleavage"],
      "reveals": ["butt", "legs", "tummy", "cleavage"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge", "beach"]
    }),
    "liya lounge button down": toMap({
      "id": "liya lounge button down",
      "category": "lounge",
      "name": "button down",
      "flavor": "Buttoning the shirt is optional!",
      "description": "button-down shirt and panties",
      "price": 40,
      "type": "loungewear",
      "sluttiness": 8,
      "comfort": 6,
      "durability": 7,
      "style": "sexy",
      "colors": ["white"],
      "tags": ["sleep"],
      "emphasizes": ["lots of cleavage"],
      "reveals": ["butt", "legs", "tummy", "cleavage"],
      "top": "button-down shirt",
      "breasts": "button-down shirt",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "liya lounge comfy white sweater": toMap({
      "id": "liya lounge comfy white sweater",
      "category": "lounge",
      "name": "comfy white sweater",
      "flavor": "Eternally adorable and sexy at the same time.",
      "description": "white oversized sweater",
      "price": 40,
      "type": "loungewear",
      "sluttiness": 3,
      "comfort": 10,
      "durability": 5,
      "style": "cute",
      "colors": ["white"],
      "tags": ["one piece"],
      "emphasizes": [],
      "reveals": ["legs", "cleavage"],
      "top": "sweater",
      "breasts": "sweater",
      "bottom": "sweater",
      "pussy": "sweater",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge", "casual"]
    }),
    "liya lounge literally a towel": toMap({
      "id": "liya lounge literally a towel",
      "category": "lounge",
      "name": "literally a towel",
      "flavor": "Not really an outfit.",
      "description": "towel",
      "price": 10,
      "type": "loungewear",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 3,
      "style": "relaxed",
      "colors": ["grey"],
      "tags": ["one piece", "boobs fall out"],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "cleavage"],
      "top": "towel",
      "breasts": "towel",
      "bottom": "towel",
      "pussy": "towel",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "liya lounge pink robe": toMap({
      "id": "liya lounge pink robe",
      "category": "lounge",
      "name": "pink robe",
      "flavor": "As a guy, you'd never wear paisley. But now..",
      "description": "pink robe",
      "price": 60,
      "type": "loungewear",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 2,
      "style": "elegant",
      "colors": ["pink"],
      "tags": ["one piece"],
      "emphasizes": ["asscheeks"],
      "reveals": ["legs", "asscheeks"],
      "top": "robe",
      "breasts": "robe",
      "bottom": "robe",
      "pussy": "robe",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "liya lounge red nightie": toMap({
      "id": "liya lounge red nightie",
      "category": "lounge",
      "name": "red nightie",
      "flavor": "Appropriate for a night in.",
      "description": "silk red nightie",
      "price": 20,
      "type": "loungewear",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 2,
      "style": "sexy",
      "colors": ["red"],
      "tags": ["one piece"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "nightie",
      "breasts": "nightie",
      "bottom": "nightie",
      "pussy": "nightie",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "liya lounge white tanktop": toMap({
      "id": "liya lounge white tanktop",
      "category": "lounge",
      "name": "white tanktop",
      "flavor": "Very relaxed.",
      "description": "long white tanktop",
      "price": 15,
      "type": "loungewear",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 4,
      "style": "relaxed",
      "colors": ["white"],
      "tags": ["one piece", "easy access dress"],
      "emphasizes": [],
      "reveals": ["legs", "cleavage"],
      "top": "long tank top",
      "breasts": "long tank top",
      "bottom": "long tank top",
      "pussy": "long tank top",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    })
  }),
  "office": toMap({
    "liya office black halter dress": toMap({
      "id": "liya office black halter dress",
      "category": "office",
      "name": "black halter dress",
      "flavors": [
        "Less a dress and more of a frame to show off boobs, plenty of leg action too.",
        "Hotter than your air conditioner allows.",
        "With a short skirt and your boobs bursting out of the top, you're sure to get some extra attention."
      ],
      "description": "black dress",
      "price": 150,
      "type": "office",
      "sluttiness": 7,
      "comfort": 6,
      "durability": 5,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["very professional", "easy access dress"],
      "emphasizes": ["lots of cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office", "stylin"]
    }),
    "liya office lavender sweater dress": toMap({
      "id": "liya office lavender sweater dress",
      "category": "office",
      "name": "lavender sweater dress",
      "flavors": [
        "Just because the 'virgin killer' trend is a few years old doesn't mean you can't still have fun with it.",
        "Might raise some eyebrows in the office. And some other things.",
        "A bold choice for the office, good luck avoiding wardrobe malfunctions."
      ],
      "description": "lavender virgin killer office dress",
      "price": 120,
      "type": "office",
      "sluttiness": 9,
      "comfort": 9,
      "durability": 3,
      "style": "slutty",
      "colors": ["pink"],
      "tags": ["professional", "easy access dress", "boobs fall out", "short dress"],
      "emphasizes": ["lots of cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office", "stylin", "lounge", "casual"]
    }),
    "liya office safari": toMap({
      "id": "liya office safari",
      "category": "office",
      "name": "safari",
      "flavors": [
        "Romper? You've hardly ever been 'er!",
        "For hunting big game (in the office).",
        "Watch out for predators!"
      ],
      "description": "tan romper",
      "price": 110,
      "type": "office",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 7,
      "style": "sexy",
      "colors": ["brown"],
      "tags": ["professional", "buttons"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "romper",
      "breasts": "romper",
      "bottom": "romper",
      "pussy": "romper",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["office", "stylin", "casual"]
    }),
    "liya office white office dress": toMap({
      "id": "liya office white office dress",
      "category": "office",
      "name": "white office dress",
      "flavors": [
        "White is for purity, right?",
        "Quite a glamorous look - sure to impress.",
        "Dress like you own the company, everyone will be eating out of your hand.",
        "Sexy, minimal, and elegant."
      ],
      "description": "white dress",
      "price": 250,
      "type": "office",
      "sluttiness": 3,
      "comfort": 6,
      "durability": 9,
      "style": "elegant",
      "colors": ["white"],
      "tags": ["very professional", "easy access dress"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office", "stylin"]
    }),
    "liya office sexy business": toMap({
      "id": "liya office sexy business",
      "category": "office",
      "name": "sexy business",
      "flavors": [
        "It's made from Italian wool, that's why it's so damn expensive.",
        "Pleasure doing buisness with you.",
        "Formal office wear, leaving just enough gaps to entice."
      ],
      "description": "blazer and suit pants",
      "price": 350,
      "type": "office",
      "sluttiness": 3,
      "comfort": 6,
      "durability": 10,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["very professional", "masculine"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "blazer",
      "breasts": "blazer",
      "bottom": "suit pants",
      "pussy": "suit pants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "liya office red tank top": toMap({
      "id": "liya office red tank top",
      "category": "office",
      "name": "red tank top",
      "flavor": "Great for casual Friday.",
      "description": "red tank top and jeans",
      "price": 80,
      "type": "office",
      "sluttiness": 4,
      "comfort": 9,
      "durability": 5,
      "style": "relaxed",
      "colors": ["red"],
      "tags": ["professional"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["office", "casual"]
    }),
    "liya office red skirt": toMap({
      "id": "liya office red skirt",
      "category": "office",
      "name": "red skirt",
      "flavor": "The profit curves arent the only ones being shown.",
      "description": "black blouse and red skirt",
      "price": 120,
      "type": "office",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 5,
      "style": "sexy",
      "colors": ["black", "red"],
      "tags": ["professional", "easy access skirt"],
      "emphasizes": ["legs"],
      "reveals": ["legs"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "liya office grey sport coat": toMap({
      "id": "liya office grey sport coat",
      "category": "office",
      "name": "grey sport coat",
      "flavor": "Sexy yet quite professional.",
      "description": "grey sport coat, blouse and skirt",
      "price": 190,
      "type": "office",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 8,
      "style": "elegant",
      "colors": ["grey", "black"],
      "tags": ["very professional", "easy access skirt", "two layer top"],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "cleavage"],
      "top": "sport coat",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "liya office business casual": toMap({
      "id": "liya office business casual",
      "category": "office",
      "name": "business casual",
      "flavor": "Low effort and it still looks good. What's not to like?",
      "description": "white tank top and grey skirt",
      "price": 60,
      "type": "office",
      "sluttiness": 3,
      "comfort": 8,
      "durability": 9,
      "style": "casual",
      "colors": ["white", "grey"],
      "tags": ["professional", "easy access skirt"],
      "emphasizes": [],
      "reveals": [],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    })
  }),
  "stylin": toMap({
    "liya stylin blue wrap dress": toMap({
      "id": "liya stylin blue wrap dress",
      "category": "stylin",
      "name": "blue wrap dress",
      "flavor": "Keep things under wraps.",
      "description": "blue wrap dress",
      "price": 190,
      "type": "dress",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 8,
      "style": "elegant",
      "colors": ["blue"],
      "tags": ["easy access dress", "one piece", "professional"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "office"]
    }),
    "liya stylin frilly black dress": toMap({
      "id": "liya stylin frilly black dress",
      "category": "stylin",
      "name": "frilly black dress",
      "flavor": "It really sparkles, and so do you!",
      "description": "black dress with sequins",
      "price": 300,
      "type": "dress",
      "sluttiness": 6,
      "comfort": 3,
      "durability": 9,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["easy access dress", "one piece"],
      "emphasizes": ["lots of cleavage"],
      "reveals": ["legs", "cleavage"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "liya stylin yellow dress": toMap({
      "id": "liya stylin yellow dress",
      "category": "stylin",
      "name": "yellow dress",
      "flavor": "Perfect for those dreamy summer days. ",
      "description": "wispy yellow dress",
      "price": 140,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 10,
      "durability": 4,
      "style": "cute",
      "colors": ["yellow"],
      "tags": ["one piece"],
      "emphasizes": [],
      "reveals": [],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sandals",
      "locations": ["stylin", "casual", "beach"]
    }),
    "liya stylin denim romper": toMap({
      "id": "liya stylin denim romper",
      "category": "stylin",
      "name": "denim romper",
      "flavor": "Not the usual material for a romper but that makes it stand out and that long, long zip is a tease.",
      "description": "front-zip denim romper",
      "price": 120,
      "type": "romper",
      "sluttiness": 5,
      "comfort": 4,
      "durability": 10,
      "style": "sexy",
      "colors": ["blue"],
      "tags": ["one piece", "zipper", "front zip"],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "cleavage"],
      "top": "romper",
      "breasts": "romper",
      "bottom": "romper",
      "pussy": "romper",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sandals",
      "locations": ["stylin", "casual", "lounge"]
    }),
    "liya stylin black mesh": toMap({
      "id": "liya stylin black mesh",
      "category": "stylin",
      "name": "black mesh",
      "flavor": "You better wear a bra with this… or not?",
      "description": "sheer top and leather skirt",
      "price": 180,
      "type": "skirt and blouse",
      "sluttiness": 9,
      "comfort": 5,
      "durability": 3,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["transparent", "needs bra", "stockings"],
      "emphasizes": ["nipples"],
      "reveals": ["boobs", "nipples"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "casual", "office"]
    }),
    "liya stylin zipper vest": toMap({
      "id": "liya stylin zipper vest",
      "category": "stylin",
      "name": "zipper vest",
      "flavor": "Funky and stylish zipper vest.",
      "description": "zipper vest and jeans",
      "price": 80,
      "type": "stylish outfit",
      "sluttiness": 5,
      "comfort": 4,
      "durability": 10,
      "style": "sexy",
      "colors": ["black", "blue"],
      "tags": ["zipper", "front zip"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "vest",
      "breasts": "vest",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["stylin", "casual", "office"]
    })
  })
}));