window.GE.outfit_database = window.GE.outfit_database || new Map();

window.GE.outfit_database.set("mia", toMap({
  "purchasable": toMap({
    "beach": 5,
    "casual": 4,
    "fetish": 2,
    "lingerie": 5,
    "gym": 6,
    "lounge": 2,
    "office": 3,
    "stylin": 3
  }),
  "beach": toMap({
    "mia beach beach dress": toMap({
      "id": "mia beach beach dress",
      "category": "beach",
      "name": "beach dress",
      "flavor": "A classy, dreamy look - but not for swimming.",
      "description": "billowy white dress",
      "price": 190,
      "type": "classy beachwear",
      "sluttiness": 2,
      "comfort": 10,
      "durability": 5,
      "style": "elegant",
      "colors": ["white"],
      "tags": ["strings", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "mia beach bedazzled lavender bikini": toMap({
      "id": "mia beach bedazzled lavender bikini",
      "category": "beach",
      "name": "bedazzled lavender bikini",
      "flavor": "If the color wasn't girly enough, it's covered in rhinestones.",
      "description": "sparkly lavender triangle bikini top and bottom",
      "price": 20,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["strings", "swim"],
      "emphasizes": ["sideboob"],
      "reveals": ["boobs", "tummy", "legs", "butt"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "mia beach black bandeau bikini": toMap({
      "id": "mia beach black bandeau bikini",
      "category": "beach",
      "name": "black bandeau bikini",
      "flavor": "Do you hate those pesky tan lines that can ruin your photos and stick out like a sore thumb when you’re wearing a tank top? You’re not alone! That’s where the bandeau bikini top swoops in to save the day.",
      "description": "black bandeau bikini top and bottom",
      "price": 60,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 5,
      "durability": 3,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["boobs fall out", "swim", "strapless"],
      "emphasizes": ["underboob"],
      "reveals": ["boobs", "tummy", "legs", "butt"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "mia beach black high-waisted bikini": toMap({
      "id": "mia beach black high-waisted bikini",
      "category": "beach",
      "name": "black high-waisted bikini",
      "flavor": "You'll pose for a fish-pic, but you definitely don't want to touch it.",
      "description": "black bikini top and bottom",
      "price": 45,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 4,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["strings", "swim"],
      "emphasizes": ["cleavage"],
      "reveals": ["boobs", "tummy", "legs", "butt"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "mia beach blue choker bikini": toMap({
      "id": "mia beach blue choker bikini",
      "category": "beach",
      "name": "blue choker bikini",
      "flavor": "Because who doesn't want to look like a submissive mermaid?",
      "description": "sparkly blue bikini top and bottom",
      "price": 65,
      "type": "bikini",
      "sluttiness": 8,
      "comfort": 3,
      "durability": 2,
      "style": "slutty",
      "colors": ["blue"],
      "tags": ["strings", "swim"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "legs", "butt"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 2,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "mia beach frilly pink bikini": toMap({
      "id": "mia beach frilly pink bikini",
      "category": "beach",
      "name": "frilly pink bikini",
      "flavor": "Cute but still screaming 'Fuck me!'",
      "description": "pink bikini top and bottom",
      "price": 50,
      "type": "bikini",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 5,
      "style": "cute",
      "colors": ["pink"],
      "tags": ["swim"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "legs", "butt"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "mia beach pink triangle bikini": toMap({
      "id": "mia beach pink triangle bikini",
      "category": "beach",
      "name": "pink triangle bikini",
      "flavor": "It doesn't fit you properly, though maybe that's the point…",
      "description": "pink bikini top and bottom",
      "price": 60,
      "type": "bikini",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 3,
      "style": "slutty",
      "colors": ["pink"],
      "tags": ["swim"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "legs", "butt"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "mia beach silky pink bikini": toMap({
      "id": "mia beach silky pink bikini",
      "category": "beach",
      "name": "silky pink bikini",
      "flavor": "You know anyone can see your nipples in this sheer bikini — do you find that exciting?",
      "description": "pink bikini top and bottom",
      "price": 60,
      "type": "bikini",
      "sluttiness": 10,
      "comfort": 4,
      "durability": 4,
      "style": "slutty",
      "colors": ["pink"],
      "tags": ["swim", "semi-transparent"],
      "emphasizes": ["nipples"],
      "reveals": ["nipples", "boobs", "tummy", "legs", "butt"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "mia beach striped pink bikini": toMap({
      "id": "mia beach striped pink bikini",
      "category": "beach",
      "name": "striped pink bikini",
      "flavor": "If you were a hot-pink candycane, you would wear this.",
      "description": "pink bikini top with striped bottom",
      "price": 70,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 8,
      "durability": 7,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["swim"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "legs", "butt"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "mia beach white floral bikini": toMap({
      "id": "mia beach white floral bikini",
      "category": "beach",
      "name": "white floral bikini",
      "flavor": "A floral pattern to go with your killer hourglass figure.",
      "description": "floral white bikini top and bottom",
      "price": 65,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 4,
      "style": "cute",
      "colors": ["white"],
      "tags": ["swim", "strings"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "legs", "butt"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "mia beach sunset yellow bikini": toMap({
      "id": "mia beach sunset yellow bikini",
      "category": "beach",
      "name": "yellow bikini",
      "flavor": "A bikini with a nice sunset-style gradient.",
      "description": "yellow bikini top and bottom",
      "price": 65,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 4,
      "style": "cute",
      "colors": ["white"],
      "tags": ["swim", "strings"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "legs", "butt"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "mia beach white one piece": toMap({
      "id": "mia beach white one piece",
      "category": "beach",
      "name": "white one piece",
      "flavor": "You're just one cannonball away from a wardrobe malfunction.",
      "description": "white one-piece swimsuit",
      "price": 70,
      "type": "one-piece swimsuit",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 7,
      "style": "sexy",
      "colors": ["white"],
      "tags": ["swim", "boobs fall out", "one piece"],
      "emphasizes": ["sideboob"],
      "reveals": ["boobs", "tummy", "legs", "butt"],
      "top": "swimsuit",
      "breasts": "swimsuit",
      "bottom": "swimsuit",
      "pussy": "swimsuit",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "mia beach underboob window": toMap({
      "id": "mia beach underboob window",
      "category": "beach",
      "name": "underboob window",
      "flavor": "It's a one piece, but it still shows cleavage and underboob. It's also hot pink. So all in all it's pretty slutty.",
      "description": "pink one piece",
      "price": 90,
      "type": "one-piece swimsuit",
      "sluttiness": 8,
      "comfort": 5,
      "durability": 8,
      "style": "slutty",
      "colors": ["pink"],
      "tags": ["swim", "one piece"],
      "emphasizes": ["underboob"],
      "reveals": ["boobs", "tummy", "legs", "butt"],
      "top": "swimsuit",
      "breasts": "swimsuit",
      "bottom": "swimsuit",
      "pussy": "swimsuit",
      "breast support": 2,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "mia beach black sleeved one piece": toMap({
      "id": "mia beach black sleeved one piece",
      "category": "beach",
      "name": "black sleeved one piece",
      "flavor": "You're probably doing a photo-shoot on a boat, but you know everything is see-through. Maybe you'll catch the big one?",
      "description": "black mesh one piece",
      "price": 110,
      "type": "one-piece swimsuit",
      "sluttiness": 10,
      "comfort": 4,
      "durability": 2,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["swim", "one piece", "semi-transparent"],
      "emphasizes": ["nipples"],
      "reveals": ["nipples", "boobs", "tummy", "legs", "butt"],
      "top": "swimsuit",
      "breasts": "swimsuit",
      "bottom": "swimsuit",
      "pussy": "swimsuit",
      "breast support": 2,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "mia beach black one piece": toMap({
      "id": "mia beach black one piece",
      "category": "beach",
      "name": "black one piece",
      "flavors": [
        "Nice and modest.",
        "The sensible choice."
      ],
      "description": "black one piece",
      "price": 45,
      "type": "one-piece swimsuit",
      "sluttiness": 1,
      "comfort": 8,
      "durability": 10,
      "style": "modest",
      "colors": ["black"],
      "tags": ["swim", "one piece"],
      "emphasizes": [],
      "reveals": ["legs", "butt"],
      "top": "swimsuit",
      "breasts": "swimsuit",
      "bottom": "swimsuit",
      "pussy": "swimsuit",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "mia beach pent up": toMap({
      "id": "mia beach pent up",
      "category": "beach",
      "name": "pent up",
      "flavor": "You're a thot, but a classy thot.",
      "description": "black crop top and bikini bottom",
      "price": 40,
      "type": "casual beachwear",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 3,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["boobs fall out"],
      "emphasizes": ["underboob"],
      "reveals": ["legs", "butt", "tummy", "underboob"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "mia beach sling bikini": toMap({
      "id": "mia beach sling bikini",
      "category": "beach",
      "name": "sling bikini",
      "flavor": "Wanna rock my hammock?",
      "description": "green sling top and fishnet bottoms",
      "price": 50,
      "type": "casual beachwear",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 4,
      "style": "sexy",
      "colors": ["green", "white"],
      "tags": ["boobs fall out", "semi-transparent"],
      "emphasizes": [],
      "reveals": ["tummy", "pussy"],
      "top": "sling top",
      "breasts": "sling top",
      "bottom": "fishnet pants",
      "pussy": "fishnet pants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    })
  }),
  "casual": toMap({
    "mia casual fuzzy lavender crop top": toMap({
      "id": "mia casual fuzzy lavender crop top",
      "category": "casual",
      "name": "fuzzy lavender crop top",
      "flavor": "Looks like you took a blanket and made it into a crop top and bottoms.",
      "description": "fluffy crop top and matching shorts",
      "price": 90,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 10,
      "durability": 3,
      "style": "cute",
      "colors": ["pink"],
      "tags": ["sleep"],
      "emphasizes": [],
      "reveals": ["legs", "tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "mia casual jeans and tank top": toMap({
      "id": "mia casual jeans and tank top",
      "category": "casual",
      "name": "jeans and tank top",
      "flavor": "For when you just need to relax but you gotta show a little cleavage.",
      "description": "tank top and jeans",
      "price": 70,
      "type": "casual",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 8,
      "style": "relaxed",
      "colors": ["blue"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy"],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "mia casual pink bralette": toMap({
      "id": "mia casual pink bralette",
      "category": "casual",
      "name": "pink bralette",
      "flavor": "You're really trying to embrace your inner blonde bimbo, huh?",
      "description": "bralette and jean shorts",
      "price": 50,
      "type": "casual",
      "sluttiness": 7,
      "comfort": 7,
      "durability": 3,
      "style": "sexy",
      "colors": ["pink", "blue"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "legs", "asscheeks"],
      "top": "bralette",
      "breasts": "bralette",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 4,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "mia casual short white dress": toMap({
      "id": "mia casual short white dress",
      "category": "casual",
      "name": "short white dress",
      "flavor": "Don't bend over, or you're liable to fall out at both ends!",
      "description": "dress",
      "price": 45,
      "type": "casual",
      "sluttiness": 8,
      "comfort": 7,
      "durability": 4,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["short dress", "not serious", "easy access dress", "one piece", "boobs fall out"],
      "emphasizes": ["lots of cleavage"],
      "reveals": ["cleavage", "legs", "asscheeks"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "wedges",
      "locations": ["casual", "lounge", "office", "stylin"]
    }),
    "mia casual striped crop top": toMap({
      "id": "mia casual striped crop top",
      "category": "casual",
      "name": "striped crop top",
      "flavor": "For when you want to be comfy, but still turn a few heads.",
      "description": "crop top and jeans",
      "price": 60,
      "type": "casual",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 6,
      "style": "casual",
      "colors": ["white"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "mia casual tube top and cargo pants": toMap({
      "id": "mia casual tube top and cargo pants",
      "category": "casual",
      "name": "tube top and cargo pants",
      "flavor": "You look like Lara Croft, just way softer and more like a bimbo.",
      "description": "tube top and khaki cargo pants",
      "price": 90,
      "type": "casual",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 7,
      "style": "casual",
      "colors": ["blue", "brown"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "tube top",
      "breasts": "tube top",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "mia casual cap-sleeve bralette": toMap({
      "id": "mia casual cap-sleeve bralette",
      "category": "casual",
      "name": "cap-sleeve bralette",
      "flavor": "Honestly, it's a *stretch* to even call this a top.",
      "description": "cap-sleeve bralette and jean shorts",
      "price": 90,
      "type": "casual",
      "sluttiness": 8,
      "comfort": 5,
      "durability": 1,
      "style": "slutty",
      "colors": ["white", "blue"],
      "tags": ["boobs fall out"],
      "emphasizes": ["lots of cleavage"],
      "reveals": ["cleavage", "tummy", "legs"],
      "top": "cap-sleeve bralette",
      "breasts": "cap-sleeve bralette",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge", "stylin"]
    }),
    "mia casual white cami": toMap({
      "id": "mia casual white cami",
      "category": "casual",
      "name": "white cami",
      "flavor": "Cute for those hot summer days!",
      "description": "white camie and distressed shorts",
      "price": 110,
      "type": "casual",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 4,
      "style": "cute",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy", "legs"],
      "top": "cami",
      "breasts": "cami",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    })
  }),
  "fetish": toMap({
    "mia fetish black leather goddess": toMap({
      "id": "mia fetish black leather goddess",
      "category": "fetish",
      "name": "black leather goddess",
      "flavors": [
        "You know something naughty is going to happen if you're wearing this piece.",
        "Nice pick there, mistress.",
        "You look quite expensive in this."
      ],
      "description": "leather bra and panties, with gloves",
      "price": 130,
      "type": "fetishwear",
      "sluttiness": 8,
      "comfort": 3,
      "durability": 8,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["rich magnet", "straps"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "butt", "legs", "tummy"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 10,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    }),
    "mia fetish happy birthday": toMap({
      "id": "mia fetish happy birthday",
      "category": "fetish",
      "name": "happy birthday",
      "flavors": [
        "Is it your birthday or theirs? You look more like a present after all…",
        "Yes, we all know *you're* the birthday present.",
        "They say the best part of getting a birthday present is unwrapping it..."
      ],
      "description": "ribbon bra and panties",
      "price": 50,
      "type": "fetishwear",
      "sluttiness": 9,
      "comfort": 3,
      "durability": 2,
      "style": "slutty",
      "colors": ["red"],
      "tags": ["untie", "straps"],
      "emphasizes": ["underboob"],
      "reveals": ["boobs", "butt", "legs", "tummy"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    }),
    "mia fetish nurse": toMap({
      "id": "mia fetish nurse",
      "category": "fetish",
      "name": "nurse",
      "flavors": [
        "Well HELLLOOOOOOO NURSE!",
        "You'll do anything to make them feel better!"
      ],
      "description": "nipple tape, panties, and a nurse cap",
      "price": 15,
      "type": "fetishwear",
      "sluttiness": 10,
      "comfort": 2,
      "durability": 1,
      "style": "slutty",
      "colors": ["red"],
      "tags": ["peel", "hat"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "butt", "legs", "tummy"],
      "top": "nipple tape",
      "breasts": "nipple tape",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    }),
    "mia fetish red collar": toMap({
      "id": "mia fetish red collar",
      "category": "fetish",
      "name": "red collar",
      "flavor": "For when slutty red stockings & brassiere aren’t enough and you really need a collar.",
      "description": "nipple tape, panties, and a nurse cap",
      "price": 200,
      "type": "fetishwear",
      "sluttiness": 10,
      "comfort": 4,
      "durability": 7,
      "style": "elegant",
      "colors": ["red"],
      "tags": ["collar", "stockings"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "butt", "legs", "tummy"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    })
  }),
  "gym": toMap({
    "mia gym home run": toMap({
      "id": "mia gym home run",
      "category": "gym",
      "name": "home run",
      "flavors": [
        "Shows all the guys that you knock it out of the park.",
        "Go Sports Team!",
        "You decide which base he gets to.",
        "You'll be a shoe-in for MVP - most voluptuous player!",
        "In this, all you'd have to do to get the ump on your side is to get on your knees..."
      ],
      "description": "sports top and shorts",
      "price": 90,
      "type": "fitness",
      "sluttiness": 3,
      "comfort": 8,
      "durability": 7,
      "style": "cute",
      "colors": ["grey", "blue"],
      "tags": ["workout", "buckle", "thigh socks", "jock magnet"],
      "emphasizes": [],
      "reveals": ["legs", "asscheeks"],
      "top": "sports top",
      "breasts": "sports top",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["gym"]
    }),
    "mia gym pink running outfit": toMap({
      "id": "mia gym pink running outfit",
      "category": "gym",
      "name": "pink running outfit",
      "flavors": [
        "It's really not even worth calling this a sweater... The zipper is 2 inches long.",
        "The pseudo sports-bra top doesn't offer much support, you'll be bouncing everywhere.",
        "You may attract extra attention if you're out running in this."
      ],
      "description": "sports top and shorts",
      "price": 135,
      "type": "fitness",
      "sluttiness": 9,
      "comfort": 8,
      "durability": 7,
      "style": "slutty",
      "colors": ["pink"],
      "tags": ["great workout", "boobs fall out", "gym scene"],
      "emphasizes": ["lots of cleavage"],
      "reveals": ["cleavage", "tummy", "legs", "asscheeks"],
      "top": "sports top",
      "breasts": "sports top",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 2,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge"]
    }),
    "mia gym pink yoga": toMap({
      "id": "mia gym pink yoga",
      "category": "gym",
      "name": "pink yoga",
      "flavor": "You look like a trophy wife.",
      "description": "sports bra and yoga pants",
      "price": 150,
      "type": "fitness",
      "sluttiness": 2,
      "comfort": 9,
      "durability": 5,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["workout"],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "yoga pants",
      "pussy": "yoga pants",
      "breast support": 7,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge", "casual"]
    }),
    "mia gym shermer phys ed": toMap({
      "id": "mia gym shermer phys ed",
      "category": "gym",
      "name": "shermer phys ed",
      "flavors": [
        "Are you the PE teacher? Student? Who cares. You're hot.",
        "You don't actually know what Shermer Phys Ed is, is it just one of those pointless brand things?",
        "Let's get physical!",
        "Brings you back to your highschool days... maybe your old gym teacher can help you relive them in a new way?"
      ],
      "description": "sports bra and bottom",
      "price": 90,
      "type": "fitness",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 6,
      "style": "sexy",
      "colors": ["grey", "blue"],
      "tags": ["workout", "not serious"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "sports bottom",
      "pussy": "sports bottom",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym"]
    }),
    "mia gym yoga outfit": toMap({
      "id": "mia gym yoga outfit",
      "category": "gym",
      "name": "yoga outfit",
      "flavors": [
        "It's so form-fitting you know everyone will have their eyes glued to you at the gym.",
        "Normally you'd be ogling the other girls dressed in something like this. Guess you'll be ogled now instead.",
        "How tight can these pants be? Tight enough!",
        "For some reason the guys always make you take a mat at the front. Weird."
      ],
      "description": "Sports bra and yoga pants",
      "price": 110,
      "type": "fitness",
      "sluttiness": 2,
      "comfort": 8,
      "durability": 8,
      "style": "casual",
      "colors": ["black"],
      "tags": ["workout"],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "yoga pants",
      "pussy": "yoga pants",
      "breast support": 10,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "casual", "lounge"]
    }),
    "mia gym yoga shorts": toMap({
      "id": "mia gym yoga shorts",
      "category": "gym",
      "name": "yoga shorts",
      "flavor": "Form-fitting and comfortable!",
      "description": "Sports bra and yoga shorts",
      "price": 100,
      "type": "fitness",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 7,
      "style": "casual",
      "colors": ["white"],
      "tags": ["workout"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "yoga shorts",
      "pussy": "yoga shorts",
      "breast support": 6,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "casual", "lounge"]
    })
  }),
  "lingerie": toMap({
    "mia lingerie black and pink multiway lingerie": toMap({
      "id": "mia lingerie black and pink multiway lingerie",
      "category": "lingerie",
      "name": "black and pink multiway lingerie",
      "flavor": "The effort it takes to put this beautiful piece on will prove how much you like the person who gets to take it off!",
      "description": "black and pink multiway bra and panties",
      "price": 75,
      "type": "lingerie",
      "sluttiness": 6,
      "comfort": 3,
      "durability": 7,
      "style": "elegant",
      "colors": ["black", "pink"],
      "tags": ["stockings"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "mia lingerie black and white lingerie": toMap({
      "id": "mia lingerie black and white lingerie",
      "category": "lingerie",
      "name": "black and white lingerie",
      "flavor": "This bra offers a lot of support but really smushes your boobs against your chest.",
      "description": "white and black sports bra and panties",
      "price": 45,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 3,
      "durability": 8,
      "style": "casual",
      "colors": ["white", "black"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 10,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "mia lingerie black garter": toMap({
      "id": "mia lingerie black garter",
      "category": "lingerie",
      "name": "black garter",
      "flavor": "You put your hand on your hip like you can play coy when wearing this hot outfit.",
      "description": "lacy black lingerie with stockings",
      "price": 65,
      "type": "lingerie",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 6,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["stockings"],
      "emphasizes": ["lots of cleavage"],
      "reveals": ["boobs", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "mia lingerie blue demi bra": toMap({
      "id": "mia lingerie blue demi bra",
      "category": "lingerie",
      "name": "blue demi bra",
      "flavors": [
        "You're not fooling anyone if they make it far enough to see you wear this.",
        "Kinda screams 'Roaring 20s.'",
        "Are you a sweet and innocent girl?"
      ],
      "description": "lacy blue high-waisted panties and demi bra",
      "price": 60,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 4,
      "style": "cute",
      "colors": ["blue"],
      "tags": [],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "mia lingerie comfy pink lingerie": toMap({
      "id": "mia lingerie comfy pink lingerie",
      "category": "lingerie",
      "name": "comfy pink lingerie",
      "flavor": "You may be a Barbie girl, but are you in a Barbie world?",
      "description": "soft pink bra and panties",
      "price": 40,
      "type": "lingerie",
      "sluttiness": 3,
      "comfort": 10,
      "durability": 2,
      "style": "cute",
      "colors": ["pink"],
      "tags": ["sleep"],
      "emphasizes": [],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "mia lingerie multiway lingerie": toMap({
      "id": "mia lingerie multiway lingerie",
      "category": "lingerie",
      "name": "multiway lingerie",
      "flavor": "Juuuuust opaque enough to leave some mystery regarding your areolas.",
      "description": "pink multiway bra and panties",
      "price": 55,
      "type": "lingerie",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 6,
      "style": "sexy",
      "colors": ["pink"],
      "tags": [],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "mia lingerie purple lingerie": toMap({
      "id": "mia lingerie purple lingerie",
      "category": "lingerie",
      "name": "purple lingerie",
      "flavors": [
        "Purple goes quite well with your complexion.",
        "The cheap workhorse of lingerie sets."
      ],
      "description": "purple lace bra and panties",
      "price": 30,
      "type": "lingerie",
      "sluttiness": 3,
      "comfort": 8,
      "durability": 4,
      "style": "casual",
      "colors": ["purple"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["boobs", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "mia lingerie red lingerie": toMap({
      "id": "mia lingerie red lingerie",
      "category": "lingerie",
      "name": "red lingerie",
      "flavor": "A nice push-up bra with some fancy details.",
      "description": "red push-up bra and panties",
      "price": 110,
      "type": "lingerie",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 8,
      "style": "elegant",
      "colors": ["red"],
      "tags": ["push-up"],
      "emphasizes": ["cleavage"],
      "reveals": ["boobs", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 9,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "mia lingerie showy lingerie": toMap({
      "id": "mia lingerie showy lingerie",
      "category": "lingerie",
      "name": "showy lingerie",
      "flavors": [
        "What exactly is the point of this?",
        "I think you're wearing it wrong.",
        "You gotta be putting that on wrong, this can't be what the manufacturer intended.",
        "At this point they’re just straps.",
        "Peekabo for grown-ups.",
        "If you wear anything on top your nipples will poke out, but your goal is definitely to take off whatever you're wearing when you have this underneath."
      ],
      "description": "pink multiway bra and panties, without cups",
      "price": 55,
      "type": "lingerie",
      "sluttiness": 10,
      "comfort": 7,
      "durability": 5,
      "style": "slutty",
      "colors": ["pink"],
      "tags": ["basically naked"],
      "emphasizes": ["nipples"],
      "reveals": ["boobs", "tummy", "butt", "legs", "nipples"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "mia lingerie white garter": toMap({
      "id": "mia lingerie white garter",
      "category": "lingerie",
      "name": "white garter",
      "flavors": [
        "Classy!",
        "It's white, it's lacy, and you know it's sexy."
      ],
      "description": "white underwire bra and panties, with garter",
      "price": 90,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 5,
      "durability": 9,
      "style": "elegant",
      "colors": ["white"],
      "tags": ["stockings", "underwire"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 10,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "mia lingerie pink bodysuit": toMap({
      "id": "mia lingerie pink bodysuit",
      "category": "lingerie",
      "name": "pink bodysuit",
      "flavor": "You're wearing a pink mesh onesie. How do *you* think it looks?",
      "description": "pink bodysuit",
      "price": 75,
      "type": "lingerie",
      "sluttiness": 7,
      "comfort": 2,
      "durability": 9,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["one piece", "bodysuit", "underwire"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "butt", "legs"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "mia lingerie black bodysuit": toMap({
      "id": "mia lingerie black bodysuit",
      "category": "lingerie",
      "name": "black bodysuit",
      "flavors": [
        "It's relatively tame given you're mostly just showing some cleavage and legs...",
        "Comfy and form fitting in all the right places."
      ],
      "description": "pink bodysuit",
      "price": 60,
      "type": "lingerie",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 7,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["one piece", "bodysuit"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "butt", "legs"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    })
  }),
  "lounge": toMap({
    "mia lounge apron": toMap({
      "id": "mia lounge apron",
      "category": "lounge",
      "name": "apron",
      "flavors": [
        "You look cute doing the chores.",
        "You're, like, a domestic goddess, or something like that.",
        "Unleash your inner housewife. Or, y'know, make some nachos. It's your call.",
        "Housewife in training!"
      ],
      "description": "little apron and a white dress",
      "price": 60,
      "type": "loungewear",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 7,
      "style": "cute",
      "colors": ["pink", "white"],
      "tags": ["easy access dress", "one piece", "two-layer top", "chores"],
      "emphasizes": ["legs"],
      "reveals": ["legs"],
      "top": "apron",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "mia lounge bath robe": toMap({
      "id": "mia lounge bath robe",
      "category": "lounge",
      "name": "bath robe",
      "flavors": [
        "Feels great putting this on after a long, steamy shower.",
        "You'd only need this if you were going to have someone over. Are you?",
        "If you could manage to close it maybe your family members wouldn't stare."
      ],
      "description": "terry cloth bathrobe",
      "price": 65,
      "type": "loungewear",
      "sluttiness": 5,
      "comfort": 7,
      "durability": 8,
      "style": "relaxed",
      "colors": ["black"],
      "tags": ["sleep"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "bathrobe",
      "breasts": "bathrobe",
      "bottom": "bathrobe",
      "pussy": "bathrobe",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "mia lounge grey pajamas": toMap({
      "id": "mia lounge grey pajamas",
      "category": "lounge",
      "name": "grey pajamas",
      "flavor": "For when you want to be comfy and you really don't need to impress anyone.",
      "description": "cotton pj top and bottom",
      "price": 30,
      "type": "loungewear",
      "sluttiness": 5,
      "comfort": 8,
      "durability": 5,
      "style": "relaxed",
      "colors": ["grey"],
      "tags": ["sleep"],
      "emphasizes": [],
      "reveals": ["tummy", "legs"],
      "top": "pj top",
      "breasts": "pj top",
      "bottom": "pj bottoms",
      "pussy": "pj bottoms",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "mia lounge pink velour": toMap({
      "id": "mia lounge pink velour",
      "category": "lounge",
      "name": "pink velour",
      "flavor": "Pink, soft to the touch, revealing. It definitely suits you.",
      "description": "velvety pj top and bottom",
      "price": 110,
      "type": "loungewear",
      "sluttiness": 7,
      "comfort": 10,
      "durability": 8,
      "style": "elegant",
      "colors": ["pink"],
      "tags": ["great sleep"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "legs"],
      "top": "pj top",
      "breasts": "pj top",
      "bottom": "pj bottoms",
      "pussy": "pj bottoms",
      "breast support": 5,
      "panties under": "can",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "mia lounge white button-down": toMap({
      "id": "mia lounge white button-down",
      "category": "lounge",
      "name": "white button-down",
      "flavors": [
        "It's literaly just a guy's shirt, repurposed as woman's loungewear.",
        "Good thing shirts are unisex!",
        "If everything else is in the wash, I guess this men's shirt could still be an option for lounging around."
      ],
      "description": "white button-down shirt",
      "price": 40,
      "type": "loungewear",
      "sluttiness": 8,
      "comfort": 4,
      "durability": 8,
      "style": "relaxed",
      "colors": ["white"],
      "tags": ["sleep", "masculine", "buttons", "one piece"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "guy's shirt",
      "breasts": "guy's shirt",
      "bottom": "guy's shirt",
      "pussy": "guy's shirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    })
  }),
  "office": toMap({
    "mia office front-zip blouse": toMap({
      "id": "mia office front-zip blouse",
      "category": "office",
      "name": "front-zip blouse",
      "flavors": [
        "There's no way you won't get a raise in this!",
        "Your coworkers might think you lack intelligence but at least you'll show them you have the curves to make up for it!"
      ],
      "description": "pink front-zip blouse and black skirt",
      "price": 120,
      "type": "office",
      "sluttiness": 7,
      "comfort": 4,
      "durability": 10,
      "style": "sexy",
      "colors": ["pink", "black"],
      "tags": ["very professional", "easy access skirt", "front zip", "zipper"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "front-zip blouse",
      "breasts": "front-zip blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "mia office low-cut pink blouse": toMap({
      "id": "mia office low-cut pink blouse",
      "category": "office",
      "name": "low-cut pink blouse",
      "flavor": "There's no way you won't get a raise in this!",
      "description": "pink button-down blouse and black skirt",
      "price": 100,
      "type": "office",
      "sluttiness": 8,
      "comfort": 6,
      "durability": 5,
      "style": "sexy",
      "colors": ["pink", "black"],
      "tags": ["professional", "easy access skirt", "buttons"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "mia office skirt and blouse": toMap({
      "id": "mia office skirt and blouse",
      "category": "office",
      "name": "skirt and blouse",
      "flavor": "A bit cheap looking, but it does the job.",
      "description": "pink front-zip blouse and black skirt",
      "price": 30,
      "type": "office",
      "sluttiness": 5,
      "comfort": 7,
      "durability": 4,
      "style": "casual",
      "colors": ["pink", "red"],
      "tags": ["professional", "easy access skirt"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "mia office white and grey officewear": toMap({
      "id": "mia office white and grey officewear",
      "category": "office",
      "name": "white and grey officewear",
      "flavor": "Probably the tamest officewear you've seen.",
      "description": "button-down shirt and grey pants",
      "price": 50,
      "type": "office",
      "sluttiness": 1,
      "comfort": 8,
      "durability": 8,
      "style": "modest",
      "colors": ["white", "grey"],
      "tags": ["professional", "masculine", "buttons"],
      "emphasizes": [],
      "reveals": [],
      "top": "button-down shirt",
      "breasts": "button-down shirt",
      "bottom": "pants",
      "pussy": "pants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "mia office houndstooth dress": toMap({
      "id": "mia office houndstooth dress",
      "category": "office",
      "name": "houndstooth dress",
      "flavor": "With a thin shoulder strap and a short skirt, it's not overly revealing but definitely slightly slutty for an office.",
      "description": "wool houndstooth dress",
      "price": 60,
      "type": "dress",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 10,
      "style": "slutty",
      "colors": ["black", "white"],
      "tags": ["professional", "easy access dress", "one piece"],
      "emphasizes": [],
      "reveals": [],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office", "stylin"]
    })
  }),
  "stylin": toMap({
    "mia stylin long white dress": toMap({
      "id": "mia stylin long white dress",
      "category": "stylin",
      "name": "long white dress",
      "flavor": "You can still look elegant while showing off your bombshell figure!",
      "description": "white cotton dress",
      "price": 100,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 10,
      "durability": 4,
      "style": "elegant",
      "colors": ["white"],
      "tags": ["one piece", "professional"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "wedges",
      "locations": ["stylin", "office"]
    }),
    "mia stylin orange dress": toMap({
      "id": "mia stylin orange dress",
      "category": "stylin",
      "name": "orange dress",
      "flavor": "You keep bending over to mess with your shoes, what is with this outfit?",
      "description": "orange dress",
      "price": 130,
      "type": "dress",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 6,
      "style": "sexy",
      "colors": ["orange"],
      "tags": ["one piece", "easy access dress", "professional"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "office"]
    }),
    "mia stylin pink dress": toMap({
      "id": "mia stylin pink dress",
      "category": "stylin",
      "name": "pink dress",
      "flavor": "It's hot pink and puts your cleavage on display... you know exactly what you're doing.",
      "description": "pink dress",
      "price": 120,
      "type": "dress",
      "sluttiness": 5,
      "comfort": 7,
      "durability": 5,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["one piece", "easy access dress"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "mia stylin white crop top": toMap({
      "id": "mia stylin white crop top",
      "category": "stylin",
      "name": "white crop top",
      "flavor": "You're super comfy, but your top can't fully contain your boobs.",
      "description": "white crop top and pants",
      "price": 150,
      "type": "stylish outfit",
      "sluttiness": 7,
      "comfort": 10,
      "durability": 4,
      "style": "sexy",
      "colors": ["white"],
      "tags": ["boobs fall out"],
      "emphasizes": ["underboob"],
      "reveals": ["underboob", "tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "pants",
      "pussy": "pants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "wedges",
      "locations": ["stylin", "casual"]
    }),
    "mia stylin rebellious": toMap({
      "id": "mia stylin rebellious",
      "category": "stylin",
      "name": "rebellious",
      "flavors": [
        "You don't wanna go to school, you just wanna break the rules!",
        "Now you get to be the sexy punk chick!",
        "Looking for someone to fix your daddy issues?",
        "You kinda look like a schoolgirl who just discovered gothy sluttiness. I guess it's never too late."
      ],
      "description": "black crop top and schoolgirl skirt",
      "price": 45,
      "type": "skirt and blouse",
      "sluttiness": 8,
      "comfort": 4,
      "durability": 3,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["easy access skirt"],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "lounge", "casual"]
    }),
    "mia stylin baby blue knot outfit": toMap({
      "id": "mia stylin baby blue knot outfit",
      "category": "stylin",
      "name": "baby blue knot outfit",
      "flavor": "An elegant look for a hot day.",
      "description": "knot-front top and shorts",
      "price": 80,
      "type": "shorts and top",
      "sluttiness": 2,
      "comfort": 10,
      "durability": 3,
      "style": "elegant",
      "colors": ["blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["legs", "tummy"],
      "top": "knot-front top",
      "breasts": "knot-front top",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sandals",
      "locations": ["stylin", "lounge", "casual", "beach"]
    })
  })
}));