window.GE.outfit_database = window.GE.outfit_database || new Map();

window.GE.outfit_database.set("rae", toMap({
  "purchasable": toMap({
    "beach": 3,
    "casual": 5,
    "fetish": 4,
    "lingerie": 5,
    "gym": 3,
    "lounge": 5,
    "office": 3,
    "stylin": 5
  }),
  "beach": toMap({
    "rae beach cute pink beach outfit": toMap({
      "id": "rae beach cute pink beach outfit",
      "category": "beach",
      "name": "cute pink beach outfit",
      "flavor": "This little beach outfit is cute and casual. The boys and gals are going to love you.",
      "description": "string bikini and loose beach top",
      "price": 60,
      "type": "casual beachwear",
      "sluttiness": 3,
      "comfort": 8,
      "durability": 4,
      "style": "cute",
      "colors": ["pink"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy", "butt"],
      "top": "beach top",
      "breasts": "bikini top",
      "bottom": "bikini bottoms",
      "pussy": "bikini bottoms",
      "breast support": 6,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "rae beach green one piece": toMap({
      "id": "rae beach green one piece",
      "category": "beach",
      "name": "green one piece",
      "flavor": "Something about the forest green gives a Japanese vibe.",
      "description": "low-cut green one-piece",
      "price": 65,
      "type": "one-piece swimsuit",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 5,
      "style": "sexy",
      "colors": ["green"],
      "tags": ["one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "one-piece swimsuit",
      "breasts": "one-piece swimsuit",
      "bottom": "one-piece swimsuit",
      "pussy": "one-piece swimsuit",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "rae beach grey bikini": toMap({
      "id": "rae beach grey bikini",
      "category": "beach",
      "name": "grey bikini",
      "flavor": "Casual yet displays your tits really nicely.",
      "description": "grey bikini top and bottom",
      "price": 70,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 6,
      "style": "casual",
      "colors": ["grey"],
      "tags": ["swim"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "butt", "legs", "tummy"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "rae beach honey pot": toMap({
      "id": "rae beach honey pot",
      "category": "beach",
      "name": "honey pot",
      "flavor": "You’re such a cutie. With your pig tails and cute shirt, you'll be the talk of the entire beach!",
      "description": "crop top, bikini top, and bikini bottom",
      "price": 60,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 3,
      "style": "cute",
      "colors": ["white"],
      "tags": ["swim"],
      "emphasizes": [],
      "reveals": ["butt", "legs", "tummy"],
      "top": "crop top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "rae beach nike bikini": toMap({
      "id": "rae beach nike bikini",
      "category": "beach",
      "name": "nike bikini",
      "flavor": "Just do it!",
      "description": "nike air bikini",
      "price": 100,
      "type": "bikini",
      "sluttiness": 3,
      "comfort": 8,
      "durability": 10,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["swim"],
      "emphasizes": ["cleavage"],
      "reveals": ["butt", "legs", "tummy", "cleavage"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 10,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "rae beach silky red bikini": toMap({
      "id": "rae beach silky red bikini",
      "category": "beach",
      "name": "silky red bikini",
      "flavor": "A soft, silky, and smooth bikini makes everyone stare at you.",
      "description": "silky red bikini",
      "price": 80,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 7,
      "style": "sexy",
      "colors": ["red"],
      "tags": ["swim"],
      "emphasizes": ["cleavage"],
      "reveals": ["butt", "legs", "tummy", "cleavage"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "rae beach triangle top and rings": toMap({
      "id": "rae beach triangle top and rings",
      "category": "beach",
      "name": "triangle top and rings",
      "flavor": "It's super sexy, but it doesn't hold your tits very securely.",
      "description": "black triangle bikini",
      "price": 90,
      "type": "bikini",
      "sluttiness": 8,
      "comfort": 5,
      "durability": 2,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["swim", "boobs fall out"],
      "emphasizes": ["boobs"],
      "reveals": ["butt", "legs", "tummy", "boobs"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 2,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "rae beach yellow bikini": toMap({
      "id": "rae beach yellow bikini",
      "category": "beach",
      "name": "yellow bikini",
      "flavor": "It's cute, and offers great support.",
      "description": "yellow bikini top and bottom",
      "price": 110,
      "type": "bikini",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 9,
      "style": "sexy",
      "colors": ["yellow"],
      "tags": ["swim"],
      "emphasizes": ["boobs"],
      "reveals": ["butt", "legs", "tummy", "boobs"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 10,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "rae beach blue bikini": toMap({
      "id": "rae beach blue bikini",
      "category": "beach",
      "name": "blue bikini",
      "flavor": "It's really classy, and makes your boobs look great.",
      "description": "blue bikini top and bottom",
      "price": 130,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 6,
      "style": "sexy",
      "colors": ["blue"],
      "tags": ["swim"],
      "emphasizes": ["boobs", "cleavage"],
      "reveals": ["butt", "legs", "tummy", "boobs"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    })
  }),
  "casual": toMap({
    "rae casual big sweatshirt": toMap({
      "id": "rae casual big sweatshirt",
      "category": "casual",
      "name": "big sweatshirt",
      "flavor": "Some outfits work for both guys and girls, like this one. ",
      "description": "big black sweatshirt",
      "price": 40,
      "type": "casual",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 4,
      "style": "cute",
      "colors": ["black"],
      "tags": ["one piece"],
      "emphasizes": [],
      "reveals": [],
      "top": "sweatshirt",
      "breasts": "sweatshirt",
      "bottom": "sweatshirt",
      "pussy": "sweatshirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "rae casual black and white": toMap({
      "id": "rae casual black and white",
      "category": "casual",
      "name": "black and white",
      "flavor": "This really shows off your cute little tush.",
      "description": "black tank top and white shorts",
      "price": 50,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 4,
      "style": "sexy",
      "colors": ["black", "white"],
      "tags": [],
      "emphasizes": ["asscheeks"],
      "reveals": ["asscheeks", "legs"],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "rae casual breaking and entering": toMap({
      "id": "rae casual breaking and entering",
      "category": "casual",
      "name": "breaking and entering",
      "flavor": "Breaking and entering… my heart.",
      "description": "black leather top and shorts",
      "price": 60,
      "type": "casual",
      "sluttiness": 3,
      "comfort": 8,
      "durability": 8,
      "style": "casual",
      "colors": ["black"],
      "tags": ["hat"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "leather jacket",
      "breasts": "leather jacket",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sandals",
      "locations": ["casual"]
    }),
    "rae casual crop top": toMap({
      "id": "rae casual crop top",
      "category": "casual",
      "name": "crop top",
      "flavor": "The strings on this cage-front top are working hard to contain you!",
      "description": "black cage-front crop top and yoga pants",
      "price": 50,
      "type": "casual",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 3,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["boobs fall out"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "yoga pants",
      "pussy": "yoga pants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual"]
    }),
    "rae casual flower dress": toMap({
      "id": "rae casual flower dress",
      "category": "casual",
      "name": "flower dress",
      "flavor": "It's quite tropical!",
      "description": "flowery sundress",
      "price": 60,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 4,
      "style": "cute",
      "colors": ["white"],
      "tags": ["easy access dress"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "wedges",
      "locations": ["casual"]
    }),
    "rae casual hiker": toMap({
      "id": "rae casual hiker",
      "category": "casual",
      "name": "hiker",
      "flavor": "Great for a hike in the jungle, on a hot day.",
      "description": "sports bra and short shorts",
      "price": 70,
      "type": "casual",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 5,
      "style": "sexy",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": ["asscheeks"],
      "reveals": ["asscheeks", "legs", "tummy"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["casual", "gym", "lounge"]
    }),
    "rae casual im watching you": toMap({
      "id": "rae casual im watching you",
      "category": "casual",
      "name": "im watching you",
      "flavor": "You can finally pull off cute anime girl tops, because you look like one yourself!",
      "description": "crop top and sweatpants",
      "price": 50,
      "type": "casual",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 4,
      "style": "cute",
      "colors": ["white", "black"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "sweatpants",
      "pussy": "sweatpants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "rae casual leather pants": toMap({
      "id": "rae casual leather pants",
      "category": "casual",
      "name": "leather pants",
      "flavor": "Form fitting and comfy, yet classy.",
      "description": "sweatshirt and leather pants",
      "price": 80,
      "type": "casual",
      "sluttiness": 2,
      "comfort": 9,
      "durability": 9,
      "style": "casual",
      "colors": ["grey", "black"],
      "tags": [],
      "emphasizes": [],
      "reveals": [],
      "top": "sweatshirt",
      "breasts": "sweatshirt",
      "bottom": "leather pants",
      "pussy": "leather pants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "wedges",
      "locations": ["casual", "stylin"]
    }),
    "rae casual orange crop top": toMap({
      "id": "rae casual orange crop top",
      "category": "casual",
      "name": "orange crop top",
      "flavor": "Cute, even though its mayyybe a little trashy.",
      "description": "orange crop top and distressed jean shorts",
      "price": 35,
      "type": "casual",
      "sluttiness": 4,
      "comfort": 5,
      "durability": 4,
      "style": "cute",
      "colors": ["orange", "blue"],
      "tags": [],
      "emphasizes": ["asscheeks"],
      "reveals": ["asscheeks", "tummy", "legs"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "rae casual red halter top": toMap({
      "id": "rae casual red halter top",
      "category": "casual",
      "name": "red halter top",
      "flavor": "You'd better tie this properly.",
      "description": "red crop top and jeans",
      "price": 50,
      "type": "casual",
      "sluttiness": 5,
      "comfort": 3,
      "durability": 3,
      "style": "sexy",
      "colors": ["red", "blue"],
      "tags": [],
      "emphasizes": ["sideboob"],
      "reveals": ["sideboob", "tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    }),
    "rae casual shark sweatshirt": toMap({
      "id": "rae casual shark sweatshirt",
      "category": "casual",
      "name": "shark sweatshirt",
      "flavor": "It's a fun contrast between a sweatshirt and tiny shorts.",
      "description": "sweatshirt and short shorts",
      "price": 65,
      "type": "casual",
      "sluttiness": 7,
      "comfort": 7,
      "durability": 5,
      "style": "sexy",
      "colors": ["black"],
      "tags": [],
      "emphasizes": ["asscheeks"],
      "reveals": ["asscheeks", "legs"],
      "top": "sweatshirt",
      "breasts": "sweatshirt",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "rae casual striped tanktop": toMap({
      "id": "rae casual striped tanktop",
      "category": "casual",
      "name": "striped tanktop",
      "flavor": "It's very… orange. But somehow looks good on you!",
      "description": "cropped tank top and shorts",
      "price": 40,
      "type": "casual",
      "sluttiness": 4,
      "comfort": 4,
      "durability": 4,
      "style": "casual",
      "colors": ["orange", "white"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "cropped tanktop",
      "breasts": "cropped tanktop",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "rae casual tight grey shirt": toMap({
      "id": "rae casual tight grey shirt",
      "category": "casual",
      "name": "tight grey shirt",
      "flavor": "Sometimes an outfit can totally cover your body, yet also show it off. Like this!",
      "description": "tight grey shirt and jeans",
      "price": 55,
      "type": "casual",
      "sluttiness": 3,
      "comfort": 8,
      "durability": 4,
      "style": "sexy",
      "colors": ["grey", "blue"],
      "tags": [],
      "emphasizes": ["boobs"],
      "reveals": [],
      "top": "tight shirt",
      "breasts": "tight shirt",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "rae casual white tank top": toMap({
      "id": "rae casual white tank top",
      "category": "casual",
      "name": "white tank top",
      "flavor": "Cute and sexy.",
      "description": "white cropped tank top and sweatpants",
      "price": 40,
      "type": "casual",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 4,
      "style": "sexy",
      "colors": ["white", "grey"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "sweatpants",
      "pussy": "sweatpants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    })
  }),
  "fetish": toMap({
    "rae fetish angelic": toMap({
      "id": "rae fetish angelic",
      "category": "fetish",
      "name": "angelic",
      "flavor": "Better get some practice welcoming guys to heaven!",
      "description": "bodysuit, stockings and angel wings",
      "price": 250,
      "type": "fetishwear",
      "sluttiness": 8,
      "comfort": 3,
      "durability": 3,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["stockings", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    }),
    "rae fetish easter": toMap({
      "id": "rae fetish easter",
      "category": "fetish",
      "name": "easter",
      "flavors": [
        "You look like you're ready to fuck like a bunny!",
        "They'll wanna go down your rabbit hole!",
        "You’re going to have a lot of fun this Easter. This little bunny outfit makes you feel slutty and festive at the same time."
      ],
      "description": "bra, panties, and bunny ears",
      "price": 150,
      "type": "fetishwear",
      "sluttiness": 9,
      "comfort": 4,
      "durability": 2,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["collar"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    }),
    "rae fetish femme fatale": toMap({
      "id": "rae fetish femme fatale",
      "category": "fetish",
      "name": "femme fatale",
      "flavors": [
        "James Bond, eat your heart out.",
        "You're ready to handle some heavy weaponry.",
        "You're ready to take some rich guys' money!"
      ],
      "description": "silken black bodysuit",
      "price": 90,
      "type": "fetishwear",
      "sluttiness": 6,
      "comfort": 4,
      "durability": 5,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["one piece", "rich magnet"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "butt", "legs"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heel boots",
      "locations": ["fetish"]
    }),
    "rae fetish french maid": toMap({
      "id": "rae fetish french maid",
      "category": "fetish",
      "name": "french maid",
      "flavor": "This outfit makes you look really submissive. And productive!",
      "description": "french maid outfit",
      "price": 130,
      "type": "fetishwear",
      "sluttiness": 7,
      "comfort": 6,
      "durability": 6,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["one piece", "easy access dress", "chores"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "butt", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["fetish", "lounge"]
    }),
    "rae fetish hey sailor": toMap({
      "id": "rae fetish hey sailor",
      "category": "fetish",
      "name": "hey sailor",
      "flavors": [
        "God, you look cute in this.",
        "There are some cute boys in the navy. They’re gonna love you."
      ],
      "description": "sailor dress",
      "price": 50,
      "type": "fetishwear",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 7,
      "style": "cute",
      "colors": ["white"],
      "tags": ["one piece", "easy access dress", "short dress", "not serious"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 3,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["fetish", "lounge", "casual", "stylin", "office"]
    }),
    "rae fetish idee fixe restraint": toMap({
      "id": "rae fetish idee fixe restraint",
      "category": "fetish",
      "name": "idee fixe restraint",
      "flavor": "You're ready to be tied up even more.",
      "description": "harness bodysuit",
      "price": 250,
      "type": "fetishwear",
      "sluttiness": 7,
      "comfort": 2,
      "durability": 10,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["one piece", "push aside", "straps", "semi-transparent top", "semi-transparent"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "nipples", "boobs"],
      "top": "harness bodysuit",
      "breasts": "harness bodysuit",
      "bottom": "harness bodysuit",
      "pussy": "harness bodysuit",
      "breast support": 1,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heel boots",
      "locations": ["fetish"]
    }),
    "rae fetish milk maid": toMap({
      "id": "rae fetish milk maid",
      "category": "fetish",
      "name": "milk maid",
      "flavors": [
        "Just what are you gonna milk?",
        "Got milk? Yes, you do!"
      ],
      "description": "milkmaid blouse and skirt",
      "price": 140,
      "type": "fetishwear",
      "sluttiness": 5,
      "comfort": 9,
      "durability": 3,
      "style": "sexy",
      "colors": ["white", "blue"],
      "tags": ["easy access skirt", "chores", "not serious"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "legs"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 3,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["fetish", "lounge"]
    }),
    "rae fetish minnie": toMap({
      "id": "rae fetish minnie",
      "category": "fetish",
      "name": "minnie",
      "flavor": "I'm not sure Disney ever sanctioned this outfit.",
      "description": "polka-dot blouse and skirt",
      "price": 50,
      "type": "fetishwear",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 3,
      "style": "sexy",
      "colors": ["red"],
      "tags": ["easy access skirt"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "legs"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["fetish"]
    }),
    "rae fetish on display": toMap({
      "id": "rae fetish on display",
      "category": "fetish",
      "name": "on display",
      "flavor": "Perfect for corporate meetings. Just kidding.",
      "description": "outfit that doubles as dental floss",
      "price": 15,
      "type": "fetishwear",
      "sluttiness": 10,
      "comfort": 2,
      "durability": 1,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["basically naked", "push aside", "no obstruction", "boobs fall out"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "butt", "tummy", "legs"],
      "top": "string",
      "breasts": "string",
      "bottom": "string",
      "pussy": "string",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    }),
    "rae fetish sailor mooning": toMap({
      "id": "rae fetish sailor mooning",
      "category": "fetish",
      "name": "sailor mooning",
      "flavor": "Not sure if this is a maid outfit or a sailor outfit. But who cares?",
      "description": "frilly bodysuit with apron",
      "price": 55,
      "type": "fetishwear",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 4,
      "style": "slutty",
      "colors": ["blue", "white"],
      "tags": ["one piece", "push aside", "chores"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "butt", "tummy", "legs"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["fetish", "lounge"]
    })
  }),
  "gym": toMap({
    // guaranteed, plus 3 others
    "rae gym blue gym outfit": toMap({
      "id": "rae gym blue gym outfit",
      "category": "gym",
      "name": "blue gym outfit",
      "flavor": "Cheap and quite practical.",
      "description": "blue sports shirt and shorts",
      "price": 35,
      "type": "fitness",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 3,
      "style": "relaxed",
      "colors": ["blue", "grey"],
      "tags": ["workout", "gym scene"],
      "emphasizes": [],
      "reveals": ["tummy", "legs"],
      "top": "sports shirt",
      "breasts": "sports shirt",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["gym", "casual", "lounge"]
    }),
    "rae gym booty shorts": toMap({
      "id": "rae gym booty shorts",
      "category": "gym",
      "name": "booty shorts",
      "flavor": "Form fitting and sexy.",
      "description": "sports bra and booty shorts",
      "price": 70,
      "type": "fitness",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 7,
      "style": "sexy",
      "colors": ["black", "white"],
      "tags": ["workout"],
      "emphasizes": ["asscheeks"],
      "reveals": ["asscheeks", "tummy", "legs"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 9,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "casual", "lounge"]
    }),
    "rae gym bottom heavy": toMap({
      "id": "rae gym bottom heavy",
      "category": "gym",
      "name": "bottom heavy",
      "flavor": "A slutty way to show off your squat gainz.",
      "description": "sweatshirt and thong",
      "price": 70,
      "type": "fitness",
      "sluttiness": 9,
      "comfort": 3,
      "durability": 2,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["workout", "push aside"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "legs"],
      "top": "sweatshirt",
      "breasts": "sweatshirt",
      "bottom": "thong",
      "pussy": "thong",
      "breast support": 0,
      "panties under": "no",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["gym", "casual", "lounge"]
    }),
    // This shows up twice
    "rae gym fishnets": toMap({
      "id": "rae gym fishnets",
      "category": "gym",
      "name": "fishnets",
      "flavor": "A slightly strange combination of colors and textures… but let's be real, they won't be looking at the outfit.",
      "description": "fishnet crop top and sports bra/panties",
      "price": 50,
      "type": "fitness",
      "sluttiness": 8,
      "comfort": 5,
      "durability": 4,
      "style": "slutty",
      "colors": ["black", "yellow"],
      "tags": ["workout"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "legs", "tummy"],
      "top": "fishnet crop top",
      "breasts": "sports bra",
      "bottom": "sport panties",
      "pussy": "sport panties",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "casual", "lounge"]
    }),
    "rae gym tenisu": toMap({
      "id": "rae gym tenisu",
      "category": "gym",
      "name": "tenisu",
      "flavor": "Watashi wa sekushīna tenisu o suru no ga sukidesu.",
      "description": "sports bikini",
      "price": 120,
      "type": "fitness",
      "sluttiness": 7,
      "comfort": 6,
      "durability": 8,
      "style": "elegant",
      "colors": ["pink"],
      "tags": ["workout"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "legs", "butt"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "beach", "lounge"]
    }),
    "rae gym tight": toMap({
      "id": "rae gym tight",
      "category": "gym",
      "name": "tight",
      "flavor": "The outfit is constricting, but can keep pace with a tough workout.",
      "description": "sports bra and shorts",
      "price": 90,
      "type": "fitness",
      "sluttiness": 5,
      "comfort": 2,
      "durability": 10,
      "style": "sexy",
      "colors": ["black", "pink"],
      "tags": ["great workout"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "legs"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "sport shorts",
      "pussy": "sport shorts",
      "breast support": 10,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym"]
    }),
    "rae gym tigress": toMap({
      "id": "rae gym tigress",
      "category": "gym",
      "name": "tigress",
      "flavor": "Rawr!",
      "description": "sports bra and sweatpants",
      "price": 110,
      "type": "fitness",
      "sluttiness": 7,
      "comfort": 8,
      "durability": 6,
      "style": "sexy",
      "colors": ["black", "white"],
      "tags": ["workout"],
      "emphasizes": ["lots of cleavage"],
      "reveals": ["boobs", "tummy"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "sweatpants",
      "pussy": "sweatpants",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym", "lounge", "casual"]
    }),
    "rae gym yoga pants": toMap({
      "id": "rae gym yoga pants",
      "category": "gym",
      "name": "yoga pants",
      "flavor": "You feel really flexible in this.",
      "description": "tank top and yoga pants",
      "price": 70,
      "type": "fitness",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 9,
      "style": "casual",
      "colors": ["black"],
      "tags": ["workout"],
      "emphasizes": ["butt"],
      "reveals": [],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "yoga pants",
      "pussy": "yoga pants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["gym", "lounge", "casual"]
    })
  }),
  "lingerie": toMap({
    "rae lingerie black garter": toMap({
      "id": "rae lingerie black garter",
      "category": "lingerie",
      "name": "black garter",
      "flavor": "Elegant and sexy. Black is really your color!",
      "description": "lacy black lingerie with garter and stockings",
      "price": 90,
      "type": "lingerie",
      "sluttiness": 5,
      "comfort": 4,
      "durability": 10,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["stockings"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "rae lingerie black lingerie with stockings": toMap({
      "id": "rae lingerie black lingerie with stockings",
      "category": "lingerie",
      "name": "black lingerie with stockings",
      "flavor": "This set has a soft, silky feel that makes it comfy, even though it's fancy.",
      "description": "silky black lingerie with stockings",
      "price": 110,
      "type": "lingerie",
      "sluttiness": 6,
      "comfort": 8,
      "durability": 7,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["stockings"],
      "emphasizes": ["butt"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    // Doesn't show up
    "rae lingerie black bodysuit": toMap({
      "id": "rae lingerie black bodysuit",
      "category": "lingerie",
      "name": "black bodysuit",
      "flavor": "Lacy and sheer, it shows off just the right amount of skin.",
      "description": "black bodysuit with stockings",
      "price": 130,
      "type": "lingerie",
      "sluttiness": 7,
      "comfort": 4,
      "durability": 9,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["stockings", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 7,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie", "fetish"]
    }),
    "rae lingerie casual pink bra": toMap({
      "id": "rae lingerie casual pink bra",
      "category": "lingerie",
      "name": "casual pink bra",
      "flavor": "Casual and fun, this is a great everyday bra.",
      "description": "pink bra and grey t-shirt material panties",
      "price": 20,
      "type": "lingerie",
      "sluttiness": 3,
      "comfort": 9,
      "durability": 5,
      "style": "casual",
      "colors": ["pink", "grey"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "rae lingerie fishnet lingerie": toMap({
      "id": "rae lingerie fishnet lingerie",
      "category": "lingerie",
      "name": "fishnet lingerie",
      "flavor": "This set comes with an optional pair of fishnet stockings.",
      "description": "black bra and panties, with stockings",
      "price": 50,
      "type": "lingerie",
      "sluttiness": 5,
      "comfort": 7,
      "durability": 4,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["stockings"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 6,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "rae lingerie forest green lace": toMap({
      "id": "rae lingerie forest green lace",
      "category": "lingerie",
      "name": "forest green lace",
      "flavor": "This color looks really good on you.",
      "description": "green lace bra and panties",
      "price": 90,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 2,
      "style": "sexy",
      "colors": ["green"],
      "tags": [],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "rae lingerie lacy black lingerie": toMap({
      "id": "rae lingerie lacy black lingerie",
      "category": "lingerie",
      "name": "lacy black lingerie",
      "flavor": "A simple yet beautiful set.",
      "description": "black lace bra and panties",
      "price": 70,
      "type": "lingerie",
      "sluttiness": 3,
      "comfort": 8,
      "durability": 5,
      "style": "sexy",
      "colors": ["black"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "rae lingerie pale green lingerie": toMap({
      "id": "rae lingerie pale green lingerie",
      "category": "lingerie",
      "name": "pale green lingerie",
      "flavor": "The material is super comfy, and supports those jiggling breasts.",
      "description": "green bra and panties",
      "price": 60,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 10,
      "durability": 4,
      "style": "casual",
      "colors": ["green"],
      "tags": [],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "rae lingerie pretty in pink": toMap({
      "id": "rae lingerie pretty in pink",
      "category": "lingerie",
      "name": "pretty in pink",
      "flavor": "This is about as extra as lingerie can be.",
      "description": "fancy pink lingerie",
      "price": 250,
      "type": "lingerie",
      "sluttiness": 9,
      "comfort": 3,
      "durability": 9,
      "style": "elegant",
      "colors": ["pink"],
      "tags": ["rich magnet", "straps"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 4,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "rae lingerie simple black lingerie": toMap({
      "id": "rae lingerie simple black lingerie",
      "category": "lingerie",
      "name": "simple black lingerie",
      "flavor": "Straightforward and supportive.",
      "description": "black polyester bra and panties",
      "price": 40,
      "type": "lingerie",
      "sluttiness": 3,
      "comfort": 6,
      "durability": 8,
      "style": "casual",
      "colors": ["black"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 9,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    })
  }),
  "lounge": toMap({
    "rae lounge bra and sweatpants": toMap({
      "id": "rae lounge bra and sweatpants",
      "category": "lounge",
      "name": "bra and sweatpants",
      "flavor": "What it says on the tin.",
      "description": "bra and grey knit sweatpants",
      "price": 35,
      "type": "loungewear",
      "sluttiness": 7,
      "comfort": 8,
      "durability": 6,
      "style": "sexy",
      "colors": ["black", "grey"],
      "tags": ["sleep"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "sweatpants",
      "pussy": "sweatpants",
      "breast support": 5,
      "panties under": "can",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "rae lounge fluffy pink pjs": toMap({
      "id": "rae lounge fluffy pink pjs",
      "category": "lounge",
      "name": "fluffy pink pjs",
      "flavor": "An extremely comfy and cute set of pajamas.",
      "description": "pink pj top and bottom",
      "price": 70,
      "type": "loungewear",
      "sluttiness": 2,
      "comfort": 10,
      "durability": 7,
      "style": "cute",
      "colors": ["pink"],
      "tags": ["great sleep"],
      "emphasizes": [],
      "reveals": [],
      "top": "pj top",
      "breasts": "pj top",
      "bottom": "pj bottom",
      "pussy": "pj bottom",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "rae lounge fluffy": toMap({
      "id": "rae lounge fluffy",
      "category": "lounge",
      "name": "fluffy",
      "flavor": "An extremely comfy getup, although pretty revealing if you unbutton too many buttons.",
      "description": "button-down shirt and grey lingerie",
      "price": 40,
      "type": "loungewear",
      "sluttiness": 6,
      "comfort": 8,
      "durability": 6,
      "style": "sexy",
      "colors": ["grey"],
      "tags": ["sleep"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "legs", "cleavage", "butt"],
      "top": "button-down shirt",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 8,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "rae lounge game night": toMap({
      "id": "rae lounge game night",
      "category": "lounge",
      "name": "game night",
      "flavor": "A guy's sports shirt, oversized so it (mostly}) covers your naughty bits.",
      "description": "sports shirt and panties",
      "price": 60,
      "type": "loungewear",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 8,
      "style": "relaxed",
      "colors": ["black"],
      "tags": ["sleep"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "legs", "cleavage", "butt"],
      "top": "sports shirt",
      "breasts": "sports shirt",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "rae lounge holy lacy bralette": toMap({
      "id": "rae lounge holy lacy bralette",
      "category": "lounge",
      "name": "holy lacy bralette",
      "flavor": "A comfy pj set that may be able to ward off vampires.",
      "description": "bralette and string panties",
      "price": 40,
      "type": "loungewear",
      "sluttiness": 8,
      "comfort": 7,
      "durability": 5,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["sleep"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "legs", "cleavage", "butt"],
      "top": "bralette",
      "breasts": "bralette",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge", "lingerie"]
    }),
    "rae lounge kimono": toMap({
      "id": "rae lounge kimono",
      "category": "lounge",
      "name": "kimono",
      "flavor": "A traditional Japanese robe. Really comfy.",
      "description": "kimono",
      "price": 90,
      "type": "loungewear",
      "sluttiness": 2,
      "comfort": 9,
      "durability": 8,
      "style": "elegant",
      "colors": ["white"],
      "tags": ["sleep", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "kimono",
      "breasts": "kimono",
      "bottom": "kimono",
      "pussy": "kimono",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "rae lounge lacy nightgown": toMap({
      "id": "rae lounge lacy nightgown",
      "category": "lounge",
      "name": "lacy nightgown",
      "flavor": "It honestly hides very little.",
      "description": "see-through nightgown",
      "price": 110,
      "type": "loungewear",
      "sluttiness": 10,
      "comfort": 7,
      "durability": 3,
      "style": "slutty",
      "colors": ["white"],
      "tags": ["sleep", "one piece", "basically naked", "transparent", "easy access dress"],
      "emphasizes": ["nipples"],
      "reveals": ["boobs", "nipples", "butt", "pussy", "tummy"],
      "top": "nightgown",
      "breasts": "nightgown",
      "bottom": "nightgown",
      "pussy": "nightgown",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge", "fetish"]
    }),
    "rae lounge loungewear": toMap({
      "id": "rae lounge loungewear",
      "category": "lounge",
      "name": "loungewear",
      "flavor": "Pretty basic but cute.",
      "description": "sports bra and sweatpants",
      "price": 50,
      "type": "loungewear",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 7,
      "style": "sexy",
      "colors": ["red", "black"],
      "tags": ["sleep"],
      "emphasizes": [],
      "reveals": ["tummy"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "sweatpants",
      "pussy": "sweatpants",
      "breast support": 7,
      "panties under": "can",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge", "casual", "gym"]
    }),
    "rae lounge low cut peach t-shirt": toMap({
      "id": "rae lounge low cut peach t-shirt",
      "category": "lounge",
      "name": "low cut peach t-shirt",
      "flavor": "Hey! Eyes up here.",
      "description": "t-shirt and panties",
      "price": 60,
      "type": "loungewear",
      "sluttiness": 6,
      "comfort": 8,
      "durability": 4,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["sleep"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "t-shirt",
      "breasts": "t-shirt",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "rae lounge pinkity drinkity": toMap({
      "id": "rae lounge pinkity drinkity",
      "category": "lounge",
      "name": "pinkity drinkity",
      "flavor": "Cute and VERY girly.",
      "description": "crop top, bra and panties",
      "price": 40,
      "type": "loungewear",
      "sluttiness": 7,
      "comfort": 8,
      "durability": 5,
      "style": "cute",
      "colors": ["white", "pink"],
      "tags": ["sleep"],
      "emphasizes": [],
      "reveals": ["tummy", "legs", "butt"],
      "top": "crop top",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 5,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "rae lounge silk pjs": toMap({
      "id": "rae lounge silk pjs",
      "category": "lounge",
      "name": "silk pjs",
      "flavor": "A comfy and classy set of sleepwear.",
      "description": "grey tanktop and shorts",
      "price": 150,
      "type": "loungewear",
      "sluttiness": 3,
      "comfort": 9,
      "durability": 8,
      "style": "elegant",
      "colors": ["grey"],
      "tags": ["great sleep"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 3,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    })
  }),
  "office": toMap({
    "rae office black business suit": toMap({
      "id": "rae office black business suit",
      "category": "office",
      "name": "black business suit",
      "flavor": "It doesn't have any pants, does that make this technically a dress?",
      "description": "suit dress",
      "price": 90,
      "type": "dress",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 7,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["easy access dress", "stockings", "very professional"],
      "emphasizes": ["legs"],
      "reveals": ["legs", "cleavage"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "rae office button down shirt": toMap({
      "id": "rae office button down shirt",
      "category": "office",
      "name": "button down shirt",
      "flavor": "This is a very slutty option for the office. Only wear this if you want a LOT of attention.",
      "description": "low-cut button-down shirt and skirt",
      "price": 70,
      "type": "skirt and blouse",
      "sluttiness": 10,
      "comfort": 5,
      "durability": 3,
      "style": "slutty",
      "colors": ["white", "black"],
      "tags": ["easy access skirt", "buttons", "professional"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "legs"],
      "top": "button-down shirt",
      "breasts": "button-down shirt",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "rae office white business suit": toMap({
      "id": "rae office white business suit",
      "category": "office",
      "name": "white business suit",
      "flavor": "You look like a mix between a high-end air stewardess, and a boss bitch!",
      "description": "suit dress",
      "price": 150,
      "type": "skirt and blouse",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 8,
      "style": "elegant",
      "colors": ["white"],
      "tags": ["easy access dress", "very professional"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "suit dress",
      "breasts": "suit dress",
      "bottom": "suit dress",
      "pussy": "suit dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    })
  }),
  "stylin": toMap({
    "rae stylin anaconda": toMap({
      "id": "rae stylin anaconda",
      "category": "stylin",
      "name": "anaconda",
      "flavor": "This dress hugs your curves and fits like a second skin.",
      "description": "snakeskin-pattern dress",
      "price": 150,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 4,
      "style": "sexy",
      "colors": ["grey"],
      "tags": ["easy access dress", "short dress", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "casual"]
    }),
    "rae stylin black gala dress": toMap({
      "id": "rae stylin black gala dress",
      "category": "stylin",
      "name": "black gala dress",
      "flavors": [
        "You look incredibly fancy in this.",
        "Elegance to the max. You’re going to catch everyone's eye."
      ],
      "description": "low-cut designer dress",
      "price": 350,
      "type": "dress",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 7,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["one piece", "rich magnet"],
      "emphasizes": ["lots of cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "rae stylin classy black dress": toMap({
      "id": "rae stylin classy black dress",
      "category": "stylin",
      "name": "classy black dress",
      "flavor": "This is intended for going out, but may work at the office too.",
      "description": "dress",
      "price": 210,
      "type": "dress",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 8,
      "style": "elegant",
      "colors": ["black"],
      "tags": ["one piece", "professional"],
      "emphasizes": ["cleavage", "legs"],
      "reveals": ["cleavage", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["stylin", "office"]
    }),
    "rae stylin floppy hat": toMap({
      "id": "rae stylin floppy hat",
      "category": "stylin",
      "name": "floppy hat",
      "flavor": "You look ready to go watch some polo.",
      "description": "white buttoned dress and matching hat",
      "price": 320,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 4,
      "durability": 4,
      "style": "elegant",
      "colors": ["white"],
      "tags": ["one piece", "rich magnet", "easy access dress", "hat"],
      "emphasizes": ["cleavage", "legs"],
      "reveals": ["cleavage", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "rae stylin leather demon": toMap({
      "id": "rae stylin leather demon",
      "category": "stylin",
      "name": "leather demon",
      "flavor": "A rather slutty getup. But damn, you look good in it!",
      "description": "leather jacket, fishnet top and panties",
      "price": 130,
      "type": "stylish outfit",
      "sluttiness": 10,
      "comfort": 3,
      "durability": 7,
      "style": "slutty",
      "colors": ["black"],
      "tags": ["chad magnet"],
      "emphasizes": ["boobs"],
      "reveals": ["boobs", "legs", "tummy", "butt"],
      "top": "leather jacket",
      "breasts": "fishnet top",
      "bottom": "fishnet panties",
      "pussy": "fishnet panties",
      "breast support": 2,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heel boots",
      "locations": ["stylin"]
    }),
    "rae stylin black skirt": toMap({
      "id": "rae stylin black skirt",
      "category": "stylin",
      "name": "black skirt",
      "flavor": "A super cute look.",
      "description": "crop top and skirt",
      "price": 110,
      "type": "stylish outfit",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 5,
      "style": "cute",
      "colors": ["white", "black"],
      "tags": ["easy access skirt", "nerd magnet"],
      "emphasizes": [],
      "reveals": ["legs", "tummy"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["stylin", "casual", "office"]
    }),
    "rae stylin leather": toMap({
      "id": "rae stylin leather",
      "category": "stylin",
      "name": "leather",
      "flavor": "You feel ready to hit the town in this!",
      "description": "form-fitting leather dress",
      "price": 150,
      "type": "dress",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 7,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["easy access dress", "short dress", "waterproof"],
      "emphasizes": [],
      "reveals": ["legs", "cleavage"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "rae stylin red clubbing dress": toMap({
      "id": "rae stylin red clubbing dress",
      "category": "stylin",
      "name": "red clubbing dress",
      "flavor": "This makes you want to go out and have fun.",
      "description": "red dress",
      "price": 120,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 6,
      "style": "sexy",
      "colors": ["red"],
      "tags": ["easy access dress", "short dress"],
      "emphasizes": [],
      "reveals": ["legs", "cleavage"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "rae stylin red dress": toMap({
      "id": "rae stylin red dress",
      "category": "stylin",
      "name": "red dress",
      "flavor": "Uber stylish and flowy. Makes you feel too good for everyone around you!",
      "description": "red dress",
      "price": 210,
      "type": "dress",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 7,
      "style": "elegant",
      "colors": ["red"],
      "tags": ["rich magnet"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "rae stylin white fantasy": toMap({
      "id": "rae stylin white fantasy",
      "category": "stylin",
      "name": "white fantasy",
      "flavors": [
        "Flowy and sexy!",
        "You're someone's fantasy, come to life."
      ],
      "description": "white dress",
      "price": 250,
      "type": "dress",
      "sluttiness": 5,
      "comfort": 9,
      "durability": 5,
      "style": "cute",
      "colors": ["white"],
      "tags": ["buttons"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "casual"]
    }),
    "rae stylin white dress": toMap({
      "id": "rae stylin white dress",
      "category": "stylin",
      "name": "white dress",
      "flavor": "As simple as a dress can get.",
      "description": "white dress",
      "price": 80,
      "type": "dress",
      "sluttiness": 6,
      "comfort": 6,
      "durability": 4,
      "style": "sexy",
      "colors": ["white"],
      "tags": ["easy access dress", "short dress"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "casual"]
    }),
    "rae stylin whimsical green dress": toMap({
      "id": "rae stylin whimsical green dress",
      "category": "stylin",
      "name": "whimsical green dress",
      "flavors": [
        "Not sure if this is traditional, or just something dreamed up by a designer.",
        "You look like a hotter Wicked Witch of the West."
      ],
      "description": "green dress",
      "price": 500,
      "type": "dress",
      "sluttiness": 1,
      "comfort": 10,
      "durability": 10,
      "style": "elegant",
      "colors": ["green"],
      "tags": ["rich magnet"],
      "emphasizes": [],
      "reveals": [],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "boots",
      "locations": ["stylin"]
    }),
    "rae stylin swiss miss": toMap({
      "id": "rae stylin swiss miss",
      "category": "stylin",
      "name": "swiss miss",
      "flavors": [
        "You're all ready for Oktoberfest.",
        "The corset is a little uncomfortable..."
      ],
      "description": "swiss dress",
      "price": 200,
      "type": "dress",
      "sluttiness": 3,
      "comfort": 2,
      "durability": 8,
      "style": "cute",
      "colors": ["brown"],
      "tags": [],
      "emphasizes": ["cleavage"],
      "reveals": [],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    // Doesn't show up
    "rae stylin rogue": toMap({
      "id": "rae stylin rogue",
      "category": "stylin",
      "name": "rogue",
      "flavor": "Blend in with the shadows!",
      "description": "black turtleneck and leather pants",
      "price": 140,
      "type": "dress",
      "sluttiness": 1,
      "comfort": 6,
      "durability": 10,
      "style": "casual",
      "colors": ["black"],
      "tags": [],
      "emphasizes": [],
      "reveals": [],
      "top": "turtleneck",
      "breasts": "turtleneck",
      "bottom": "pants",
      "pussy": "pants",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["stylin", "casual"]
    })
  })
}));