window.GE.outfit_database = window.GE.outfit_database || new Map();

window.GE.outfit_database.set("scarlit", toMap({
  "purchasable": toMap({
    "beach": 5,
    "casual": 4,
    "fetish": 5,
    "lingerie": 6,
    "gym": 3,
    "lounge": 3,
    "office": 3,
    "stylin": 5
  }),
  "beach": toMap({
    "scarlit beach deep v": toMap({
      "id": "scarlit beach deep v",
      "category": "beach",
      "name": "deep v",
      "flavors": [
        "The V can't get much deeper.",
        "Not practical in the water especially with those boots. Still waterproof though!"
      ],
      "description": "gold deep v halter one piece swimsuit",
      "price": 165,
      "type": "swimsuit",
      "sluttiness": 9,
      "comfort": 4,
      "durability": 4,
      "style": "slutty",
      "colors": ["gold", "black"],
      "tags": ["waterproof"],
      "emphasizes": ["legs"],
      "reveals": ["legs", "cleavage", "butt"],
      "top": "swimsuit",
      "breasts": "swimsuit",
      "bottom": "swimsuit",
      "pussy": "swimsuit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "boots",
      "locations": ["beach", "fetish"]
    }),
    "scarlit beach blue beach gown": toMap({
      "id": "scarlit beach blue beach gown",
      "category": "beach",
      "name": "blue beach gown",
      "flavor": "An elegant and expensive-looking option.",
      "description": "blue robe and golden bikini",
      "price": 140,
      "type": "casual beachwear",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 6,
      "style": "elegant",
      "colors": ["blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["cleavage", "tummy", "legs"],
      "top": "robe",
      "breasts": "bikini top",
      "bottom": "robe",
      "pussy": "bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "scarlit beach blue one piece": toMap({
      "id": "scarlit beach blue one piece",
      "category": "beach",
      "name": "blue one piece",
      "flavor": "Perfect for swimming some laps.",
      "description": "blue one-piece swimsuit",
      "price": 60,
      "type": "one-piece swimsuit",
      "sluttiness": 2,
      "comfort": 6,
      "durability": 8,
      "style": "casual",
      "colors": ["blue"],
      "tags": ["waterproof", "swim", "one piece"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "legs"],
      "top": "swimsuit",
      "breasts": "swimsuit",
      "bottom": "swimsuit",
      "pussy": "swimsuit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "scarlit beach bubbalicious": toMap({
      "id": "scarlit beach bubbalicious",
      "category": "beach",
      "name": "bubbalicious",
      "flavors": [
        "Yeah, this outfit definitely embraces the sexiness factor, not as practical as some other choices.",
        "It takes a special kind of girl to wear heels to the beach or pool."
      ],
      "description": "pink bikini top and bottom",
      "price": 100,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 3,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["swim"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "legs", "tummy", "cleavage"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["beach"]
    }),
    "scarlit beach fuscia one piece": toMap({
      "id": "scarlit beach fuscia one piece",
      "category": "beach",
      "name": "fuscia one piece",
      "flavor": "This swimsuit has some nice touches, like bows at the hips.",
      "description": "fuscia one-piece swimsuit",
      "price": 50,
      "type": "one-piece swimsuit",
      "sluttiness": 2,
      "comfort": 7,
      "durability": 8,
      "style": "cute",
      "colors": ["pink"],
      "tags": ["waterproof", "swim", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "swimsuit",
      "breasts": "swimsuit",
      "bottom": "swimsuit",
      "pussy": "swimsuit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "scarlit beach green bikini": toMap({
      "id": "scarlit beach green bikini",
      "category": "beach",
      "name": "green bikini",
      "flavor": "Natural tones make you look like a tigress, ready to pounce!",
      "description": "green bikini top and bottom",
      "price": 50,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 6,
      "style": "sexy",
      "colors": ["green"],
      "tags": ["swim"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "legs", "tummy", "cleavage"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "scarlit beach orange halter bikini": toMap({
      "id": "scarlit beach orange halter bikini",
      "category": "beach",
      "name": "orange halter bikini",
      "flavor": "Now *this* is super classy. Goes well with some nice hoop earrings!",
      "description": "orange halter bikini top and bottom",
      "price": 200,
      "type": "bikini",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 7,
      "style": "elegant",
      "colors": ["orange"],
      "tags": ["swim"],
      "emphasizes": ["cleavage"],
      "reveals": ["butt", "legs", "tummy", "cleavage"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "scarlit beach red triangle bikini": toMap({
      "id": "scarlit beach red triangle bikini",
      "category": "beach",
      "name": "red triangle bikini",
      "flavor": "This bikini is as basic as they come. But that just means you're the star of the show!",
      "description": "red triangle bikini top and bottom",
      "price": 40,
      "type": "bikini",
      "sluttiness": 5,
      "comfort": 7,
      "durability": 8,
      "style": "casual",
      "colors": ["red"],
      "tags": ["swim"],
      "emphasizes": ["cleavage"],
      "reveals": ["butt", "legs", "tummy", "cleavage"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "scarlit beach see through bikini": toMap({
      "id": "scarlit beach see through bikini",
      "category": "beach",
      "name": "see through bikini",
      "flavor": "The sluttiness factor is increased by the fact that your nipples are clearly visible.",
      "description": "blue see-through bikini",
      "price": 60,
      "type": "bikini",
      "sluttiness": 10,
      "comfort": 4,
      "durability": 8,
      "style": "slutty",
      "colors": ["blue"],
      "tags": ["swim", "see-through top", "transparent top"],
      "emphasizes": ["nipples"],
      "reveals": ["butt", "legs", "tummy", "cleavage", "nipples"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "scarlit beach sunflower bikini": toMap({
      "id": "scarlit beach sunflower bikini",
      "category": "beach",
      "name": "sunflower bikini",
      "flavor": "This has a really fun vibe! Perfect for playing some volleyball on the beach.",
      "description": "yellow bikini",
      "price": 50,
      "type": "bikini",
      "sluttiness": 6,
      "comfort": 7,
      "durability": 4,
      "style": "cute",
      "colors": ["yellow"],
      "tags": ["swim", "waterproof"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "legs", "tummy", "cleavage"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    }),
    "scarlit beach red v-neck": toMap({
      "id": "scarlit beach red v-neck",
      "category": "beach",
      "name": "red v-neck",
      "flavor": "The gold buttons add a classy touch to this swimsuit.",
      "description": "red v-neck",
      "price": 180,
      "type": "one-piece swimsuit",
      "sluttiness": 5,
      "comfort": 5,
      "durability": 6,
      "style": "elegant",
      "colors": ["red"],
      "tags": ["waterproof", "swim", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "swimsuit",
      "breasts": "swimsuit",
      "bottom": "swimsuit",
      "pussy": "swimsuit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["beach"]
    }),
    "scarlit beach knitted bikini": toMap({
      "id": "scarlit beach knitted bikini",
      "category": "beach",
      "name": "knitted bikini",
      "flavors": [
        "Better for lounging in the sun, but you can swim in this.",
        "So many strings! Hope it doesn't come undone..."
      ],
      "description": "knitted bikini top and knitted bikini thong",
      "price": 85,
      "type": "bikini",
      "sluttiness": 7,
      "comfort": 5,
      "durability": 3,
      "style": "sexy",
      "colors": ["brown", "black"],
      "tags": ["swim"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "legs", "tummy", "cleavage"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["beach"]
    }),
    "scarlit beach vixen bikini": toMap({
      "id": "scarlit beach vixen bikini",
      "category": "beach",
      "name": "vixen bikini",
      "flavor": "The white contrasts amazingly with your ass. Makes you look like a real piece of chocolate.",
      "description": "white bikini that says 'Vixen'",
      "price": 65,
      "type": "bikini",
      "sluttiness": 7,
      "comfort": 8,
      "durability": 6,
      "style": "sexy",
      "colors": ["white"],
      "tags": ["swim", "waterproof"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "legs", "tummy", "cleavage"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "bikini bottom",
      "pussy": "bikini bottom",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["beach"]
    })
  }),
  "casual": toMap({
    "scarlit casual baby blue booty shorts": toMap({
      "id": "scarlit casual baby blue booty shorts",
      "category": "casual",
      "name": "baby blue booty shorts",
      "flavor": "Perfect for wearing around the house or going to the mall.",
      "description": "white cropped tank top and blue shorts",
      "price": 40,
      "type": "casual",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 3,
      "style": "cute",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": ["tummy", "legs"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "scarlit casual blue jeans": toMap({
      "id": "scarlit casual blue jeans",
      "category": "casual",
      "name": "blue jeans",
      "flavor": "You're as corny as Kansas and August, you're as normal as blueberry pie.",
      "description": "brown tank top and jeans",
      "price": 55,
      "type": "casual",
      "sluttiness": 2,
      "comfort": 6,
      "durability": 10,
      "style": "casual",
      "colors": ["brown", "blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": [],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sneakers",
      "locations": ["casual", "lounge"]
    }),
    "scarlit casual green bra top": toMap({
      "id": "scarlit casual green bra top",
      "category": "casual",
      "name": "green bra top",
      "flavor": "A fairly sexy look, and you can definitely pull it off.",
      "description": "green bralette and jean shorts",
      "price": 40,
      "type": "casual",
      "sluttiness": 7,
      "comfort": 4,
      "durability": 3,
      "style": "sexy",
      "colors": ["green", "blue"],
      "tags": [],
      "emphasizes": [],
      "reveals": [],
      "top": "bralette",
      "breasts": "bralette",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "sandals",
      "locations": ["casual", "lounge"]
    }),
    "scarlit casual maroon sweater": toMap({
      "id": "scarlit casual maroon sweater",
      "category": "casual",
      "name": "maroon sweater",
      "flavor": "Comfy and classy.",
      "description": "maroon sweater and jeans",
      "price": 70,
      "type": "casual",
      "sluttiness": 2,
      "comfort": 8,
      "durability": 6,
      "style": "modest",
      "colors": ["red", "blue"],
      "tags": ["professional"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage"],
      "top": "sweater",
      "breasts": "sweater",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "flats",
      "locations": ["casual", "stylin", "office"]
    }),
    "scarlit casual red skirt": toMap({
      "id": "scarlit casual red skirt",
      "category": "casual",
      "name": "red skirt",
      "flavor": "The skirt goes swish, swish around your big hips and butt.",
      "description": "white crop top and red skirt",
      "price": 90,
      "type": "casual",
      "sluttiness": 8,
      "comfort": 9,
      "durability": 3,
      "style": "slutty",
      "colors": ["white", "red"],
      "tags": ["easy access skirt"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "tummy", "legs"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["casual", "stylin", "office"]
    }),
    "scarlit casual white tank top": toMap({
      "id": "scarlit casual white tank top",
      "category": "casual",
      "name": "white tank top",
      "flavors": [
        "Do you come with the car?",
        "Ready to get dirty in this."
      ],
      "description": "white tank top and blue jeans",
      "price": 45,
      "type": "casual",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 4,
      "style": "casual",
      "colors": ["white", "blue"],
      "tags": [],
      "emphasizes": ["tummy"],
      "reveals": ["tummy"],
      "top": "shirt",
      "breasts": "shirt",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "boots",
      "locations": ["casual"]
    }),
    "scarlit casual silky orange top": toMap({
      "id": "scarlit casual silky orange top",
      "category": "casual",
      "name": "silky orange top",
      "flavor": "Your ass hangs out of the shorts a bit. It's sexy, but casual too.",
      "description": "orange tank top and jean shorts",
      "price": 60,
      "type": "casual",
      "sluttiness": 7,
      "comfort": 7,
      "durability": 5,
      "style": "sexy",
      "colors": ["orange", "blue"],
      "tags": [],
      "emphasizes": ["asscheeks"],
      "reveals": ["asscheeks", "legs", "tummy"],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "jean shorts",
      "pussy": "jean shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "flats",
      "locations": ["casual", "lounge"]
    })
  }),
  "fetish": toMap({
    "scarlit fetish fishnet bra": toMap({
      "id": "scarlit fetish fishnet bra",
      "category": "fetish",
      "name": "fishnet bra",
      "flavor": "We've caught something, cap'n!",
      "description": "halter fishnet bra and panties",
      "price": 60,
      "type": "fetishwear",
      "sluttiness": 5,
      "comfort": 5,
      "durability": 3,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["see-through top", "transparent"],
      "emphasizes": ["nipples"],
      "reveals": ["nipples", "butt", "tummy", "legs", "boobs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    }),
    "scarlit fetish rainbow top": toMap({
      "id": "scarlit fetish rainbow top",
      "category": "fetish",
      "name": "rainbow top",
      "flavor": "You're sending a very clear message that says, 'I wanna sit on your cock.'",
      "description": "cropped rainbox top and thong",
      "price": 45,
      "type": "fetishwear",
      "sluttiness": 10,
      "comfort": 3,
      "durability": 2,
      "style": "slutty",
      "colors": ["pink"],
      "tags": [],
      "emphasizes": ["butt"],
      "reveals": ["butt", "tummy", "legs"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "thong",
      "pussy": "thong",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    }),
    "scarlit fetish black tie": toMap({
      "id": "scarlit fetish black tie",
      "category": "fetish",
      "name": "black tie",
      "flavor": "Probably shouldn't show up to a formal event in this outfit.",
      "description": "dress shirt, black tie, garter belt, stockings and panties",
      "price": 215,
      "type": "fetishwear",
      "sluttiness": 9,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["white", "black"],
      "tags": [],
      "emphasizes": ["butt"],
      "reveals": ["butt", "tummy", "legs"],
      "top": "shirt",
      "breasts": "shirt",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["fetish"]
    }),
    "scarlit fetish masquerade": toMap({
      "id": "scarlit fetish masquerade",
      "category": "fetish",
      "name": "masquerade",
      "flavor": "They'll want to know who's behind the mask.",
      "description": "red corset, gloves, boots and mask",
      "price": 275,
      "type": "fetishwear",
      "sluttiness": 8,
      "comfort": 3,
      "durability": 8,
      "style": "sexy",
      "colors": ["red"],
      "tags": ["one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "corset",
      "breasts": "corset",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "boots",
      "locations": ["fetish"]
    }),
    "scarlit fetish gold chains": toMap({
      "id": "scarlit fetish gold chains",
      "category": "fetish",
      "name": "gold chains",
      "flavor": "Expensive but so, so sexy.",
      "description": "black crop top and shorts with gold chains",
      "price": 450,
      "type": "fetishwear",
      "sluttiness": 8,
      "comfort": 2,
      "durability": 7,
      "style": "sexy",
      "colors": ["black", "gold"],
      "tags": [],
      "emphasizes": ["legs"],
      "reveals": ["tummy", "legs"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["fetish"]
    }),
    "scarlit fetish silver bodysuit": toMap({
      "id": "scarlit fetish silver bodysuit",
      "category": "fetish",
      "name": "silver bodysuit",
      "flavor": "Silver is second to none here.",
      "description": "silver bodysuit",
      "price": 275,
      "type": "fetishwear",
      "sluttiness": 7,
      "comfort": 3,
      "durability": 5,
      "style": "sexy",
      "colors": ["silver"],
      "tags": ["one piece"],
      "emphasizes": ["legs"],
      "reveals": ["legs", "cleavage"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["fetish"]
    }),
    "scarlit fetish disco vixen": toMap({
      "id": "scarlit fetish disco vixen",
      "category": "fetish",
      "name": "disco vixen",
      "flavors": [
        "Singlehandedly making sure it never dies.",
        "The roller skates are impractical but it's not disco without it!"
      ],
      "description": "white backless bodysuit",
      "price": 140,
      "type": "fetishwear",
      "sluttiness": 8,
      "comfort": 2,
      "durability": 4,
      "style": "cute",
      "colors": ["white"],
      "tags": ["one piece"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "legs"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "skates",
      "locations": ["fetish", "stylin"]
    }),
    "scarlit fetish red teddy": toMap({
      "id": "scarlit fetish red teddy",
      "category": "fetish",
      "name": "red teddy",
      "flavor": "Extremely classy, you look like a sugar baby in this.",
      "description": "red lacy teddy",
      "price": 150,
      "type": "fetishwear",
      "sluttiness": 5,
      "comfort": 8,
      "durability": 8,
      "style": "elegant",
      "colors": ["red"],
      "tags": ["easy access dress", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "teddy",
      "breasts": "teddy",
      "bottom": "teddy",
      "pussy": "teddy",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["fetish"]
    })
  }),
  "gym": toMap({
    "scarlit gym acrobatic suit": toMap({
      "id": "scarlit gym acrobatic suit",
      "category": "gym",
      "name": "acrobatic suit",
      "flavor": "Ready to do some handstands?",
      "description": "tan athletic bodysuit",
      "price": 100,
      "type": "fitness",
      "sluttiness": 4,
      "comfort": 4,
      "durability": 10,
      "style": "sexy",
      "colors": ["brown"],
      "tags": ["workout", "one piece"],
      "emphasizes": ["butt"],
      "reveals": ["butt", "legs", "cleavage"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["gym"]
    }),
    "scarlit gym pink gym outfit": toMap({
      "id": "scarlit gym pink gym outfit",
      "category": "gym",
      "name": "pink gym outfit",
      "flavor": "Great for HIIT!",
      "description": "pink sports bra and yoga shorts",
      "price": 80,
      "type": "fitness",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 6,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["workout"],
      "emphasizes": ["legs"],
      "reveals": ["tummy", "legs"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "yoga shorts",
      "pussy": "yoga shorts",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["gym"]
    }),
    "scarlit gym purple workout": toMap({
      "id": "scarlit gym purple workout",
      "category": "gym",
      "name": "purple workout",
      "flavor": "These pants really accentuate your massive ass.",
      "description": "white tank top and purple yoga pants",
      "price": 60,
      "type": "fitness",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 5,
      "style": "sexy",
      "colors": ["white", "purple"],
      "tags": ["great workout"],
      "emphasizes": ["butt"],
      "reveals": [],
      "top": "tank top",
      "breasts": "tank top",
      "bottom": "yoga pants",
      "pussy": "yoga pants",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["gym"]
    }),
    "scarlit gym tennis": toMap({
      "id": "scarlit gym tennis",
      "category": "gym",
      "name": "tennis",
      "flavor": "You'll be doing a lot of grunting in this outfit.",
      "description": "red sports bra and white skirt",
      "price": 90,
      "type": "fitness",
      "sluttiness": 6,
      "comfort": 5,
      "durability": 6,
      "style": "sexy",
      "colors": ["red", "white"],
      "tags": ["great workout"],
      "emphasizes": ["legs"],
      "reveals": ["legs", "tummy"],
      "top": "sports bra",
      "breasts": "sports bra",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "yes",
      "bra under": "no",
      "shoes": "sneakers",
      "locations": ["gym"]
    })
  }),
  "lingerie": toMap({
    "scarlit lingerie black lingerie": toMap({
      "id": "scarlit lingerie black lingerie",
      "category": "lingerie",
      "name": "black lingerie",
      "flavor": "Thongs are sexy as hell on you…",
      "description": "black bra and thong",
      "price": 50,
      "type": "lingerie",
      "sluttiness": 5,
      "comfort": 4,
      "durability": 3,
      "style": "sexy",
      "colors": ["black"],
      "tags": [],
      "emphasizes": ["butt"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "scarlit lingerie black mountainous lingerie": toMap({
      "id": "scarlit lingerie black mountainous lingerie",
      "category": "lingerie",
      "name": "black mountainous lingerie",
      "flavor": "He's gonna want to climb your mountains…",
      "description": "black patterned bra and high-waisted thong",
      "price": 60,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 5,
      "durability": 5,
      "style": "sexy",
      "colors": ["black"],
      "tags": [],
      "emphasizes": ["butt"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "scarlit lingerie lacy white bikini": toMap({
      "id": "scarlit lingerie lacy white bikini",
      "category": "lingerie",
      "name": "lacy white bikini",
      "flavor": "Mmm, the way this contrasts with your skin tone is chef's kiss!",
      "description": "white lacy bra and panties",
      "price": 80,
      "type": "lingerie",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 4,
      "style": "elegant",
      "colors": ["white"],
      "tags": [],
      "emphasizes": ["butt"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "scarlit lingerie pink boyshorts": toMap({
      "id": "scarlit lingerie pink boyshorts",
      "category": "lingerie",
      "name": "pink boyshorts",
      "flavor": "These remind you of wearing boxer briefs as a guy. But it's way more comfy without balls!",
      "description": "pink bra and boyshorts",
      "price": 50,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 9,
      "durability": 3,
      "style": "cute",
      "colors": ["pink"],
      "tags": [],
      "emphasizes": ["butt"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "boyshorts",
      "pussy": "boyshorts",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "scarlit lingerie pink silk": toMap({
      "id": "scarlit lingerie pink silk",
      "category": "lingerie",
      "name": "pink silk",
      "flavor": "Extremely classy, rich guys will come running!",
      "description": "pink silk bra and panties",
      "price": 190,
      "type": "lingerie",
      "sluttiness": 7,
      "comfort": 4,
      "durability": 8,
      "style": "elegant",
      "colors": ["pink"],
      "tags": ["rich magnet"],
      "emphasizes": ["butt"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "scarlit lingerie yellow lingerie": toMap({
      "id": "scarlit lingerie yellow lingerie",
      "category": "lingerie",
      "name": "yellow lingerie",
      "flavor": "You look like a bumblebee!",
      "description": "yellow bra and panties",
      "price": 40,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 5,
      "style": "cute",
      "colors": ["yellow"],
      "tags": [],
      "emphasizes": ["butt"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "scarlit lingerie white thong": toMap({
      "id": "scarlit lingerie white thong",
      "category": "lingerie",
      "name": "white thong",
      "flavor": "Just a thong, no bra.",
      "description": "white thong",
      "price": 20,
      "type": "lingerie",
      "sluttiness": 8,
      "comfort": 2,
      "durability": 1,
      "style": "slutty",
      "colors": ["white"],
      "tags": [],
      "emphasizes": ["butt"],
      "reveals": ["boobs", "tummy", "butt", "legs", "nipples"],
      "top": "nothing",
      "breasts": "nothing",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "scarlit lingerie swirly lingerie": toMap({
      "id": "scarlit lingerie swirly lingerie",
      "category": "lingerie",
      "name": "swirly lingerie",
      "flavor": "A lot of nice swirls and pattern-stitching to decorate your beautiful body!",
      "description": "black bra and panties",
      "price": 40,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 5,
      "style": "sexy",
      "colors": ["black"],
      "tags": [],
      "emphasizes": ["butt"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "scarlit lingerie red lingerie": toMap({
      "id": "scarlit lingerie red lingerie",
      "category": "lingerie",
      "name": "red lingerie",
      "flavor": "Perfect for Valentine's day!",
      "description": "red bra and panties",
      "price": 50,
      "type": "lingerie",
      "sluttiness": 5,
      "comfort": 6,
      "durability": 5,
      "style": "sexy",
      "colors": ["red"],
      "tags": [],
      "emphasizes": ["butt"],
      "reveals": ["cleavage", "tummy", "butt", "legs"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "scarlit lingerie royalty": toMap({
      "id": "scarlit lingerie royalty",
      "category": "lingerie",
      "name": "royalty",
      "flavors": [
        "The tiara signifies your high status.",
        "A princess wouldn't wear this, but you're a queen.",
        "Your subjects will bow before you."
      ],
      "description": "white transparent bodysuit lingerie",
      "price": 160,
      "type": "lingerie",
      "sluttiness": 7,
      "comfort": 4,
      "durability": 5,
      "style": "elegant",
      "colors": ["white"],
      "tags": ["see-through top", "transparent top", "one piece"],
      "emphasizes": ["nipples"],
      "reveals": ["cleavage", "butt", "legs", "nipples"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    }),
    "scarlit lingerie pink bodysuit": toMap({
      "id": "scarlit lingerie pink bodysuit",
      "category": "lingerie",
      "name": "pink bodysuit",
      "flavor": "It's super comfy.",
      "description": "pink bodysuit",
      "price": 45,
      "type": "lingerie",
      "sluttiness": 4,
      "comfort": 8,
      "durability": 8,
      "style": "cute",
      "colors": ["pink"],
      "tags": ["one piece"],
      "emphasizes": ["butt"],
      "reveals": ["cleavage", "butt", "legs"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lingerie"]
    })
  }),
  "lounge": toMap({
    "scarlit lounge bathrobe": toMap({
      "id": "scarlit lounge bathrobe",
      "category": "lounge",
      "name": "bathrobe",
      "flavor": "A nice waffle-knit bathrobe!",
      "description": "bathrobe",
      "price": 40,
      "type": "loungewear",
      "sluttiness": 3,
      "comfort": 9,
      "durability": 8,
      "style": "casual",
      "colors": ["grey"],
      "tags": ["sleep", "one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "cleavage"],
      "top": "bathrobe",
      "breasts": "bathrobe",
      "bottom": "bathrobe",
      "pussy": "bathrobe",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "scarlit lounge denim crop top": toMap({
      "id": "scarlit lounge denim crop top",
      "category": "lounge",
      "name": "denim crop top",
      "flavor": "You'd think the fabric wouldn't be comfy but it kind of is!",
      "description": "denim crop top and lace panties",
      "price": 75,
      "type": "loungewear",
      "sluttiness": 8,
      "comfort": 6,
      "durability": 4,
      "style": "sexy",
      "colors": ["blue"],
      "tags": ["sleep"],
      "emphasizes": ["legs", "cleavage"],
      "reveals": ["cleavage", "belly", "legs", "asscheeks"],
      "top": "crop top",
      "breasts": "crop top",
      "bottom": "panties",
      "pussy": "panties",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "scarlit lounge big t-shirt": toMap({
      "id": "scarlit lounge big t-shirt",
      "category": "lounge",
      "name": "big t-shirt",
      "flavor": "Literally just a big t-shirt.",
      "description": "big t-shirt",
      "price": 20,
      "type": "loungewear",
      "sluttiness": 5,
      "comfort": 7,
      "durability": 6,
      "style": "sexy",
      "colors": ["orange"],
      "tags": ["sleep", "one piece", "masculine", "easy access dress"],
      "emphasizes": ["asscheeks"],
      "reveals": ["asscheeks", "legs"],
      "top": "t-shirt",
      "breasts": "t-shirt",
      "bottom": "t-shirt",
      "pussy": "t-shirt",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "scarlit lounge comfy pjs": toMap({
      "id": "scarlit lounge comfy pjs",
      "category": "lounge",
      "name": "comfy pjs",
      "flavor": "An adorable little button-down playsuit.",
      "description": "off-shoulder playsuit",
      "price": 60,
      "type": "loungewear",
      "sluttiness": 3,
      "comfort": 8,
      "durability": 8,
      "style": "cute",
      "colors": ["white"],
      "tags": ["sleep", "one piece", "buttons"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "playsuit",
      "breasts": "playsuit",
      "bottom": "playsuit",
      "pussy": "playsuit",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    }),
    "scarlit lounge good luck": toMap({
      "id": "scarlit lounge good luck",
      "category": "lounge",
      "name": "good luck",
      "flavors": [
        "A thrown together outfit that somehow works!",
        "Easy to do work around the house in this.",
        "The cat t-shirt brings good fortune, they say."
      ],
      "description": "blue t-shirt and jean shorts",
      "price": 35,
      "type": "loungewear",
      "sluttiness": 3,
      "comfort": 7,
      "durability": 5,
      "style": "casual",
      "colors": ["blue"],
      "tags": ["chores"],
      "emphasizes": [],
      "reveals": ["tummy", "legs"],
      "top": "t-shirt",
      "breasts": "t-shirt",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "sandals",
      "locations": ["lounge"]
    }),
    "scarlit lounge green shorts": toMap({
      "id": "scarlit lounge green shorts",
      "category": "lounge",
      "name": "green shorts",
      "flavor": "Can you get away with wearing a bra around the house? Let's find out!",
      "description": "bra and shorts",
      "price": 45,
      "type": "loungewear",
      "sluttiness": 8,
      "comfort": 5,
      "durability": 4,
      "style": "sexy",
      "colors": ["white", "green"],
      "tags": ["sleep"],
      "emphasizes": ["cleavage"],
      "reveals": ["tummy", "cleavage", "legs", "asscheeks"],
      "top": "bra",
      "breasts": "bra",
      "bottom": "shorts",
      "pussy": "shorts",
      "breast support": 0,
      "panties under": "can",
      "bra under": "no",
      "shoes": "none",
      "locations": ["lounge"]
    })
  }),
  "office": toMap({
    "scarlit office black dress": toMap({
      "id": "scarlit office black dress",
      "category": "office",
      "name": "black dress",
      "flavor": "Sexy and no-nonsense.",
      "description": "office dress",
      "price": 140,
      "type": "dress",
      "sluttiness": 3,
      "comfort": 8,
      "durability": 7,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["easy access dress"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "scarlit office pink blouse": toMap({
      "id": "scarlit office pink blouse",
      "category": "office",
      "name": "pink blouse",
      "flavor": "Comfortable and cute, perfect to keep you cool during a sale.",
      "description": "pink blouse and black skirt",
      "price": 110,
      "type": "dress",
      "sluttiness": 3,
      "comfort": 8,
      "durability": 7,
      "style": "cute",
      "colors": ["pink", "black"],
      "tags": ["easy access skirt", "very professional"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    }),
    "scarlit office maroon skirt": toMap({
      "id": "scarlit office maroon skirt",
      "category": "office",
      "name": "maroon skirt",
      "flavor": "This skirt really flatters your butt.",
      "description": "maroon skirt and white blouse",
      "price": 130,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 6,
      "durability": 5,
      "style": "sexy",
      "colors": ["white", "red"],
      "tags": ["easy access skirt", "very professional"],
      "emphasizes": ["butt"],
      "reveals": ["legs"],
      "top": "blouse",
      "breasts": "blouse",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["office"]
    })
  }),
  "stylin": toMap({
    "scarlit stylin black satin dress": toMap({
      "id": "scarlit stylin black satin dress",
      "category": "stylin",
      "name": "black satin dress",
      "flavor": "Comfy and hugs your curves.",
      "description": "black satin tube dress",
      "price": 130,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 7,
      "durability": 5,
      "style": "sexy",
      "colors": ["black"],
      "tags": ["easy access dress", "one piece"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "scarlit stylin pink skirt": toMap({
      "id": "scarlit stylin pink skirt",
      "category": "stylin",
      "name": "pink skirt",
      "flavors": [
        "Classy but also promiscuous.",
        "You look like an expensive lady of the night in this."
      ],
      "description": "pink bikini top and pink skirt",
      "price": 235,
      "type": "stylish outfit",
      "sluttiness": 8,
      "comfort": 4,
      "durability": 4,
      "style": "slutty",
      "colors": ["black", "blue"],
      "tags": ["easy access skirt"],
      "emphasizes": ["tummy"],
      "reveals": ["tummy", "cleavage", "legs"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "skirt",
      "pussy": "skirt",
      "breast support": 0,
      "panties under": "yes",
      "bra under": "no",
      "shoes": "boots",
      "locations": ["stylin"]
    }),
    "scarlit stylin burgundy sequins": toMap({
      "id": "scarlit stylin burgundy sequins",
      "category": "stylin",
      "name": "burgundy sequins",
      "flavor": "Wouldn't look out of place at a black tie event or gala.",
      "description": "sparkly burgundy dress",
      "price": 400,
      "type": "dress",
      "sluttiness": 3,
      "comfort": 3,
      "durability": 9,
      "style": "elegant",
      "colors": ["red"],
      "tags": ["one piece", "rich magnet"],
      "emphasizes": [],
      "reveals": ["legs"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "scarlit stylin fancy dress": toMap({
      "id": "scarlit stylin fancy dress",
      "category": "stylin",
      "name": "fancy dress",
      "flavor": "An incredible designer look. Is it worth the price?",
      "description": "flowy pink designer dress",
      "price": 650,
      "type": "dress",
      "sluttiness": 5,
      "comfort": 9,
      "durability": 10,
      "style": "elegant",
      "colors": ["pink"],
      "tags": ["one piece", "rich magnet"],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "cleavage"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "scarlit stylin golden sequins": toMap({
      "id": "scarlit stylin golden sequins",
      "category": "stylin",
      "name": "golden sequins",
      "flavor": "A boxy, roaring 20s look.",
      "description": "golden sequin dress",
      "price": 240,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 4,
      "durability": 7,
      "style": "elegant",
      "colors": ["yellow"],
      "tags": ["one piece", "waterproof"],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "cleavage"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "scarlit stylin little white dress": toMap({
      "id": "scarlit stylin little white dress",
      "category": "stylin",
      "name": "little white dress",
      "flavor": "Makes you look extremely cute and innocent!",
      "description": "white dress",
      "price": 120,
      "type": "dress",
      "sluttiness": 5,
      "comfort": 8,
      "durability": 3,
      "style": "cute",
      "colors": ["white"],
      "tags": ["one piece", "easy access dress", "short dress"],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "cleavage"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "lounge", "casual"]
    }),
    "scarlit stylin pineapples": toMap({
      "id": "scarlit stylin pineapples",
      "category": "stylin",
      "name": "pineapples",
      "flavor": "A fun pineapple-patterned bodysuit.",
      "description": "pink pineapple bodysuit",
      "price": 150,
      "type": "dress",
      "sluttiness": 6,
      "comfort": 8,
      "durability": 7,
      "style": "sexy",
      "colors": ["pink"],
      "tags": ["one piece", "sleep"],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "cleavage"],
      "top": "bodysuit",
      "breasts": "bodysuit",
      "bottom": "bodysuit",
      "pussy": "bodysuit",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin", "lounge", "casual"]
    }),
    "scarlit stylin dress jacket": toMap({
      "id": "scarlit stylin dress jacket",
      "category": "stylin",
      "name": "dress jacket",
      "flavor": "You'll be demanding more than just attention in these thigh high boots.",
      "description": "red jacket and black dress",
      "price": 225,
      "type": "dress",
      "sluttiness": 7,
      "comfort": 3,
      "durability": 4,
      "style": "sexy",
      "colors": ["red", "black"],
      "tags": ["easy access skirt", "short dress"],
      "emphasizes": ["cleavage"],
      "reveals": ["cleavage", "belly"],
      "top": "jacket",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "boots",
      "locations": ["stylin"]
    }),
    "scarlit stylin loose pink dress": toMap({
      "id": "scarlit stylin loose pink dress",
      "category": "stylin",
      "name": "loose pink dress",
      "flavor": "Classy! And very short.",
      "description": "pink dress with a plunging neckline",
      "price": 130,
      "type": "dress",
      "sluttiness": 7,
      "comfort": 8,
      "durability": 5,
      "style": "elegant",
      "colors": ["pink"],
      "tags": ["one piece", "short dress", "easy access dress"],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "cleavage"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    }),
    "scarlit stylin bad girl": toMap({
      "id": "scarlit stylin bad girl",
      "category": "stylin",
      "name": "bad girl",
      "flavors": [
        "What trouble are you getting into tonight?",
        "Keep the jeans undone for easy access."
      ],
      "description": "black bikini top and bottoms, blue jeans",
      "price": 160,
      "type": "stylish outfit",
      "sluttiness": 9,
      "comfort": 6,
      "durability": 3,
      "style": "slutty",
      "colors": ["black", "blue"],
      "tags": [],
      "emphasizes": ["tummy"],
      "reveals": ["tummy", "cleavage"],
      "top": "bikini top",
      "breasts": "bikini top",
      "bottom": "jeans",
      "pussy": "jeans",
      "breast support": 0,
      "panties under": "no",
      "bra under": "no",
      "shoes": "heels",
      "locations": ["stylin", "casual"]
    }),
    "scarlit stylin sequin dress": toMap({
      "id": "scarlit stylin sequin dress",
      "category": "stylin",
      "name": "sequin dress",
      "flavor": "You like shiny dresses!",
      "description": "sparkly backless dress",
      "price": 150,
      "type": "dress",
      "sluttiness": 4,
      "comfort": 4,
      "durability": 3,
      "style": "elegant",
      "colors": ["grey"],
      "tags": ["one piece"],
      "emphasizes": ["cleavage"],
      "reveals": ["legs", "cleavage"],
      "top": "dress",
      "breasts": "dress",
      "bottom": "dress",
      "pussy": "dress",
      "breast support": 0,
      "panties under": "can",
      "bra under": "can",
      "shoes": "heels",
      "locations": ["stylin"]
    })
  })
}));